### ISSUE TITLE
v2.27.0 - Endless loop at login - Cannot assign array to property MailSo\Imap\Folder::$MAILBOXID

### ISSUE THREAD

**Issue by cm-schl** [the-djmaze/snappymail#1032]
When trying to login to SnappyMail after the update to v2.27.0 on a Nextcloud install the site is loaded again and again.

- Browser: Firefox 102.9.0esr
- IMAP daemon: Cyrus
- SnappyMail Version: v2.27.0

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
```
[2023-03-21 10:23:13.171][5e7cb688] IMAP[INFO]: > TAG3 LIST "" "*" RETURN (SUBSCRIBED SPECIAL-USE STATUS (MESSAGES UNSEEN UIDNEXT UIDVALIDITY HIGHESTMODSEQ MAILBOXID))\r\n
[2023-03-21 10:23:13.186][5e7cb688] IMAP[INFO]: < * LIST (\Subscribed \HasChildren) "." INBOX\r\n
[2023-03-21 10:23:13.186][5e7cb688] IMAP[INFO]: < * STATUS INBOX (MESSAGES 5348 UIDNEXT 8456 UIDVALIDITY 1655807763 MAILBOXID (`�li4V) UNSEEN 2 HIGHESTMODSEQ 23074)\r\n
[2023-03-21 10:23:13.186][5e7cb688] SERVICE[WARNING]: Cannot assign array to property MailSo\Imap\Folder::$MAILBOXID of type ?string
#0 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/MailSo/Imap/Traits/Status.php(164): MailSo\Imap\Folder->setStatusItem()
#1 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/MailSo/Imap/Commands/Folders.php(521): MailSo\Imap\Folder->setStatusFromResponse()
#2 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/MailSo/Imap/Commands/Folders.php(603): MailSo\Imap\ImapClient->FolderList()
#3 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/MailSo/Mail/MailClient.php(772): MailSo\Imap\ImapClient->FolderStatusList()
#4 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/RainLoop/Actions/Folders.php(58): MailSo\Mail\MailClient->Folders()
#5 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoFolders()
#6 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#7 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#8 /var/www/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php(97): RainLoop\Service::Handle()
#9 /var/www/nextcloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp()
#10 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->indexPost()
#11 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#12 /var/www/nextcloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#13 /var/www/nextcloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#14 /var/www/nextcloud/lib/base.php(1047): OC\Route\Router->match()
#15 /var/www/nextcloud/index.php(36): OC::handleRequest()
#16 {main}
[2023-03-21 10:23:13.186][5e7cb688] [NOTICE]: TypeError: Cannot assign array to property MailSo\Imap\Folder::$MAILBOXID of type ?string in /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/MailSo/Imap/Traits/Status.php:123
Stack trace:
#0 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/MailSo/Imap/Traits/Status.php(164): MailSo\Imap\Folder->setStatusItem()
#1 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/MailSo/Imap/Commands/Folders.php(521): MailSo\Imap\Folder->setStatusFromResponse()
#2 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/MailSo/Imap/Commands/Folders.php(603): MailSo\Imap\ImapClient->FolderList()
#3 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/MailSo/Mail/MailClient.php(772): MailSo\Imap\ImapClient->FolderStatusList()
#4 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/RainLoop/Actions/Folders.php(58): MailSo\Mail\MailClient->Folders()
#5 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoFolders()
#6 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#7 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.27.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#8 /var/www/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php(97): RainLoop\Service::Handle()
#9 /var/www/nextcloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp()
#10 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->indexPost()
#11 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#12 /var/www/nextcloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#13 /var/www/nextcloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#14 /var/www/nextcloud/lib/base.php(1047): OC\Route\Router->match()
#15 /var/www/nextcloud/index.php(36): OC::handleRequest()
#16 {main}
```

**Additional context**
Had a look into the log files before the update - the value behind the log entries `STATUS INBOX` is always something cryptic like "`�li4V".

Maybe commit b7963eb has something to do with it?

**Comment by the-djmaze** [comment]
MailSo IMAP parser converts '(....)' into an array. This should be fixed now.
