### ISSUE TITLE
2.27.2 upgrade causes AuthError and Call to a member function ImapConnectAndLogin() on null

### ISSUE THREAD

**Issue by jas8522** [the-djmaze/snappymail#1060]
**Describe the bug**

Authentication works great with 2.24.4. Upgraded to 2.27.2 and I'm unable to authenticate with any remote server. Authentication works fine with any accounts on the local server where snappymail is installed.

I rolled back to 2.24.4 and authentication works fine again.

Logs say:

```
[2023-03-30 15:07:34.621][72eac484] [ERROR]: Error: Call to a member function ImapConnectAndLogin() on null in snappymail/v/2.27.2/app/libraries/RainLoop/Actions.php:1073
Stack trace:
#0 snappymail/v/2.27.2/app/libraries/RainLoop/Actions/Folders.php(267): RainLoop\Actions->initMailClientConnection()
#1 snappymail/v/2.27.2/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoFolderInformation()
#2 snappymail/v/2.27.2/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#3 snappymail/v/2.27.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#4 snappymail/v/2.27.2/include.php(143): RainLoop\Service::Handle()
#5 index.php(11): include('...')
#6 {main}

Next RainLoop\Exceptions\ClientException: AuthError[102] in snappymail/v/2.27.2/app/libraries/RainLoop/Actions.php:1077
Stack trace:
#0 snappymail/v/2.27.2/app/libraries/RainLoop/Actions/Folders.php(267): RainLoop\Actions->initMailClientConnection()
#1 snappymail/v/2.27.2/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoFolderInformation()
#2 snappymail/v/2.27.2/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#3 snappymail/v/2.27.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#4 snappymail/v/2.27.2/include.php(143): RainLoop\Service::Handle()
#5 index.php(11): include('...')
```

**Expected behavior**
When logging in to any account that worked fine with 2.24.4, I'm also able to login using 2.27.2

**Please complete the following information:**
- Browser: Firefox 111.0.1 (had reports from other users using Chrome)
- IMAP daemon: dovecot
- PHP version: 8.1
- SnappyMail Version: 2.27.2

**Additional context**
The auto domain grabber plugin is being used - might be related to that.
No domains are defined other than 'auto' for that plugin. Even the domain we access email accounts on the local server where snappy is installed is not added to the list - it uses the auto domain grabber plugin.

Thanks as always for the assistance!

**Comment by jas8522** [comment]
If anyone still has issues logging in after the 2.27.x upgrade, the issue was with the Mailbox Detect plugin being outdated. I updated it, and issue resolved!
