### ISSUE TITLE
An error occurred. Please refresh the page and try again.TypeError: Failed to fetch

### ISSUE THREAD

**Issue by scarleo** [the-djmaze/snappymail#1068]
**Describe the bug**
After latest update on Nextcloud I cannot see the email plugin at all:
"An error occurred.
Please refresh the page and try again.TypeError: Failed to fetch"

**To Reproduce**
1. Upgrade to latest release 2.27.3
2. Go to Email in Nextcloud
3. See error

**Expected behavior**
I would see my email

**Please complete the following information:**
- Browser: Chromium
- IMAP daemon: dovecot
- PHP version: 8.1
- SnappyMail Version: 2.27.3

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**
Nextcloud 25.0.5

**Comment by scarleo** [comment]
This is in the log:

`[2023-04-04 12:03:29.508][f46e7b0f] Crypt[WARNING]: Decrypt() invalid $data or $key
[2023-04-04 12:03:29.508][f46e7b0f] smremember[NOTICE]: decrypt
[2023-04-04 12:03:29.508][f46e7b0f] Crypt[WARNING]: Decrypt() invalid $data or $key
[2023-04-04 12:03:29.508][f46e7b0f] smremember[NOTICE]: invalid
[2023-04-04 12:03:29.510][f46e7b0f] SERVICE[WARNING]: InvalidToken[101]
#0 /var/www/clients/client1/web20/web/apps/snappymail/app/snappymail/v/2.27.3/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#1 /var/www/clients/client1/web20/web/apps/snappymail/app/snappymail/v/2.27.3/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#2 /var/www/clients/client1/web20/web/apps/snappymail/lib/Util/SnappyMailHelper.php(97): RainLoop\Service::Handle()
#3 /var/www/clients/client1/web20/web/apps/snappymail/lib/Controller/PageController.php(26): OCA\SnappyMail\Util\SnappyMailHelper::startApp()
#4 /var/www/clients/client1/web20/web/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->index()
#5 /var/www/clients/client1/web20/web/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#6 /var/www/clients/client1/web20/web/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#7 /var/www/clients/client1/web20/web/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#8 /var/www/clients/client1/web20/web/lib/base.php(1047): OC\Route\Router->match()
#9 /var/www/clients/client1/web20/web/index.php(36): OC::handleRequest()
#10 {main}
[2023-04-04 12:03:29.510][f46e7b0f] [NOTICE]: RainLoop\Exceptions\ClientException: InvalidToken[101] in /var/www/clients/client1/web20/web/apps/snappymail/app/snappymail/v/2.27.3/app/libraries/RainLoop/ServiceActions.php:104
Stack trace:
#0 /var/www/clients/client1/web20/web/apps/snappymail/app/snappymail/v/2.27.3/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#1 /var/www/clients/client1/web20/web/apps/snappymail/app/snappymail/v/2.27.3/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#2 /var/www/clients/client1/web20/web/apps/snappymail/lib/Util/SnappyMailHelper.php(97): RainLoop\Service::Handle()
#3 /var/www/clients/client1/web20/web/apps/snappymail/lib/Controller/PageController.php(26): OCA\SnappyMail\Util\SnappyMailHelper::startApp()
#4 /var/www/clients/client1/web20/web/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->index()
#5 /var/www/clients/client1/web20/web/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#6 /var/www/clients/client1/web20/web/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#7 /var/www/clients/client1/web20/web/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#8 /var/www/clients/client1/web20/web/lib/base.php(1047): OC\Route\Router->match()
#9 /var/www/clients/client1/web20/web/index.php(36): OC::handleRequest()
#10 {main}
[2023-04-04 12:03:29.510][f46e7b0f] JSON[INFO]: {"Action":"Message","Result":false,"ErrorCode":101,"ErrorMessage":"","ErrorMessageAdditional":"Token mismatch","epoch":1680609809}
[2023-04-04 12:03:29.592][f46e7b0f] [INFO]: Memory peak usage: 8MB
[2023-04-04 12:03:29.592][f46e7b0f] [INFO]: Time delta: 0.16404390335083
`

**Comment by the-djmaze** [comment]
Please read #1069
