### ISSUE TITLE
Error: Undefined constant "SIGCLD" in ...

### ISSUE THREAD

**Issue by k4my4b** [the-djmaze/snappymail#1147]
**Describe the bug**
upgrading to v2.28.0 will crash nextcloud 
installing v2.28.0 will fail

**To Reproduce**
1. Upgrade to v2.28.0 (maintenance mode will be activated)
2. perform 'occ upgrade'

~~**Expected behavior**~~

~~**Screenshots**~~

**Please complete the following information:**
- Browser: chromium Version 114.0.5735.45 (Official Build) Arch Linux (64-bit)
- IMAP daemon: dovecot (mailcow)
- PHP version: 8.0.28
- SnappyMail Version: v2.28.0
- Mode: nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
```
An unhandled exception has been thrown:
Error: Undefined constant "SIGCLD" in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.28.0/app/libraries/MailSo/Log/Logger.php:78
Stack trace:
#0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.28.0/app/libraries/MailSo/Log/Logger.php(78): constant('SIGCLD')
#1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.28.0/app/libraries/RainLoop/Api.php(64): MailSo\Log\Logger->__construct(true)
#2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.28.0/app/libraries/snappymail/log.php(40): RainLoop\Api::Logger()
#3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.28.0/app/libraries/snappymail/log.php(12): SnappyMail\Log::log(6, 'INSTALLER', 'Start package i...')
#4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.28.0/app/libraries/snappymail/repository.php(273): SnappyMail\Log::info('INSTALLER', 'Start package i...')
#5 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.28.0/setup.php(159): SnappyMail\Repository::installPackage('plugin', 'nextcloud')
#6 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.28.0/include.php(110): include('/var/www/html/c...')
#7 /var/www/html/custom_apps/snappymail/app/index.php(11): include('/var/www/html/c...')
#8 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(31): require_once('/var/www/html/c...')
#9 /var/www/html/custom_apps/snappymail/lib/Migration/InstallStep.php(27): OCA\SnappyMail\Util\SnappyMailHelper::loadApp()
#10 /var/www/html/lib/private/Repair.php(127): OCA\SnappyMail\Migration\InstallStep->run(Object(OC\Repair))
#11 /var/www/html/lib/private/legacy/OC_App.php(1068): OC\Repair->run()
#12 /var/www/html/lib/private/legacy/OC_App.php(1010): OC_App::executeRepairSteps('snappymail', Array)
#13 /var/www/html/lib/private/Updater.php(361): OC_App::updateApp('snappymail')
#14 /var/www/html/lib/private/Updater.php(273): OC\Updater->doAppUpgrade()
#15 /var/www/html/lib/private/Updater.php(141): OC\Updater->doUpgrade('25.0.6.1', '25.0.6.1')
#16 /var/www/html/core/Command/Upgrade.php(225): OC\Updater->upgrade()
#17 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/console.php(100): OC\Console\Application->run()
#23 /var/www/html/occ(11): require_once('/var/www/html/c...')
```
**Additional context**
Additional context
In case anyone else happens to experience the same issue, here's a couple of simple steps to roll back to the previous version: (assuming you are on nextcloud docker)

1. disable the app from nextcloud apps menu or `occ app:disable snappymail`
2. `docker exec -it -u www-data <your nextcloud instance> bash`
3. `cd /var/www/html/custom_apps/`
4. `rm -fr snappymail`
5. `curl https://snappymail.eu/repository/nextcloud/snappymail-2.27.3-nextcloud.tar.gz | tar -xzvf -`
7. enable snappymail again `occ app:enable snappymail`

**Comment by joergmschulz** [comment]
alternatively you can comment out SIGCLD in line 34 of this file, but ......

**Comment by ChiefPete** [comment]
Is there going to be a release with [commit](https://github.com/the-djmaze/snappymail/commit/9eaa0f4eb52a223b16332bfe445c5684a52b8b57)? or do I have to manually edit the file so my users can access their emails through Nextcloud.

Thanks.

**Comment by the-djmaze** [comment]
I will make new release
