### ISSUE TITLE
Encryption method doesn't fit on ChangePassword Plugin

### ISSUE THREAD

**Issue by Nono-m0le** [the-djmaze/snappymail#1219]
**SnappyMail version, browser, browser version:**
2.28.4, Firefox, 115.0.2 (64 bits)

**Expected behavior and actual behavior:**
I wanted to setup the plugin "ChangePassword" but I'm struggeling to make it works and I think it's related to the encryption method.

No matter which settings I setup as ENCRYPTION & ENCRYPT I always end-up with the following error:

The first time I try to change (which clear all the field current / new password / new password) : 
```
[2023-07-19 21:29:35.723][79efc122] [INFO]: [SM:2.28.4][IP:x.x.x.X][PID:832864][nginx/][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://domain.tld/?/Json/&q[]=/0/]
[2023-07-19 21:29:35.730][79efc122] JSON[INFO]: Action: DoPluginChangePassword
[2023-07-19 21:29:35.730][79efc122] POST[INFO]: {"PrevPassword":"*******","NewPassword":"*******","Action":"PluginChangePassword"}
[2023-07-19 21:29:36.022][79efc122] [INFO]: PDO password changed for test@domain.tld
[2023-07-19 21:29:36.022][79efc122] COOKIE[DEBUG]: set smaccount
[2023-07-19 21:29:36.035][79efc122] SQL[INFO]: SELECT MAX(value_int) FROM rainloop_system WHERE sys_name = ?
[2023-07-19 21:29:36.036][79efc122] SQL[INFO]: SELECT id_user FROM rainloop_users WHERE rl_email = :rl_email
[2023-07-19 21:29:36.040][79efc122] JSON[INFO]: {"Action":"PluginChangePassword","Result":{"Auth":true,"title":"SnappyMail Webmail","loadingDescription":"SnappyMail","Plugins":{"change-password":{"pass_min_length":8,"pass_min_strength":20}},"System":{"version":"2.28.4","token":"xxxxx","languages":["ar-SA","bg-BG...
[2023-07-19 21:29:36.041][79efc122] [INFO]: Memory peak usage: 2MB
[2023-07-19 21:29:36.041][79efc122] [INFO]: Time delta: 0.33212685585022 
```

Then at the 2nd attempt : 

```
[2023-07-19 21:32:17.972][1144786d] [INFO]: [SM:2.28.4][IP:x.x.x.x][PID:831033][nginx/][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://domain.tld/?/Json/&q[]=/0/]
[2023-07-19 21:32:17.981][1144786d] JSON[INFO]: Action: DoPluginChangePassword
[2023-07-19 21:32:17.981][1144786d] POST[INFO]: {"PrevPassword":"*******","NewPassword":"*******","Action":"PluginChangePassword"}
[2023-07-19 21:32:17.985][1144786d] SERVICE[WARNING]: UnknownNotification[131]
#0 /<path_to>/snappymail/v/2.28.4/app/libraries/RainLoop/Plugins/Manager.php(372): ChangePasswordPlugin->ChangePassword()
#1 /<path_to>/snappymail/v/2.28.4/app/libraries/RainLoop/ServiceActions.php(145): RainLoop\Plugins\Manager->RunAdditionalJson()
#2 /<path_to>/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#3 /<path_to>/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#4 /<path_to>/snappymail/v/2.28.4/include.php(143): RainLoop\Service::Handle()
#5 /<path_to>/index.php(11): include('/<path_to>..')
#6 {main}
[2023-07-19 21:32:17.986][1144786d] [NOTICE]: RainLoop\Exceptions\ClientException: UnknownNotification[131] in /<path_to>/data/_data_/_default_/plugins/change-password/index.php:150
Stack trace:
#0 /<path_to>/snappymail/v/2.28.4/app/libraries/RainLoop/Plugins/Manager.php(372): ChangePasswordPlugin->ChangePassword()
#1 /<path_to>/snappymail/v/2.28.4/app/libraries/RainLoop/ServiceActions.php(145): RainLoop\Plugins\Manager->RunAdditionalJson()
#2 /<path_to>/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#3 /<path_to>/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#4 /<path_to>/snappymail/v/2.28.4/include.php(143): RainLoop\Service::Handle()
#5 /<path_to>/index.php(11): include('/<path_to>...')
#6 {main}
[2023-07-19 21:32:17.987][1144786d] JSON[INFO]: {"Action":"PluginChangePassword","Result":false,"ErrorCode":131,"ErrorMessage":"","ErrorMessageAdditional":"NOTIFICATIONS\/CURRENT_PASSWORD_INCORRECT","epoch":1689802337}
[2023-07-19 21:32:17.989][1144786d] [INFO]: Memory peak usage: 2MB
[2023-07-19 21:32:17.989][1144786d] [INFO]: Time delta: 0.0261549949646
```

**Steps to reproduce the problem:**
Both my dovecot & postfixadmin (to create new user) use "SHA512-CRYPT" as encryption method.
```
# cat /etc/dovecot/dovecot-sql.conf.ext | grep ^default_pass_scheme
default_pass_scheme = SHA512-CRYPT

# cat <path_to_postfixadmin>/config.local.php | grep encrypt
$CONF['encrypt'] = "php_crypt:SHA512";
```
I got the php_crypt:SHA512 from here : https://github.com/postfixadmin/postfixadmin/issues/567#issuecomment-984690398

**Logs or screenshots:**
On the changePassword settings, I try to setup almost all kind of combination (none / SHA512, bcrypt / SHA512) and I always (at the 2nd attempts) got the CURRENT_PASSWORD_INCORRECT error (despite using the good one, obviously).

**Comment by the-djmaze** [comment]
It depends how you configured dovecot and postfix.

When postfix is using the dovecot SASL, there's not much you need to do.
```
Encryption: bcrypt
Encrypt prefix: {BLF-CRYPT}
```
```
Encryption: SHA512-CRYPT
Encrypt prefix: {SHA512-CRYPT}
```

For a better understanding we need to see your SQL statement.

**Comment by Nono-m0le** [comment]
thanks for the answer @the-djmaze .
My SQL statement is
`UPDATE mailbox SET password = :newpass WHERE domain = :domain AND username = :username and password = :oldpass`

But if my dovecot SASL use SHA512, this still doesn't work using the plugin (it does using postfix admin)

**Comment by the-djmaze** [comment]
Best to remove `and password = :oldpass`
