### ISSUE TITLE
Outgoing email: "Can't connect to server"

### ISSUE THREAD

**Issue by tmlmt** [the-djmaze/snappymail#1233]
**Describe the bug**
Can't send new email nor reply to email

**To Reproduce**
Steps to reproduce the behavior: reply to an email or send a new one

**Expected behavior**
Email sent without error

**Screenshots**
![image](https://github.com/the-djmaze/snappymail/assets/10244927/296d4d8b-cafc-4c15-8531-e0a0eee2b61b)

**Please complete the following information:**
- Browser: Chrome
- IMAP daemon: dovecot
- PHP version: 8.1.21
- SnappyMail Version: 2.28.4
- Mode: nextcloud

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
```
[2023-08-21 07:54:54.754][2e1ff7af] SERVICE[WARNING]: - Can't connect to host "tcp://localhost:25" @ /var/www                                               /cloud/apps/snappymail/app/snappymail/v/2.28.4/app/libraries/MailSo/Net/NetClient.php#138
[2023-08-21 07:54:54.755][2e1ff7af] [ERROR]: MailSo\Net\Exceptions\SocketCanNotConnectToHostException: Can't                                                connect to host "tcp://localhost:25" in /var/www/cloud/apps/snappymail/app/snappymail/v/2.28.4/app/libr                                               aries/MailSo/Net/NetClient.php:138
Stack trace:
#0 /var/www/cloud/apps/snappymail/app/snappymail/v/2.28.4/app/libraries/MailSo/Smtp/SmtpClient.php(79):                                                MailSo\Net\NetClient->Connect()
#1 /var/www/cloud/apps/snappymail/app/snappymail/v/2.28.4/app/libraries/RainLoop/Model/Account.php(254)                                               : MailSo\Smtp\SmtpClient->Connect()
#2 /var/www/cloud/apps/snappymail/app/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/Messages.php(7                                               83): RainLoop\Model\Account->SmtpConnectAndLogin()
#3 /var/www/cloud/apps/snappymail/app/snappymail/v/2.28.4/app/libraries/RainLoop/Actions/Messages.php(1                                               78): RainLoop\Actions->smtpSendMessage()
#4 /var/www/cloud/apps/snappymail/app/snappymail/v/2.28.4/app/libraries/RainLoop/ServiceActions.php(142                                               ): RainLoop\Actions->DoSendMessage()
#5 /var/www/cloud/apps/snappymail/app/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(132): Rain                                               Loop\ServiceActions->ServiceJson()
#6 /var/www/cloud/apps/snappymail/app/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(14): RainL                                               oop\Service::RunResult()
#7 /var/www/cloud/apps/snappymail/lib/Util/SnappyMailHelper.php(99): RainLoop\Service::Handle()
#8 /var/www/cloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMai                                               lHelper::startApp()
#9 /var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\SnappyMail\Controller\PageCont                                               roller->indexPost()
#10 /var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher->                                               executeController()
#11 /var/www/cloud/lib/private/AppFramework/App.php(183): OC\AppFramework\Http\Dispatcher->dispatch()
#12 /var/www/cloud/lib/private/Route/Router.php(315): OC\AppFramework\App::main()
#13 /var/www/cloud/lib/base.php(1071): OC\Route\Router->match()
#14 /var/www/cloud/index.php(36): OC::handleRequest()
#15 {main}
```

**Additional context**
- The domain I'm accessing is handled by a server living on the same IP as I'm having my nextcloud instance on, but it is not the same machine, i.e. same IP but 2 different machines. Is it the reason why it's trying to connect to `localhost` and it doesn't work?
- I didn't see anywhere a possibility to specify outgoing server settings (address, port, security protocol): have I missed anything?

**Comment by the-djmaze** [comment]
Did you setup domains in the admin panel?
Read https://github.com/the-djmaze/snappymail/wiki/Admin-Manual#menu-domains for instructions

**Comment by tmlmt** [comment]
Now it all makes sense! I went to fast and was lured by the fact that I read in that setting page `List of domains webmail is allowed to access.` and then a "*" (all domains). So I hadn't seen that it was the place where you had to configure all domains. Issue's not an issue. Closing with thanks, @the-djmaze
