### ISSUE TITLE
SCRAM sign-in failed, even though credentials works in Thunderbird

### ISSUE THREAD

**Issue by arladmin** [the-djmaze/snappymail#1245]
**Describe the bug**
My domain is set up and tested with an email address, and enabled.

But, when i try to use the same user email credentials to sign into the inbox, i get the error:
"Authentication failed"

Same for all other domains from the concerned domain.

```
{
    "Action": "Login",
    "Result": false,
    "ErrorCode": 102,
    "ErrorMessage": "",
    "ErrorMessageAdditional": "",
    "epoch": 1695015959
}
```

Note: the same credentials work just fine in Thunderbird

**Please complete the following information:**
- Browser: [e.g. chromium 100, firefox 100, safari 14, mobile] Chrome 116.x
- IMAP daemon: [e.g. courier, dovecot] ?
- PHP version: 
- SnappyMail Version: 2.28.4
- Mode: [e.g. standalone, nextcloud, cyberpanel, docker] Cloudron

Log:
```
[18/Sep/2023:05:45:54 +0000] "POST /?/Json/&q[]=/0/ HTTP/1.1" 200 114 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
```

**Additional context**

**Comment by the-djmaze** [comment]
Please check ?admin -> domains if your domain is in there

**Comment by myuseraccount** [comment]
I also have this problem.  I added my domain, and the test works for IMAP and SMTP.  Trying to switch from Rainloop which works fine.  I've tried both STARTTLS and SSL/TLS, and different hostnames that have valid certificates.

Browser: Firefox 119.0 Windows 64-bit mainstream
IMAP server: Cyrus 
PHP: 8.1.20, php_fpm through Nginx Fast-CGI
Snappymail version: 2.29.1
Mode: standalone, FreeBSD 13.2

Log doesn't suggest that it's attempting authentication when I try to log in as a user.
`Nov 16 11:45:28 bastille imap[65626]: inittls: Loading hard-coded DH parameters
Nov 16 11:45:28 bastille imap[65626]: starttls: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits new) no authentication
$`

**Comment by the-djmaze** [comment]
@myuseraccount please check https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging

**Comment by myuseraccount** [comment]
Thanks @the-djmaze I just figured that out.

Even with that, the logs are sparse:
```
[2023-11-16 23:45:03.216][0594ba48] JSON[INFO]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","epoch":1700178303}
[2023-11-16 23:45:03.216][0594ba48] [INFO]: Memory peak usage: 2MB
[2023-11-16 23:45:03.216][0594ba48] [INFO]: Time delta: 5.0915658473969
[2023-11-16 23:45:03.217][0594ba48] IMAP[INFO]: Disconnected from "tcp://bastille.EXAMPLE.NET:143" (success)
``` 
Of course, EXAMPLE.NET is an edit replacing my real domain.  The same happens when I try another domain configured on the server (full email address entered as user, and both work when using the test feature in domain setup).
```
[2023-11-16 23:47:58.816][8c37f095] JSON[INFO]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","epoch":1700178478}
[2023-11-16 23:47:58.816][8c37f095] [INFO]: Memory peak usage: 4MB
[2023-11-16 23:47:58.816][8c37f095] [INFO]: Time delta: 5.0128240585327
[2023-11-16 23:47:58.816][8c37f095] IMAP[INFO]: Disconnected from "tcp://localhost:143" (success)
```
I expanded logging of my IMAP server (Cyrus) which doesn't help much either.
```
Nov 16 18:47:41 bastille imaps[66995]: starttls: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits new) no authentication
Nov 16 18:47:41 bastille imaps[66995]: SASL transitioning user hutch to auxprop database
Nov 16 18:47:41 bastille imaps[66995]: SASL setpass succeeded for hutch
Nov 16 18:47:41 bastille imaps[66995]: SASL SCRAM-SHA-512: set secret for hutch
Nov 16 18:47:41 bastille imaps[66995]: SASL SCRAM-SHA-384: set secret for hutch
Nov 16 18:47:41 bastille imaps[66995]: SASL SCRAM-SHA-256: set secret for hutch
Nov 16 18:47:41 bastille imaps[66995]: SASL SCRAM-SHA-224: set secret for hutch
Nov 16 18:47:41 bastille imaps[66995]: SASL SCRAM-SHA-1: set secret for hutch
Nov 16 18:47:41 bastille imaps[66995]: login: bastille.EXAMPLE.NET [192.168.0.101] hutch PLAIN+TLS User logged in SESSIONID=<bastille.EXAMPLE.NET-1700178461-66995-1-3540599559318986878>
Nov 16 18:47:41 bastille imaps[66995]: USAGE hutch user: 0.000000 sys: 0.006952
$
```

**Comment by myuseraccount** [comment]
I suspect it's having an issue in Snappymail, and not attempting an IMAP/SASL login.

With logging enabled on Snappymail, I get this long logfile.  Leaving it unedited this time.  The previous logs I posted were from Syslog, not snappymail/data/_data_/_default_/logs.  Below is from the Snappymail logs directly.

```
[2023-11-30 15:48:44.717][0dae7681] [INFO]: [SM:2.29.2][IP:131.252.164.183][PID:53025][nginx/1.24.0][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET https://mail.thehutch.net/]
[2023-11-30 15:48:44.734][0dae7681] [INFO]: Memory peak usage: 6MB
[2023-11-30 15:48:44.734][0dae7681] [INFO]: Time delta: 0.026949167251587
[2023-11-30 15:48:45.464][55aba554] [INFO]: [SM:2.29.2][IP:131.252.164.183][PID:53025][nginx/1.24.0][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET https://mail.thehutch.net/?/AppData/0/9822639015738192/]
[2023-11-30 15:48:45.466][55aba554] APPDATA[INFO]: {"Auth":false,"title":"TheHutch Webmail","loadingDescription":"SnappyMail","Plugins":[],"System":{"version":"2.29.2","token":"54978181704522f69a4d7b2bc7b347c71c0e7eb2","languages":["ar-SA","bg-BG","cs-CZ","da-DK","de-DE","el-GR","en","en-GB","eo","es-ES","et-EE","eu","fa-IR","fi-FI","fr-FR","hu-HU","id-ID","is-IS","it-IT","ja-JP","ko-KR","lt-LT","lv-LV","nb-NO","nl-NL","pl-PL","pt","pt-BR","pt-PT","ro-RO","ru-RU","sk-SK","sl-SI","sv-SE","tr-TR","uk-UA","vi-VN","zh-CN","zh-TW"],"webPath":"\/","webVersionPath":"\/snappymail\/v\/2.29.2\/"},"allowLanguagesOnLogin":true,"DevEmail":"","DevPassword":"","signMe":"DefaultOff","Theme":"BlurredDark","language":"en","userLanguage":"en","PluginsLink":"","StaticLibsJs":"\/snappymail\/v\/2.29.2\/static\/js\/min\/libs.min.js"}
[2023-11-30 15:48:45.466][55aba554] [INFO]: Memory peak usage: 4MB
[2023-11-30 15:48:45.466][55aba554] [INFO]: Time delta: 0.0039827823638916
[2023-11-30 15:53:26.360][afe56657] [INFO]: [SM:2.29.2][IP:131.252.164.183][PID:53025][nginx/1.24.0][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://mail.thehutch.net/?/Json/&q[]=/0/]
[2023-11-30 15:53:26.361][afe56657] JSON[INFO]: Action: DoLogin
[2023-11-30 15:53:26.361][afe56657] POST[INFO]: {"Email":"hutch","Password":"*******","language":"","signMe":"0","Action":"Login"}
[2023-11-30 15:53:26.361][afe56657] LOGIN[INFO]: The email address "hutch" is not complete
[2023-11-30 15:53:26.361][afe56657] LOGIN[INFO]: Default domain "thehutch.net" was used. (hutch > hutch@thehutch.net)
[2023-11-30 15:53:26.377][afe56657] IMAP[INFO]: Start connection to "tcp://bastille.thehutch.net:143"
[2023-11-30 15:53:26.676][afe56657] IMAP[INFO]: Connect (success)
[2023-11-30 15:53:26.693][afe56657] IMAP[INFO]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE STARTTLS LOGINDISABLED AUTH=SCRAM-SHA-512 AUTH=SCRAM-SHA-384 AUTH=SCRAM-SHA-256 AUTH=SCRAM-SHA-224 AUTH=SCRAM-SHA-1 AUTH=DIGEST-MD5 AUTH=OTP AUTH=NTLM AUTH=CRAM-MD5 SASL-IR] bastille.thehutch.net Cyrus IMAP 3.2.11 server ready\r\n
[2023-11-30 15:53:26.694][afe56657] IMAP[INFO]: > TAG1 STARTTLS\r\n
[2023-11-30 15:53:26.711][afe56657] IMAP[INFO]: < TAG1 OK Begin TLS negotiation now\r\n
[2023-11-30 15:53:26.755][afe56657] IMAP[INFO]: > TAG2 CAPABILITY\r\n
[2023-11-30 15:53:26.793][afe56657] IMAP[INFO]: < * CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ACL RIGHTS=kxten QUOTA MAILBOX-REFERRALS NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SEARCH=FUZZY SORT SORT=MODSEQ SORT=DISPLAY SORT=UID THREAD=ORDEREDSUBJECT THREAD=REFERENCES THREAD=REFS ANNOTATE-EXPERIMENT-1 METADATA LIST-EXTENDED LIST-STATUS LIST-MYRIGHTS LIST-METADATA WITHIN QRESYNC SCAN XLIST XMOVE MOVE SPECIAL-USE CREATE-SPECIAL-USE DIGEST=SHA1 X-REPLICATION STATUS=SIZE OBJECTID SAVEDATE X-CREATEDMODSEQ PREVIEW=FUZZY URLAUTH URLAUTH=BINARY AUTH=SCRAM-SHA-512-PLUS AUTH=SCRAM-SHA-512 AUTH=SCRAM-SHA-384-PLUS AUTH=SCRAM-SHA-384 AUTH=SCRAM-SHA-256-PLUS AUTH=SCRAM-SHA-256 AUTH=SCRAM-SHA-224-PLUS AUTH=SCRAM-SHA-224 AUTH=SCRAM-SHA-1-PLUS AUTH=SCRAM-SHA-1 AUTH=DIGEST-MD5 AUTH=OTP AUTH=NTLM AUTH=CRAM-MD5 AUTH=PLAIN AUTH=LOGIN SASL-IR COMPRESS=DEFLATE X-QUOTA=STORAGE X-QUOTA=MESSAGE X-QUOTA=X-ANNOTATION-STORAGE X-QUOTA=X-NUM-FOLDERS IDLE\r\n
[2023-11-30 15:53:26.794][afe56657] IMAP[INFO]: < TAG2 OK Completed\r\n
[2023-11-30 15:53:26.797][afe56657] IMAP[INFO]: > TAG3 AUTHENTICATE SCRAM-SHA-512\r\n
[2023-11-30 15:53:26.797][afe56657] IMAP[INFO]: < + \r\n
[2023-11-30 15:53:26.800][afe56657] IMAP[NOTICE]: MailSo\Imap\Exceptions\LoginException in /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/MailSo/Imap/ImapClient.php:483
Stack trace:
#0 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/MailSo/Imap/ImapClient.php(162): MailSo\Imap\ImapClient->getResponseValue(Object(MailSo\Imap\ResponseCollection), 3)
#1 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Model/Account.php(298): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#2 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Model/Account.php(238): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#3 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(425): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#4 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
#5 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/User.php(43): RainLoop\Actions->LoginProcess('hutch@thehutch....', '*******')
#6 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#7 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#8 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#9 /usr/local/www/snappymail/snappymail/v/2.29.2/include.php(143): RainLoop\Service::Handle()
#10 /usr/local/www/snappymail/index.php(11): include('/usr/local/www/...')
#11 {main}
[2023-11-30 15:53:26.800][afe56657] IMAP[NOTICE]: MailSo\Imap\Exceptions\LoginException in /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/MailSo/Imap/ImapClient.php:483
Stack trace:
#0 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/MailSo/Imap/ImapClient.php(162): MailSo\Imap\ImapClient->getResponseValue(Object(MailSo\Imap\ResponseCollection), 3)
#1 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Model/Account.php(298): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#2 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Model/Account.php(238): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#3 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(425): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#4 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
#5 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/User.php(43): RainLoop\Actions->LoginProcess('hutch@thehutch....', '*******')
#6 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#7 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#8 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#9 /usr/local/www/snappymail/snappymail/v/2.29.2/include.php(143): RainLoop\Service::Handle()
#10 /usr/local/www/snappymail/index.php(11): include('/usr/local/www/...')
#11 {main}

Next MailSo\Imap\Exceptions\LoginBadCredentialsException in /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/MailSo/Imap/ImapClient.php:244
Stack trace:
#0 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Model/Account.php(298): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#1 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Model/Account.php(238): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#2 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(425): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#3 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
#4 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/User.php(43): RainLoop\Actions->LoginProcess('hutch@thehutch....', '*******')
#5 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#6 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#7 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#8 /usr/local/www/snappymail/snappymail/v/2.29.2/include.php(143): RainLoop\Service::Handle()
#9 /usr/local/www/snappymail/index.php(11): include('/usr/local/www/...')
#10 {main}
[2023-11-30 15:53:31.398][afe56657] SERVICE[WARNING]: AuthError[102]
#0 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
#1 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/User.php(43): RainLoop\Actions->LoginProcess('hutch@thehutch....', '*******')
#2 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#3 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#4 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /usr/local/www/snappymail/snappymail/v/2.29.2/include.php(143): RainLoop\Service::Handle()
#6 /usr/local/www/snappymail/index.php(11): include('/usr/local/www/...')
#7 {main}
[2023-11-30 15:53:31.398][afe56657] SERVICE[WARNING]: -  @ /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/MailSo/Imap/ImapClient.php#244
[2023-11-30 15:53:31.398][afe56657] [ERROR]: MailSo\Imap\Exceptions\LoginException in /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/MailSo/Imap/ImapClient.php:483
Stack trace:
#0 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/MailSo/Imap/ImapClient.php(162): MailSo\Imap\ImapClient->getResponseValue(Object(MailSo\Imap\ResponseCollection), 3)
#1 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Model/Account.php(298): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#2 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Model/Account.php(238): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#3 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(425): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#4 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
#5 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/User.php(43): RainLoop\Actions->LoginProcess('hutch@thehutch....', '*******')
#6 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#7 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#8 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#9 /usr/local/www/snappymail/snappymail/v/2.29.2/include.php(143): RainLoop\Service::Handle()
#10 /usr/local/www/snappymail/index.php(11): include('/usr/local/www/...')
#11 {main}

Next MailSo\Imap\Exceptions\LoginBadCredentialsException in /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/MailSo/Imap/ImapClient.php:244
Stack trace:
#0 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Model/Account.php(298): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#1 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Model/Account.php(238): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#2 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(425): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#3 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
#4 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/User.php(43): RainLoop\Actions->LoginProcess('hutch@thehutch....', '*******')
#5 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#6 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#7 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#8 /usr/local/www/snappymail/snappymail/v/2.29.2/include.php(143): RainLoop\Service::Handle()
#9 /usr/local/www/snappymail/index.php(11): include('/usr/local/www/...')
#10 {main}

Next RainLoop\Exceptions\ClientException: AuthError[102] in /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php:436
Stack trace:
#0 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/UserAuth.php(140): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
#1 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Actions/User.php(43): RainLoop\Actions->LoginProcess('hutch@thehutch....', '*******')
#2 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#3 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#4 /usr/local/www/snappymail/snappymail/v/2.29.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /usr/local/www/snappymail/snappymail/v/2.29.2/include.php(143): RainLoop\Service::Handle()
#6 /usr/local/www/snappymail/index.php(11): include('/usr/local/www/...')
#7 {main}
[2023-11-30 15:53:31.398][afe56657] JSON[INFO]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","epoch":1701359611}
[2023-11-30 15:53:31.398][afe56657] [INFO]: Memory peak usage: 4MB
[2023-11-30 15:53:31.398][afe56657] [INFO]: Time delta: 5.0425119400024
[2023-11-30 15:53:31.399][afe56657] IMAP[INFO]: Disconnected from "tcp://bastille.thehutch.net:143" (success)
``` 
Let me know if the corresponding log from my working Rainloop setup would help.

**Comment by the-djmaze** [comment]
Now we are getting somewhere 👍

Login name is hutch@thehutch...
Then it tries login with SCRAM but seems to be empty and server wrong response is `+`.

I will look for the issue
