### ISSUE TITLE
Change Password Error with LDAP

### ISSUE THREAD

**Issue by lota** [the-djmaze/snappymail#1255]
User get a Change Password error when they tray to change own password.

With "Enable LDAP" and correct setting.

SnappyMail 2.28.4

** Log Error **
```

[2023-09-23 11:00:22.498][c3cb5cd6] SERVICE[WARNING]: Call to undefined method RainLoop\Model\MainAccount::Password()
#0 /srv/www/snappymail/public/snappymail/v/2.28.4/app/libraries/RainLoop/Plugins/Manager.php(372): ChangePasswordPlugin->ChangePassword()
#1 /srv/www/snappymail/public/snappymail/v/2.28.4/app/libraries/RainLoop/ServiceActions.php(145): RainLoop\Plugins\Manager->RunAdditionalJson()
#2 /srv/www/snappymail/public/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#3 /srv/www/snappymail/public/snappymail/v/2.28.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#4 /srv/www/snappymail/public/snappymail/v/2.28.4/include.php(143): RainLoop\Service::Handle()
#5 /srv/www/snappymail/public/index.php(11): include('/srv/www/snappy...')
#6 {main}
```

**Screenshots**
![ldap_config](https://github.com/the-djmaze/snappymail/assets/956392/ef49eab1-3092-4d2d-a186-363c1c3d541d)

![pw_error](https://github.com/the-djmaze/snappymail/assets/956392/b0a22832-f7e1-4cd0-b5dd-6850553fcdf6)

HTH && TIA
Alessandro

**Comment by the-djmaze** [comment]
Did you update the extensions through `?admin#/packages` ?
