### ISSUE TITLE
Can't send message using snappymail v2.29.1

### ISSUE THREAD

**Issue by mateors** [the-djmaze/snappymail#1271]
Today I just setup snappymail in my brand new server, but unfortunately its unable to send outgoing email. Incoming emails are working fine. Only issue when sending outgoing email. 

I can send email using the same credentials by programming but not with snappymail v2.29.1. Would you please look into this issue and help me out.

**Snappymail log says:**
```
[2023-10-05 15:27:46.254][1861fb76] SMTP[ERROR]: MailSo\Smtp\Exceptions\NegativeResponseException: Failed to add recipient "billahmdmostain@gmail.com": 501 5.1.8 Use Submission for outgoing SMTP (msg ID = aa4237d4) in /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/app/libraries/MailSo/Smtp/SmtpClient.php:535
Stack trace:
#0 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/app/libraries/MailSo/Smtp/SmtpClient.php(440): MailSo\Smtp\SmtpClient->validateResponse()
#1 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/app/libraries/MailSo/Smtp/SmtpClient.php(274): MailSo\Smtp\SmtpClient->sendRequestWithCheck()
#2 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/app/libraries/RainLoop/Actions/Messages.php(833): MailSo\Smtp\SmtpClient->Rcpt()
#3 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/app/libraries/RainLoop/Actions/Messages.php(178): RainLoop\Actions->smtpSendMessage()
#4 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoSendMessage()
#5 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#6 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#7 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/include.php(143): RainLoop\Service::Handle()
#8 /var/www/vhosts/webmail.shaperk.com/public_html/index.php(11): include('/var/www/vhosts...')
#9 {main}
[2023-10-05 15:27:46.255][1861fb76] SERVICE[WARNING]: CantSendMessage[302]
#0 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoSendMessage()
#1 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /var/www/vhosts/webmail.shaperk.com/public_html/snappymail/v/2.29.1/include.php(143): RainLoop\Service::Handle()
#4 /var/www/vhosts/webmail.shaperk.com/public_html/index.php(11): include('/var/www/vhosts...')
#5 {main}
```
The issue surely related with sending outgoing email, please suggest me how do I get rid of this problem?

**Comment by mateors** [comment]
I figured out the issue by myself and fixed. The issue was with domain configuration. I configured the * domain to fix it.
