### ISSUE TITLE
contacts not work

### ISSUE THREAD

**Issue by kbusta** [the-djmaze/snappymail#1319]
**Describe the bug**
Open contacts is empty, you can't import. but if I try to write an e-mail the contacts are present in self completion

**To Reproduce**
1. Go to 'contacts'

**Expected behavior**
view and edit contacts

**Screenshots**

**Please complete the following information:**
- Browser: firefox on win7 , debian e android
- IMAP daemon: courier
- PHP version: 8.2.12
- SnappyMail Version: 2.9.3
- Mode: [standalone]

**[Debug/logging information](apache2 error.log)
[Tue Nov 21 22:58:05.006194 2023] [proxy_fcgi:error] [pid 16389:tid 2858060608] [remote x.x.x.x:13418] AH01071: Got error 'PHP message: PHP Fatal error:  Declaration of Sabre\\VObject\\Property\\XCrypto::getValueType() must be compatible with Sabre\\VObject\\Property::getValueType(): string in /x/x/x/snappymail/v/2.29.3/app/libraries/Sabre/VObject/Property/XCrypto.php on line 31'

**Comment by the-djmaze** [comment]
Ah yes, i forgot to test that part when i updated the Sabre code

**Comment by lenny87** [comment]
Hi, this bug still exist even in 2.38.2

```
[2025-07-07 09:56:35.063][de947244] PdoAddressBook[WARNING]: Sync() invalid DavClient
[2025-07-07 09:56:35.063][de947244] SERVICE[WARNING]: ContactsSyncError[140] (AddressBookProvider->Sync() failed)
/var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/Contacts.php#75
#0 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoContactsSync()
#1 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /var/www/localhtml/snappymail/v/2.38.2/include.php(137): RainLoop\Service::Handle()
#4 /var/www/localhtml/index.php(11): include('...')
#5 {main}
[2025-07-07 09:56:44.952][94f7e03d] Crypt[ERROR]: sodiumDecrypt(): invalid $data or $key
#0 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/snappymail/crypt.php(96): SnappyMail\Crypt::Decrypt()
#1 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/Model/MainAccount.php(55): SnappyMail\Crypt::DecryptFromJSON()
#2 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/Contacts.php(233): RainLoop\Model\MainAccount->CryptKey()
#3 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/Contacts.php(25): RainLoop\Actions->getContactsSyncData()
#4 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/Providers/Suggestions.php(36): RainLoop\Actions->AddressBookProvider()
#5 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/User.php(244): RainLoop\Providers\Suggestions->Process()
#6 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoSuggestions()
#7 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#8 /var/www/localhtml/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#9 /var/www/localhtml/snappymail/v/2.38.2/include.php(137): RainLoop\Service::Handle()
#10 /var/www/localhtml/index.php(11): include('...')
#11 {main}
```
