### ISSUE TITLE
Suddenly, authentication error for all my gmail acccounts

### ISSUE THREAD

**Issue by europacafe** [the-djmaze/snappymail#1355]
**Describe the bug**
All my gmail accounts used to be working fine, but now they produce authentication failed

**To Reproduce**
just switch to my gmail account from the upper right selection list
even deleting the account and re-add it also has authentication failed
I have 4 gmail accounts and they are now producing authentication failed
I can re-verify gmail.com domain using one of the gmail account without problem
No problem with yahoo, outlook, and my self-hosting mail accounts.

**Please complete the following information:**
- Browser: Microsoft Edge
- SnappyMail Version: 2.30.0
![image](https://github.com/the-djmaze/snappymail/assets/51871976/f39dc830-8c45-4ea2-9d1a-3a4b921429c1)

This is the log messages after entering the password
```
(
    [crypto] => Array
        (
            [protocol] => TLSv1.3
            [cipher_name] => TLS_AES_256_GCM_SHA384
            [cipher_bits] => 256
            [cipher_version] => TLSv1.3
        )
    [timed_out] => 
    [blocked] => 1
    [eof] => 1
    [stream_type] => tcp_socket/ssl
    [mode] => r+
    [unread_bytes] => 0
    [seekable] => 
)
[2023-12-08 03:25:13.674][3940856a] IMAP[ERROR]: MailSo\Net\Exceptions\SocketReadException in /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Net/NetClient.php:275
Stack trace:
#0 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/Traits/ResponseParser.php(93): MailSo\Net\NetClient->getNextBuffer()
#1 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/Traits/ResponseParser.php(33): MailSo\Imap\ImapClient->partialParseResponseBranch(Object(MailSo\Imap\Response), false, '', '', true)
#2 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/ImapClient.php(521): MailSo\Imap\ImapClient->partialParseResponse()
#3 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/ImapClient.php(465): MailSo\Imap\ImapClient->getResponse()
#4 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/ImapClient.php(225): MailSo\Imap\ImapClient->SendRequestGetResponse('LOGIN', Array)
#5 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Model/Account.php(304): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#6 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Model/Account.php(244): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#7 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/UserAuth.php(426): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#8 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/UserAuth.php(147): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#9 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/Accounts.php(96): RainLoop\Actions->LoginProcess('xxxxxx@gmail.c...', 'exxxxxxxxk...', false)
#10 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoAccountSetup()
#11 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#12 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#13 /snappymail/snappymail/v/2.30.0/include.php(127): RainLoop\Service::Handle()
#14 /snappymail/index.php(11): include('/snappymail/sna...')
#15 {main}
[2023-12-08 03:25:13.675][3940856a] SERVICE[WARNING]: AuthError[102]
#0 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/UserAuth.php(147): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#1 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/Accounts.php(96): RainLoop\Actions->LoginProcess('xxxxxx@gmail.c...', 'exxxxxxxxk...', false)
#2 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoAccountSetup()
#3 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#4 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /snappymail/snappymail/v/2.30.0/include.php(127): RainLoop\Service::Handle()
#6 /snappymail/index.php(11): include('/snappymail/sna...')
#7 {main}



```

**Comment by IgorA100** [comment]
As a temporary solution, apply the patch: https://github.com/the-djmaze/snappymail/commit/58666c0df56a1a303e0616f4b0c54c54b83331f7

**Comment by the-djmaze** [comment]
`SocketReadException` happens when SnappyMail does not get a response from the server.

To know why, we need the debug log info from the 'LOGIN' command

**Comment by europacafe** [comment]
> `SocketReadException` happens when SnappyMail does not get a response from the server.
> 
> To know why, we need the debug log info from the 'LOGIN' command

here is the log entries after entering a password and press update
```
[2023-12-08 23:22:04.511][bcd732c2] [INFO]: [SM:2.30.0][IP:][PID:2435][nginx/1.24.0][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://smail.bthofen.com/?/Json/&q[]=/0/]
[2023-12-08 23:22:04.535][bcd732c2] JSON[INFO]: Action: DoAccountSetup
[2023-12-08 23:22:04.535][bcd732c2] POST[INFO]: {"email":"xxxxxx@gmail.com","password":"*******","name":"gmail - xxxxxx","new":"0","Action":"AccountSetup"}
[2023-12-08 23:22:04.542][bcd732c2] IMAP[INFO]: Start connection to "ssl://imap.gmail.com:993"
[2023-12-08 23:22:04.670][bcd732c2] IMAP[INFO]: Connect (success)
[2023-12-08 23:22:04.670][bcd732c2] IMAP[DEBUG]: 0.12832903862 (raw connection)
[2023-12-08 23:22:04.866][bcd732c2] IMAP[INFO]: < * OK Gimap ready for requests from 110.168.24.249 n6mb62387647pjd\r\n
[2023-12-08 23:22:04.866][bcd732c2] IMAP[DEBUG]: 0.32457995414734 (*)
[2023-12-08 23:22:04.867][bcd732c2] IMAP[INFO]: > TAG1 CAPABILITY\r\n
[2023-12-08 23:22:05.062][bcd732c2] IMAP[INFO]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER\r\n
[2023-12-08 23:22:05.062][bcd732c2] IMAP[INFO]: < TAG1 OK Thats all she wrote! n6mb62387647pjd\r\n
[2023-12-08 23:22:05.062][bcd732c2] IMAP[DEBUG]: 0.19520211219788 (TAG1)
[2023-12-08 23:22:05.062][bcd732c2] IMAP[INFO]: > TAG2 CAPABILITY\r\n
[2023-12-08 23:22:05.257][bcd732c2] IMAP[INFO]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER\r\n
[2023-12-08 23:22:05.257][bcd732c2] IMAP[INFO]: < TAG2 OK Thats all she wrote! n6mb62387647pjd\r\n
[2023-12-08 23:22:05.257][bcd732c2] IMAP[DEBUG]: 0.19499897956848 (TAG2)
[2023-12-08 23:22:05.257][bcd732c2] IMAP[INFO]: > TAG3 CAPABILITY\r\n
[2023-12-08 23:22:05.452][bcd732c2] IMAP[INFO]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER\r\n
[2023-12-08 23:22:05.452][bcd732c2] IMAP[INFO]: < TAG3 OK Thats all she wrote! n6mb62387647pjd\r\n
[2023-12-08 23:22:05.452][bcd732c2] IMAP[DEBUG]: 0.19546580314636 (TAG3)
[2023-12-08 23:22:05.453][bcd732c2] IMAP[INFO]: > TAG4 CAPABILITY\r\n
[2023-12-08 23:22:05.648][bcd732c2] IMAP[INFO]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER\r\n
[2023-12-08 23:22:05.648][bcd732c2] IMAP[INFO]: < TAG4 OK Thats all she wrote! n6mb62387647pjd\r\n
[2023-12-08 23:22:05.648][bcd732c2] IMAP[DEBUG]: 0.19547605514526 (TAG4)
[2023-12-08 23:22:05.648][bcd732c2] IMAP[INFO]: > TAG5 CAPABILITY\r\n
[2023-12-08 23:22:05.843][bcd732c2] IMAP[INFO]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER\r\n
[2023-12-08 23:22:05.843][bcd732c2] IMAP[INFO]: < TAG5 OK Thats all she wrote! n6mb62387647pjd\r\n
[2023-12-08 23:22:05.843][bcd732c2] IMAP[DEBUG]: 0.19534802436829 (TAG5)
[2023-12-08 23:22:05.844][bcd732c2] IMAP[INFO]: > TAG6 CAPABILITY\r\n
[2023-12-08 23:22:06.039][bcd732c2] IMAP[INFO]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER\r\n
[2023-12-08 23:22:06.039][bcd732c2] IMAP[INFO]: < TAG6 OK Thats all she wrote! n6mb62387647pjd\r\n
[2023-12-08 23:22:06.039][bcd732c2] IMAP[DEBUG]: 0.1951699256897 (TAG6)
[2023-12-08 23:22:06.039][bcd732c2] IMAP[INFO]: > TAG7 CAPABILITY\r\n
[2023-12-08 23:22:06.233][bcd732c2] IMAP[INFO]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER\r\n
[2023-12-08 23:22:06.234][bcd732c2] IMAP[INFO]: < TAG7 OK Thats all she wrote! n6mb62387647pjd\r\n
[2023-12-08 23:22:06.234][bcd732c2] IMAP[DEBUG]: 0.1948869228363 (TAG7)
[2023-12-08 23:22:06.234][bcd732c2] IMAP[INFO]: > TAG8 CAPABILITY\r\n
[2023-12-08 23:22:06.429][bcd732c2] IMAP[INFO]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER\r\n
[2023-12-08 23:22:06.429][bcd732c2] IMAP[INFO]: < TAG8 OK Thats all she wrote! n6mb62387647pjd\r\n
[2023-12-08 23:22:06.429][bcd732c2] IMAP[DEBUG]: 0.19517111778259 (TAG8)
[2023-12-08 23:22:06.429][bcd732c2] IMAP[INFO]: > TAG9 CAPABILITY\r\n
[2023-12-08 23:22:06.624][bcd732c2] IMAP[INFO]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER\r\n
[2023-12-08 23:22:06.624][bcd732c2] IMAP[INFO]: < TAG9 OK Thats all she wrote! n6mb62387647pjd\r\n
[2023-12-08 23:22:06.625][bcd732c2] IMAP[DEBUG]: 0.1954197883606 (TAG9)
[2023-12-08 23:22:06.625][bcd732c2] IMAP[INFO]: > TAG10 CAPABILITY\r\n
[2023-12-08 23:22:06.820][bcd732c2] IMAP[INFO]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER\r\n
[2023-12-08 23:22:06.820][bcd732c2] IMAP[INFO]: < TAG10 OK Thats all she wrote! n6mb62387647pjd\r\n
[2023-12-08 23:22:06.820][bcd732c2] IMAP[DEBUG]: 0.19523310661316 (TAG10)
[2023-12-08 23:22:06.820][bcd732c2] IMAP[INFO]: > TAG11 LOGIN "xxxxxx@gmail.com" "*******"\r\n
[2023-12-08 23:22:07.015][bcd732c2] IMAP[INFO]: < * BYE Too many commands before auth n6mb62387647pjd\r\n
[2023-12-08 23:22:07.016][bcd732c2] IMAP[ERROR]: Stream Meta: Array
(
    [crypto] => Array
        (
            [protocol] => TLSv1.3
            [cipher_name] => TLS_AES_256_GCM_SHA384
            [cipher_bits] => 256
            [cipher_version] => TLSv1.3
        )
    [timed_out] => 
    [blocked] => 1
    [eof] => 1
    [stream_type] => tcp_socket/ssl
    [mode] => r+
    [unread_bytes] => 0
    [seekable] => 
)
[2023-12-08 23:22:07.016][bcd732c2] IMAP[ERROR]: MailSo\Net\Exceptions\SocketReadException in /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Net/NetClient.php:275
Stack trace:
#0 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/Traits/ResponseParser.php(93): MailSo\Net\NetClient->getNextBuffer()
#1 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/Traits/ResponseParser.php(33): MailSo\Imap\ImapClient->partialParseResponseBranch(Object(MailSo\Imap\Response), false, '', '', true)
#2 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/ImapClient.php(521): MailSo\Imap\ImapClient->partialParseResponse()
#3 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/ImapClient.php(465): MailSo\Imap\ImapClient->getResponse()
#4 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/ImapClient.php(225): MailSo\Imap\ImapClient->SendRequestGetResponse('LOGIN', Array)
#5 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Model/Account.php(304): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#6 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Model/Account.php(244): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#7 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/UserAuth.php(426): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#8 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/UserAuth.php(147): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#9 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/Accounts.php(96): RainLoop\Actions->LoginProcess('xxxxxx@gmai...', 'uvbgczlweccceug...', false)
#10 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoAccountSetup()
#11 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#12 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#13 /snappymail/snappymail/v/2.30.0/include.php(127): RainLoop\Service::Handle()
#14 /snappymail/index.php(11): include('/snappymail/sna...')
#15 {main}
[2023-12-08 23:22:07.017][bcd732c2] SERVICE[WARNING]: AuthError[102]
#0 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/UserAuth.php(147): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#1 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/Accounts.php(96): RainLoop\Actions->LoginProcess('xxxxxx@gmai...', 'uvbgczlweccceug...', false)
#2 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoAccountSetup()
#3 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#4 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /snappymail/snappymail/v/2.30.0/include.php(127): RainLoop\Service::Handle()
#6 /snappymail/index.php(11): include('/snappymail/sna...')
#7 {main}
[2023-12-08 23:22:07.017][bcd732c2] SERVICE[WARNING]: -  @ /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Net/NetClient.php#275
[2023-12-08 23:22:07.017][bcd732c2] [ERROR]: MailSo\Net\Exceptions\SocketReadException in /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Net/NetClient.php:275
Stack trace:
#0 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/Traits/ResponseParser.php(93): MailSo\Net\NetClient->getNextBuffer()
#1 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/Traits/ResponseParser.php(33): MailSo\Imap\ImapClient->partialParseResponseBranch(Object(MailSo\Imap\Response), false, '', '', true)
#2 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/ImapClient.php(521): MailSo\Imap\ImapClient->partialParseResponse()
#3 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/ImapClient.php(465): MailSo\Imap\ImapClient->getResponse()
#4 /snappymail/snappymail/v/2.30.0/app/libraries/MailSo/Imap/ImapClient.php(225): MailSo\Imap\ImapClient->SendRequestGetResponse('LOGIN', Array)
#5 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Model/Account.php(304): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
#6 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Model/Account.php(244): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
#7 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/UserAuth.php(426): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
#8 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/UserAuth.php(147): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#9 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/Accounts.php(96): RainLoop\Actions->LoginProcess('xxxxxx@gmai...', 'uvbgczlweccceug...', false)
#10 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoAccountSetup()
#11 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#12 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#13 /snappymail/snappymail/v/2.30.0/include.php(127): RainLoop\Service::Handle()
#14 /snappymail/index.php(11): include('/snappymail/sna...')
#15 {main}
Next RainLoop\Exceptions\ClientException: AuthError[102] in /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/UserAuth.php:442
Stack trace:
#0 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/UserAuth.php(147): RainLoop\Actions->imapConnect(Object(RainLoop\Model\AdditionalAccount), true)
#1 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Actions/Accounts.php(96): RainLoop\Actions->LoginProcess('xxxxxx@gmai...', 'uvbgczlweccceug...', false)
#2 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoAccountSetup()
#3 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#4 /snappymail/snappymail/v/2.30.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /snappymail/snappymail/v/2.30.0/include.php(127): RainLoop\Service::Handle()
#6 /snappymail/index.php(11): include('/snappymail/sna...')
#7 {main}
[2023-12-08 23:22:07.017][bcd732c2] JSON[INFO]: {"Action":"AccountSetup","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","epoch":1702077727}
[2023-12-08 23:22:07.017][bcd732c2] [INFO]: Last error: {"type":2,"message":"stream_socket_client(): Unable to connect to tcp:\/\/127.0.0.1:6379 (Connection refused)","file":"\/snappymail\/snappymail\/v\/2.30.0\/app\/libraries\/Predis\/Connection\/StreamConnection.php","line":94}
[2023-12-08 23:22:07.017][bcd732c2] [INFO]: Memory peak usage: 2MB
[2023-12-08 23:22:07.017][bcd732c2] [INFO]: Time delta: 2.5214078426361
[2023-12-08 23:22:07.022][bcd732c2] IMAP[INFO]: Disconnected from "ssl://imap.gmail.com:993" (success)
[2023-12-08 23:22:07.022][bcd732c2] IMAP[DEBUG]: 2.4800679683685 (net session)
```

**Comment by europacafe** [comment]
> As a temporary solution, apply the patch: [58666c0](https://github.com/the-djmaze/snappymail/commit/58666c0df56a1a303e0616f4b0c54c54b83331f7)

Thanks, but this doesn't help.

**Comment by the-djmaze** [comment]
Did you disable all capabilities in Admin -> Domains -> gmail?

If so, delete it and add again but don't disable them all.

**Comment by europacafe** [comment]
Thanks. Deleting and re-adding gmail.com did solve the problem with all the existing gmail accounts.

I understand that the problem was due to the old gmail.com domain still having a standard list of "Disable Capabilities" from which I had disabled only one capability. Deleting and adding it again pulled down the longer list from gmail imap server and it works again.

**Comment by the-djmaze** [comment]
Great.

I've modified the code that hopefully prevents this issue in the future.
