### ISSUE TITLE
`operation not allowed` on `MessageMove` with the Proton bridge

### ISSUE THREAD

**Issue by BlackLight** [the-djmaze/snappymail#1365]
**Describe the bug**

Any message move/delete operations fail with `operation not allowed` when the mail server points to a ProtonMail bridge.

Request:

```json
{
  "Action": "MessageMove",
  "fromFolder": "All Mail",
  "learning": "",
  "markAsRead", 1,
  "toFolder", "Trash",
  "uids", "6299"
}
```

Response:

```json
{
  "Action": "MessageMove",
  "Result": false,
  "ErrorCode": 204,
  "ErrorMessage": "",
  "ErrorMessageAdditional": " operation not allowed"
}
```

**To Reproduce**

1. Create a new mail server by using the ProtonMail bridge - either on the same machine as the SnappyMail service, or e.g. tunnelled over SSH.
2. Configure SnappyMail to use the bridge as its mail server.
3. Try and move/delete some messages.

**Expected behavior**

Messages are successfully moved/deleted.

**Screenshots**

![Screenshot_2023-12-19_12-49-08](https://github.com/the-djmaze/snappymail/assets/42405/4904bdbc-182e-4b17-b19f-6d8ca40e73c4)

**Please complete the following information:**
- Browser: Firefox [latest canary], but the behaviour can be easily replicated on Chrome too.
- IMAP daemon: ProtonMail bridge
- PHP version: 8.2.13
- SnappyMail Version: 1.1.10
- Mode: standalone + NextCloud + Docker

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**

```
[2023-12-19 11:54:18.201][7af3b9a0] JSON[INFO]: Action: DoMessageMove
[2023-12-19 11:54:18.201][7af3b9a0] POST[INFO]: {"fromFolder":"All Mail","toFolder":"Trash","uids":"6299","markAsRead":1,"learning":"","Action":"MessageMove"}
[2023-12-19 11:54:18.201][7af3b9a0] IMAP[INFO]: Start connection to "tcp://10.0.0.1:1143"
[2023-12-19 11:54:18.224][7af3b9a0] IMAP[INFO]: Connect (success)
[2023-12-19 11:54:18.224][7af3b9a0] IMAP[DEBUG]: 0.023355007171631 (raw connection)
[2023-12-19 11:54:18.290][7af3b9a0] IMAP[INFO]: < * OK [CAPABILITY ID IDLE IMAP4rev1 MOVE STARTTLS UIDPLUS UNSELECT] Proton Mail Bridge 03.03.02 - gluon session ID 70657\r\n
[2023-12-19 11:54:18.290][7af3b9a0] IMAP[DEBUG]: 0.089079856872559 (*)
[2023-12-19 11:54:18.290][7af3b9a0] IMAP[INFO]: > TAG1 STARTTLS\r\n
[2023-12-19 11:54:18.316][7af3b9a0] IMAP[INFO]: < TAG1 OK Begin TLS negotiation now\r\n
[2023-12-19 11:54:18.316][7af3b9a0] IMAP[DEBUG]: 0.025879144668579 (TAG1)
[2023-12-19 11:54:18.347][7af3b9a0] IMAP[INFO]: > TAG2 CAPABILITY\r\n
[2023-12-19 11:54:18.431][7af3b9a0] IMAP[INFO]: < * CAPABILITY ID IDLE IMAP4rev1 STARTTLS\r\n
[2023-12-19 11:54:18.473][7af3b9a0] IMAP[INFO]: < TAG2 OK CAPABILITY\r\n
[2023-12-19 11:54:18.473][7af3b9a0] IMAP[DEBUG]: 0.12596416473389 (TAG2)
[2023-12-19 11:54:18.473][7af3b9a0] IMAP[INFO]: > TAG3 LOGIN "fabio@******.***" "*******"\r\n
[2023-12-19 11:54:18.572][7af3b9a0] IMAP[INFO]: < TAG3 OK [CAPABILITY ID IDLE IMAP4rev1 MOVE STARTTLS UIDPLUS UNSELECT] Logged in\r\n
[2023-12-19 11:54:18.572][7af3b9a0] IMAP[DEBUG]: 0.099246978759766 (TAG3)
[2023-12-19 11:54:18.573][7af3b9a0] IMAP[INFO]: > TAG4 SELECT "All Mail"\r\n
[2023-12-19 11:54:18.650][7af3b9a0] IMAP[INFO]: < * FLAGS (\Flagged \Seen)\r\n
[2023-12-19 11:54:18.686][7af3b9a0] IMAP[INFO]: < * 1661 EXISTS\r\n
[2023-12-19 11:54:18.686][7af3b9a0] IMAP[INFO]: < * 0 RECENT\r\n
[2023-12-19 11:54:18.686][7af3b9a0] IMAP[INFO]: < * OK [PERMANENTFLAGS (\Flagged \Seen)] Flags permitted\r\n
[2023-12-19 11:54:18.686][7af3b9a0] IMAP[INFO]: < * OK [UIDNEXT 6301] Predicted next UID\r\n
[2023-12-19 11:54:18.686][7af3b9a0] IMAP[INFO]: < * OK [UIDVALIDITY 1001] UIDs valid\r\n
[2023-12-19 11:54:18.686][7af3b9a0] IMAP[INFO]: < * OK [UNSEEN 1648] Unseen messages\r\n
[2023-12-19 11:54:18.686][7af3b9a0] IMAP[INFO]: < TAG4 OK [READ-WRITE] SELECT\r\n
[2023-12-19 11:54:18.686][7af3b9a0] IMAP[DEBUG]: 0.11335706710815 (TAG4)
[2023-12-19 11:54:18.687][7af3b9a0] IMAP[INFO]: > TAG5 UID STORE 6299 +FLAGS.SILENT (\Seen)\r\n
[2023-12-19 11:54:18.722][7af3b9a0] IMAP[INFO]: < TAG5 OK command completed in 5.60202ms\r\n
[2023-12-19 11:54:18.722][7af3b9a0] IMAP[DEBUG]: 0.035439968109131 (TAG5)
[2023-12-19 11:54:18.722][7af3b9a0] IMAP[INFO]: > TAG6 UID MOVE 6299 "Trash"\r\n
[2023-12-19 11:54:18.747][7af3b9a0] IMAP[INFO]: < TAG6 NO operation not allowed\r\n
[2023-12-19 11:54:18.747][7af3b9a0] IMAP[DEBUG]: 0.025211095809937 (TAG6)
[2023-12-19 11:54:18.747][7af3b9a0] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException:  operation not allowed in /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/MailSo/Imap/ImapClient.php(545): MailSo\Imap\ResponseCollection->validate()
#1 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/MailSo/Imap/ImapClient.php(468): MailSo\Imap\ImapClient->getResponse()
#2 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/MailSo/Imap/Commands/Messages.php(238): MailSo\Imap\ImapClient->SendRequestGetResponse()
#3 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/Actions/Messages.php(518): MailSo\Imap\ImapClient->MessageMove()
#4 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoMessageMove()
#5 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#6 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#7 /usr/share/snappymail/snappymail/v/2.29.1/include.php(143): RainLoop\Service::Handle()
#8 /usr/share/snappymail/index.php(11): include('...')
#9 {main}
[2023-12-19 11:54:18.748][7af3b9a0] SERVICE[WARNING]: CantMoveMessage[204]
#0 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoMessageMove()
#1 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /usr/share/snappymail/snappymail/v/2.29.1/include.php(143): RainLoop\Service::Handle()
#4 /usr/share/snappymail/index.php(11): include('...')
#5 {main}
[2023-12-19 11:54:18.748][7af3b9a0] SERVICE[WARNING]: -  operation not allowed @ /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/MailSo/Imap/ResponseCollection.php#46
[2023-12-19 11:54:18.748][7af3b9a0] [ERROR]: MailSo\Imap\Exceptions\NegativeResponseException:  operation not allowed in /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/MailSo/Imap/ImapClient.php(545): MailSo\Imap\ResponseCollection->validate()
#1 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/MailSo/Imap/ImapClient.php(468): MailSo\Imap\ImapClient->getResponse()
#2 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/MailSo/Imap/Commands/Messages.php(238): MailSo\Imap\ImapClient->SendRequestGetResponse()
#3 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/Actions/Messages.php(518): MailSo\Imap\ImapClient->MessageMove()
#4 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoMessageMove()
#5 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#6 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#7 /usr/share/snappymail/snappymail/v/2.29.1/include.php(143): RainLoop\Service::Handle()
#8 /usr/share/snappymail/index.php(11): include('...')
#9 {main}

Next RainLoop\Exceptions\ClientException: CantMoveMessage[204] in /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/Actions/Messages.php:522
Stack trace:
#0 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoMessageMove()
#1 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 /usr/share/snappymail/snappymail/v/2.29.1/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /usr/share/snappymail/snappymail/v/2.29.1/include.php(143): RainLoop\Service::Handle()
#4 /usr/share/snappymail/index.php(11): include('...')
#5 {main}
[2023-12-19 11:54:18.748][7af3b9a0] JSON[INFO]: {"Action":"MessageMove","Result":false,"ErrorCode":204,"ErrorMessage":"","ErrorMessageAdditional":" operation not allowed","epoch":1702986858}
[2023-12-19 11:54:18.748][7af3b9a0] IMAP[INFO]: > TAG7 LOGOUT\r\n
[2023-12-19 11:54:18.770][7af3b9a0] IMAP[INFO]: < * BYE\r\n
[2023-12-19 11:54:18.813][7af3b9a0] IMAP[INFO]: < TAG7 OK LOGOUT\r\n
[2023-12-19 11:54:18.813][7af3b9a0] IMAP[DEBUG]: 0.064874172210693 (TAG7)
[2023-12-19 11:54:18.813][7af3b9a0] IMAP[INFO]: Disconnected from "tcp://10.0.0.1:1143" (success)
```

**Additional context**

Note that a similar problem occurred on RainLoop as well. However, in that case I'd get a "can't move message error", followed by the message actually being moved/removed. On SnappyMail, instead, the page spinner will keep loading and nothing happens.

It sounds to me like something definitely needs to be fixed on the Proton bridge side when it comes to implementing IMAP's message move paradigms, but in the meantime even resorting to the same logic used in RainLoop should mitigate the impact.

**Comment by BlackLight** [comment]
Good point there: _All Mail_ is indeed a virtual mbox in this case. I've just tried to move a message from my Inbox folder to the trash and it worked.

Still, how come RainLoop manages to handle this? I mean, it still displays an error, but it also doesn't get stuck in a spinner loop and the messages managed to eventually get moved.

And how does IMAP normally handle such cases? I also use K-9 on Android and aerc/mutt on the terminal pointing to the same server, but those clients seem to have found a way to move messages from virtual mailboxes without returning an error.

**Comment by the-djmaze** [comment]
Maybe they silently use copy/delete?

You might could use that by disable MOVE in admin - domains - domain - imap - disable capabilities (for that, first run test with login to see all server capabilities)

**Comment by BlackLight** [comment]
Thanks for the tip! I have managed to get it to work by disabling the `MOVE` command for the mail server indeed.

It's still not ideal (I'd love to have a way to completely silence the error message, like K-9 and aerc do), but at least it's functional now.
