### ISSUE TITLE
Avatars plugin: Call to undefined function mime_content_type()

### ISSUE THREAD

**Issue by yasuhirokimura** [the-djmaze/snappymail#1392]
After updating Avaters plugin to 1.12, 'Unknown error' is diplayed as following when listing messages in folder.

<img width="1535" alt="SnappyMail UnknowError AvatarsPlugin" src="https://github.com/the-djmaze/snappymail/assets/5249848/057d9a1e-b17f-4a44-aaa9-ac5c62472a4e">

And follwing messages are written to log file.

```
[2024-01-16 18:42:52.071][d5abac14] SERVICE[WARNING]: Call to undefined function mime_content_type()
#0 /net/data/snappymail/_data_/_default_/plugins/avatars/index.php(185): AvatarsPlugin::getCachedImage('no-reply@examp....')
#1 /net/data/snappymail/_data_/_default_/plugins/avatars/index.php(64): AvatarsPlugin::getServiceIcon('no-reply@examp....')
#2 /net/data/snappymail/_data_/_default_/plugins/avatars/index.php(48): AvatarsPlugin->JsonAvatar(Array)
#3 /usr/local/www/snappymail/snappymail/v/2.32.0/app/libraries/RainLoop/Plugins/Manager.php(314): AvatarsPlugin->JsonMessageList(Array)
#4 /usr/local/www/snappymail/snappymail/v/2.32.0/app/libraries/RainLoop/ServiceActions.php(151): RainLoop\Plugins\Manager->RunHook('json.after-mess...', Array)
#5 /usr/local/www/snappymail/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#6 /usr/local/www/snappymail/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#7 /usr/local/www/snappymail/snappymail/v/2.32.0/include.php(127): RainLoop\Service::Handle()
#8 /usr/local/www/snappymail/index.php(11): include('/usr/local/www/...')
#9 {main}
```

The problem disappears by disabling Avaters plugin.

I have following 2 instances of SnappyMail.

## Instance 1

* FreeBSD 13.2-RELEASE amd64
* Dovecot 2.3.21
* Apache HTTP server 2.4.58
* PHP 8.3.1
* SnappyMail 2.32.0

## Instance 2

* Debian 11.8 amd64
* Dovecot 2.3.13
* Apache HTTP server 2.4.56
* PHP 7.4.33
* SnappyMail 2.32.0

And the problem only happens with the former.

**Comment by the-djmaze** [comment]
Fileinfo is enabled by default.
Somehow it is disabled in your PHP instance.
https://www.php.net/manual/en/fileinfo.installation.php

Can you check that?

**Comment by yasuhirokimura** [comment]
@the-djmaze  In FreeBSD Ports Collection fileinfo is provided as separate port.
I installed it and now the problem is fixed.
Thanks!
