### ISSUE TITLE
message was sent but not saved to sent items folder 

### ISSUE THREAD

**Issue by mateors** [the-djmaze/snappymail#1397]
**Describe the bug**
When i send email it says : **message was sent but not saved to sent items folder** 

**Screenshots**
![Screenshot 2024-01-18 210141](https://github.com/the-djmaze/snappymail/assets/17635146/8073708c-dc76-445f-8838-bd71fcfda31c)

**Please complete the following information:**
- Browser: Microsfot Edge Version 120.0.2210.133 (Official build) (64-bit)
- IMAP daemon: Maddy
- PHP version: 7.4
- SnappyMail Version: 2.32.0
- Mode: standalone

**Logs**

```
Next RainLoop\Exceptions\ClientException: CantSaveMessage[301] in /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/Messages.php:240
Stack trace:
#0 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.32.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoSendMessage()
#1 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.32.0/include.php(127): RainLoop\Service::Handle()
#4 /opt/mateors/lxroot/webmail.shaperk.com/public_html/index.php(11): include('/opt/mateors/lx...')
#5 {main}
```

**Comment by mateors** [comment]
@the-djmaze is it already applied to v2.32.0? can I get this updated code while reinstalling using https://github.com/the-djmaze/snappymail/releases/tag/v2.32.0 ??

**Comment by the-djmaze** [comment]
No, will be in next release

**Comment by mateors** [comment]
@the-djmaze so how can i solve this issue now? I am already using snappymail. I appreciate your support.

**Comment by the-djmaze** [comment]
Maybe this helps https://github.com/the-djmaze/snappymail/releases/tag/v2.33.0

**Comment by mateors** [comment]
@the-djmaze Thank you very much for your quick response, but unfortunately my problem still persist.

I just re-install v2.33.0 and tried to send email. And got the same error like before.

![Screenshot 2024-01-23 155617](https://github.com/the-djmaze/snappymail/assets/17635146/bd3e82f7-f856-46c7-bcfb-194ee695de55)

![Screenshot 2024-01-23 155853](https://github.com/the-djmaze/snappymail/assets/17635146/65d0b4fb-c82e-47b3-9eda-a6cdcf54f330)


**PLEASE CHECK THE DETAILED LOG BELOW:**
```
[2024-01-23 10:01:03.995][36c40858] [INFO]: [SM:2.33.0][IP:103.124.226.97][PID:709154][nginx/1.18.0][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://webmail.shaperk.com/?/Json/&q[]=/0/]
[2024-01-23 10:01:03.997][36c40858] JSON[INFO]: Action: DoSendMessage
[2024-01-23 10:01:03.997][36c40858] POST[INFO]: {"identityID":"","messageFolder":"","messageUid":0,"saveFolder":"Sent","from":"info@blackbole.com","to":"billahmdmostain@gmail.com","cc":"","bcc":"","replyTo":"","subject":"Another Email","draftInfo":null,"inReplyTo":"","references":"","markAsImportant":0,"attachments":[],"dsn":0,"requireTLS":0,"readReceiptRequest":0,"html":"<div>Let me confirm why its not working?<\/div>","plain":"Let me confirm why its not working?","Action":"SendMessage"}
[2024-01-23 10:01:03.997][36c40858] IMAP[INFO]: Start connection to "ssl://mx.shaperk.com:993"
[2024-01-23 10:01:04.025][36c40858] IMAP[INFO]: Connect (success)
[2024-01-23 10:01:04.025][36c40858] IMAP[DEBUG]: 0.028314113616943 (raw connection)
[2024-01-23 10:01:04.026][36c40858] IMAP[INFO]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN UNSELECT MOVE IDLE APPENDLIMIT AUTH=PLAIN AUTH=LOGIN COMPRESS] IMAP4rev1 Service Ready\r\n
[2024-01-23 10:01:04.026][36c40858] IMAP[DEBUG]: 0.028772830963135 (*)
[2024-01-23 10:01:04.026][36c40858] IMAP[INFO]: > TAG1 AUTHENTICATE PLAIN *******\r\n
[2024-01-23 10:01:04.121][36c40858] IMAP[INFO]: < TAG1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN UNSELECT MOVE IDLE APPENDLIMIT=120 I18NLEVEL=1 SORT THREAD=ORDEREDSUBJECT COMPRESS NAMESPACE] AUTHENTICATE completed\r\n
[2024-01-23 10:01:04.121][36c40858] IMAP[DEBUG]: 0.094758987426758 (TAG1)
[2024-01-23 10:01:04.122][36c40858] SMTP[INFO]: Start connection to "ssl://mx.shaperk.com:465"
[2024-01-23 10:01:04.141][36c40858] SMTP[INFO]: Connect (success)
[2024-01-23 10:01:04.142][36c40858] SMTP[DEBUG]: 0.019060850143433 (raw connection)
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: < 220 mx.shaperk.com ESMTP Service Ready\r\n
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: > EHLO webmail.shaperk.com\r\n
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: < 250-Hello webmail.shaperk.com\r\n
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: < 250-PIPELINING\r\n
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: < 250-8BITMIME\r\n
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: < 250-ENHANCEDSTATUSCODES\r\n
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: < 250-CHUNKING\r\n
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: < 250-AUTH PLAIN LOGIN\r\n
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: < 250-SMTPUTF8\r\n
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: < 250-REQUIRETLS\r\n
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: < 250 SIZE 33554432\r\n
[2024-01-23 10:01:04.142][36c40858] SMTP[INFO]: > AUTH PLAIN\r\n
[2024-01-23 10:01:04.143][36c40858] SMTP[INFO]: < 334 \r\n
[2024-01-23 10:01:04.143][36c40858] SMTP[INFO]: > ********\r\n
[2024-01-23 10:01:04.242][36c40858] SMTP[INFO]: < 235 2.0.0 Authentication succeeded\r\n
[2024-01-23 10:01:04.242][36c40858] SMTP[INFO]: > MAIL FROM:<info@blackbole.com>\r\n
[2024-01-23 10:01:04.242][36c40858] SMTP[INFO]: < 250 2.0.0 Roger, accepting mail from <info@blackbole.com>\r\n
[2024-01-23 10:01:04.242][36c40858] SMTP[INFO]: > RCPT TO:<billahmdmostain@gmail.com>\r\n
[2024-01-23 10:01:04.243][36c40858] SMTP[INFO]: < 250 2.0.0 I'll make sure <billahmdmostain@gmail.com> gets this\r\n
[2024-01-23 10:01:04.243][36c40858] SMTP[INFO]: > DATA\r\n
[2024-01-23 10:01:04.243][36c40858] SMTP[INFO]: < 354 2.0.0 Go ahead. End your data with <CR><LF>.<CR><LF>\r\n
[2024-01-23 10:01:04.243][36c40858] SMTP[INFO]: Message data.
[2024-01-23 10:01:04.244][36c40858] SMTP[INFO]: > .\r\n
[2024-01-23 10:01:04.310][36c40858] SMTP[INFO]: < 250 2.0.0 OK: queued\r\n
[2024-01-23 10:01:04.310][36c40858] SMTP[INFO]: > QUIT\r\n
[2024-01-23 10:01:04.312][36c40858] SMTP[INFO]: < 221 2.0.0 Bye\r\n
[2024-01-23 10:01:04.313][36c40858] SMTP[INFO]: Disconnected from "ssl://mx.shaperk.com:465" (success)
[2024-01-23 10:01:04.313][36c40858] SMTP[DEBUG]: 0.19058179855347 (net session)
[2024-01-23 10:01:04.314][36c40858] IMAP[INFO]: > TAG2 APPEND "Sent" (\Seen) {844}\r\n
[2024-01-23 10:01:04.314][36c40858] IMAP[INFO]: < + send literal\r\n
[2024-01-23 10:01:04.314][36c40858] IMAP[DEBUG]: 0.00054097175598145 (TAG2)
[2024-01-23 10:01:04.314][36c40858] IMAP[INFO]: Write to connection stream
[2024-01-23 10:01:04.314][36c40858] IMAP[INFO]: > \r\n
[2024-01-23 10:01:04.355][36c40858] IMAP[INFO]: < TAG2 NO [TOOBIG] Message size exceeding limit\r\n
[2024-01-23 10:01:04.355][36c40858] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException: TOOBIG Message size exceeding limit in /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/MailSo/Imap/ImapClient.php(542): MailSo\Imap\ResponseCollection->validate()
#1 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/MailSo/Imap/Commands/Messages.php(186): MailSo\Imap\ImapClient->getResponse()
#2 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/MailSo/Imap/Commands/Messages.php(176): MailSo\Imap\ImapClient->writeMessageStream()
#3 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/Actions/Messages.php(242): MailSo\Imap\ImapClient->MessageAppendStream()
#4 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoSendMessage()
#5 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#6 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#7 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/include.php(127): RainLoop\Service::Handle()
#8 /opt/mateors/lxroot/webmail.shaperk.com/public_html/index.php(11): include('/opt/mateors/lx...')
#9 {main}
[2024-01-23 10:01:04.356][36c40858] SERVICE[WARNING]: CantSaveMessage[301]
#0 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoSendMessage()
#1 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/include.php(127): RainLoop\Service::Handle()
#4 /opt/mateors/lxroot/webmail.shaperk.com/public_html/index.php(11): include('/opt/mateors/lx...')
#5 {main}
[2024-01-23 10:01:04.356][36c40858] SERVICE[WARNING]: - TOOBIG Message size exceeding limit @ /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/MailSo/Imap/ResponseCollection.php#46
[2024-01-23 10:01:04.356][36c40858] [ERROR]: MailSo\Imap\Exceptions\NegativeResponseException: TOOBIG Message size exceeding limit in /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/MailSo/Imap/ImapClient.php(542): MailSo\Imap\ResponseCollection->validate()
#1 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/MailSo/Imap/Commands/Messages.php(186): MailSo\Imap\ImapClient->getResponse()
#2 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/MailSo/Imap/Commands/Messages.php(176): MailSo\Imap\ImapClient->writeMessageStream()
#3 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/Actions/Messages.php(242): MailSo\Imap\ImapClient->MessageAppendStream()
#4 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoSendMessage()
#5 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#6 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#7 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/include.php(127): RainLoop\Service::Handle()
#8 /opt/mateors/lxroot/webmail.shaperk.com/public_html/index.php(11): include('/opt/mateors/lx...')
#9 {main}

Next RainLoop\Exceptions\ClientException: CantSaveMessage[301] in /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/Actions/Messages.php:267
Stack trace:
#0 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoSendMessage()
#1 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /opt/mateors/lxroot/webmail.shaperk.com/public_html/snappymail/v/2.33.0/include.php(127): RainLoop\Service::Handle()
#4 /opt/mateors/lxroot/webmail.shaperk.com/public_html/index.php(11): include('/opt/mateors/lx...')
#5 {main}
[2024-01-23 10:01:04.356][36c40858] JSON[INFO]: {"Action":"SendMessage","Result":false,"ErrorCode":301,"ErrorMessage":"","ErrorMessageAdditional":"TOOBIG Message size exceeding limit","epoch":1706004064}
[2024-01-23 10:01:04.356][36c40858] [INFO]: Memory peak usage: 2MB
[2024-01-23 10:01:04.356][36c40858] [INFO]: Time delta: 0.36309504508972
[2024-01-23 10:01:04.356][36c40858] IMAP[INFO]: > TAG3 LOGOUT\r\n
[2024-01-23 10:01:04.356][36c40858] IMAP[INFO]: < * BYE Closing connection\r\n
[2024-01-23 10:01:04.356][36c40858] IMAP[INFO]: < TAG3 OK LOGOUT completed\r\n
[2024-01-23 10:01:04.356][36c40858] IMAP[DEBUG]: 0.00049901008605957 (TAG3)
[2024-01-23 10:01:04.357][36c40858] IMAP[INFO]: Disconnected from "ssl://mx.shaperk.com:993" (success)
[2024-01-23 10:01:04.357][36c40858] IMAP[DEBUG]: 0.35977292060852 (net session)
[2024-01-23 10:01:04.574][e8cf41e5] [INFO]: [SM:2.33.0][IP:103.124.226.97][PID:709155][nginx/1.18.0][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https://webmail.shaperk.com/?/Json/&q[]=/0/]
[2024-01-23 10:01:04.575][e8cf41e5] JSON[INFO]: Action: DoFolderInformation
[2024-01-23 10:01:04.575][e8cf41e5] POST[INFO]: {"folder":"Drafts","flagsUids":[],"uidNext":1,"Action":"FolderInformation"}
[2024-01-23 10:01:04.575][e8cf41e5] IMAP[INFO]: Start connection to "ssl://mx.shaperk.com:993"
[2024-01-23 10:01:04.604][e8cf41e5] IMAP[INFO]: Connect (success)
[2024-01-23 10:01:04.604][e8cf41e5] IMAP[DEBUG]: 0.028417110443115 (raw connection)
[2024-01-23 10:01:04.604][e8cf41e5] IMAP[INFO]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN UNSELECT MOVE IDLE APPENDLIMIT AUTH=PLAIN AUTH=LOGIN COMPRESS] IMAP4rev1 Service Ready\r\n
[2024-01-23 10:01:04.604][e8cf41e5] IMAP[DEBUG]: 0.028854846954346 (*)
[2024-01-23 10:01:04.605][e8cf41e5] IMAP[INFO]: > TAG1 AUTHENTICATE PLAIN *******\r\n
[2024-01-23 10:01:04.701][e8cf41e5] IMAP[INFO]: < TAG1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN UNSELECT MOVE IDLE APPENDLIMIT=120 I18NLEVEL=1 SORT THREAD=ORDEREDSUBJECT COMPRESS NAMESPACE] AUTHENTICATE completed\r\n
[2024-01-23 10:01:04.701][e8cf41e5] IMAP[DEBUG]: 0.096331119537354 (TAG1)
[2024-01-23 10:01:04.701][e8cf41e5] IMAP[INFO]: > TAG2 STATUS "Drafts" (MESSAGES UNSEEN UIDNEXT UIDVALIDITY)\r\n
[2024-01-23 10:01:04.702][e8cf41e5] IMAP[INFO]: < * STATUS "Drafts" (UIDVALIDITY 1444557616 MESSAGES 0 UNSEEN 0 UIDNEXT 1)\r\n
[2024-01-23 10:01:04.702][e8cf41e5] IMAP[INFO]: < TAG2 OK STATUS completed\r\n
[2024-01-23 10:01:04.702][e8cf41e5] IMAP[DEBUG]: 0.00079703330993652 (TAG2)
[2024-01-23 10:01:04.702][e8cf41e5] IMAP[INFO]: > TAG3 SELECT "Drafts"\r\n
[2024-01-23 10:01:04.703][e8cf41e5] IMAP[INFO]: < * FLAGS (\Seen \Answered \Flagged \Deleted \Draft)\r\n
[2024-01-23 10:01:04.703][e8cf41e5] IMAP[INFO]: < * OK [PERMANENTFLAGS (\Seen \Answered \Flagged \Deleted \Draft \*)] Flags permitted.\r\n
[2024-01-23 10:01:04.703][e8cf41e5] IMAP[INFO]: < * OK [UIDVALIDITY 1444557616] UIDs valid\r\n
[2024-01-23 10:01:04.703][e8cf41e5] IMAP[INFO]: < * 0 EXISTS\r\n
[2024-01-23 10:01:04.703][e8cf41e5] IMAP[INFO]: < * 0 RECENT\r\n
[2024-01-23 10:01:04.703][e8cf41e5] IMAP[INFO]: < * OK [UIDNEXT 1] Predicted next UID\r\n
[2024-01-23 10:01:04.703][e8cf41e5] IMAP[INFO]: < TAG3 OK [READ-WRITE] SELECT completed\r\n
[2024-01-23 10:01:04.703][e8cf41e5] IMAP[DEBUG]: 0.00094890594482422 (TAG3)
[2024-01-23 10:01:04.703][e8cf41e5] JSON[INFO]: {"Action":"FolderInformation","Result":{"id":null,"name":"Drafts","uidNext":1,"uidValidity":1444557616,"totalEmails":0,"unreadEmails":0,"highestModSeq":0,"appendLimit":0,"etag":"7b85a15545029ceb308f4f0cf7a6fa47","permanentFlags":["\\Seen","\\Answered","\\Flagged","\\Deleted","\\Draft","\\*"],"messag...
[2024-01-23 10:01:04.703][e8cf41e5] [INFO]: Memory peak usage: 2MB
[2024-01-23 10:01:04.703][e8cf41e5] [INFO]: Time delta: 0.13179898262024
[2024-01-23 10:01:04.703][e8cf41e5] IMAP[INFO]: > TAG4 LOGOUT\r\n
[2024-01-23 10:01:04.704][e8cf41e5] IMAP[INFO]: < * BYE Closing connection\r\n
[2024-01-23 10:01:04.704][e8cf41e5] IMAP[INFO]: < TAG4 OK LOGOUT completed\r\n
[2024-01-23 10:01:04.704][e8cf41e5] IMAP[DEBUG]: 0.00040698051452637 (TAG4)
[2024-01-23 10:01:04.704][e8cf41e5] IMAP[INFO]: Disconnected from "ssl://mx.shaperk.com:993" (success)
[2024-01-23 10:01:04.704][e8cf41e5] IMAP[DEBUG]: 0.12861919403076 (net session)
```

**Comment by the-djmaze** [comment]
```
[2024-01-23 10:01:04.355][36c40858] IMAP[INFO]: < TAG2 NO [TOOBIG] Message size exceeding limit\r\n
```

Says enough. The message is too big.

**Comment by mateors** [comment]
@the-djmaze okay let me check expanding the size of the mailbox, hopefully it will works, thank you for your quick response, I am really grateful to you. We are using snappymail in your [lxroot ](https://lxroot.com) project, I am one of the co-founder, you are welcome to have a test drive of our lxroot

**Comment by the-djmaze** [comment]
You mean https://github.com/parke/lxroot ?

**Comment by mateors** [comment]
@the-djmaze No, lxroot.com

**Comment by gnilebein** [comment]
I think this is realted to this issue: https://github.com/the-djmaze/snappymail/issues/1404

If you define a "Sent" folder in the identity, they will also be saved there. However, if you have selected "Standard" there, they will not be saved!

@mateors Can you confirm this?
