### ISSUE TITLE
Unable to login under PHP 8.3.2 "Authentication failed"

### ISSUE THREAD

**Issue by 73blazer** [the-djmaze/snappymail#1401]
PHP 8.3.2; AIX 7.2.5; AIX Built in IMAP;Snappymail 2.32.0

We've had this site working for years under first rainloop and snappymail for last year plus. Was working fine for the last month or so under php 8.3.1. 
Compiled 8.3.2 with exact same extensions/configure line, nothing else has changed, and when started under php 8.3.2 it is unable to login to snappymail. Admin panel is also unable to login, the same result, "authentication failed. " (see picture). Restart under 8.3.1 and login is successful
As a side note, I still have a rainloop instance on another domain as well (yes I applied that security fix) and it does not exhibit this behavior under 8.3.2, it works just fine. 

![image](https://github.com/the-djmaze/snappymail/assets/74985737/398eaa26-b327-4077-bda1-361ecdfb23e9)

A very preliminary look seems to point to something wrong with the session auth and not actual login auth. Even if I'm already logged in and restart apache with 8.3.2,  any pick then , like on settings, or pick a folder, immediately goes to not authenticated. 

Here is debug report:

`2024-01-21 14:06:25.204][a9ee09c9] [INFO]: [SM:2.32.0][IP:10.1.1.25][PID:11337986][Apache/2.4.58 (Unix) PHP/8.3.2 OpenSSL/3.2.0][apache2handler][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][POST https
://www.mywebsite.com/mail/?/Json/&q[]=/0/]
[2024-01-21 14:06:25.233][a9ee09c9] JSON[INFO]: Action: DoLogin
[2024-01-21 14:06:25.233][a9ee09c9] POST[INFO]: {"Email":"UserX","Password":"*******","language":"","signMe":"0","Action":"Login"}
[2024-01-21 14:06:25.233][a9ee09c9] LOGIN[INFO]: The email address "UserX" is not complete
[2024-01-21 14:06:25.233][a9ee09c9] LOGIN[INFO]: Determined user domain: mywebsite.com
[2024-01-21 14:06:25.240][a9ee09c9] LOGIN[INFO]: Check "mywebsite.com": OK (UserX > UserX@mywebsite.com)
[2024-01-21 14:06:25.249][a9ee09c9] IMAP[ERROR]: InvalidArgumentException in /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/MailSo/Net/NetClient.php:83
Stack trace:
#0 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/MailSo/Imap/ImapClient.php(72): MailSo\Net\NetClient->Connect()
#1 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Model/Account.php(240): MailSo\Imap\ImapClient->Connect()
#2 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/UserAuth.php(426): RainLoop\Model\Account->ImapConnectAndLogin()
#3 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/UserAuth.php(147): RainLoop\Actions->imapConnect()
#4 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/User.php(43): RainLoop\Actions->LoginProcess()
#5 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#6 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#7 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#8 /path/tomywebsite/mail/snappymail/v/2.32.0/include.php(127): RainLoop\Service::Handle()
#9 /path/tomywebsite/mail/index.php(11): include('/path/tomywebsit...')
#10 {main}
[2024-01-21 14:06:26.180][a9ee09c9] SERVICE[WARNING]: AuthError[102]
#0 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/UserAuth.php(147): RainLoop\Actions->imapConnect()
#1 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/User.php(43): RainLoop\Actions->LoginProcess()
#2 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#3 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#4 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /path/tomywebsite/mail/snappymail/v/2.32.0/include.php(127): RainLoop\Service::Handle()
#6 /path/tomywebsite/mail/index.php(11): include('/path/tomywebsit...')
#7 {main}
[2024-01-21 14:06:26.180][a9ee09c9] SERVICE[WARNING]: -  @ /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/MailSo/Net/NetClient.php#83
[2024-01-21 14:06:26.180][a9ee09c9] [ERROR]: InvalidArgumentException in /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/MailSo/Net/NetClient.php:83
Stack trace:
#0 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/MailSo/Imap/ImapClient.php(72): MailSo\Net\NetClient->Connect()
#1 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Model/Account.php(240): MailSo\Imap\ImapClient->Connect()
#2 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/UserAuth.php(426): RainLoop\Model\Account->ImapConnectAndLogin()
#3 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/UserAuth.php(147): RainLoop\Actions->imapConnect()
#4 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/User.php(43): RainLoop\Actions->LoginProcess()
#5 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#6 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#7 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#8 /path/tomywebsite/mail/snappymail/v/2.32.0/include.php(127): RainLoop\Service::Handle()
#9 /path/tomywebsite/mail/index.php(11): include('/path/tomywebsite...')
#10 {main}

Next RainLoop\Exceptions\ClientException: AuthError[102] in /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/UserAuth.php:442
Stack trace:
#0 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/UserAuth.php(147): RainLoop\Actions->imapConnect()
#1 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Actions/User.php(43): RainLoop\Actions->LoginProcess()
#2 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoLogin()
#3 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#4 /path/tomywebsite/mail/snappymail/v/2.32.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#5 /path/tomywebsite/mail/snappymail/v/2.32.0/include.php(127): RainLoop\Service::Handle()
#6 /path/tomywebsite/mail/index.php(11): include('/path/tomywebsit...')
#7 {main}
[2024-01-21 14:06:26.180][a9ee09c9] JSON[INFO]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","epoch":1705845986}
[2024-01-21 14:06:26.180][a9ee09c9] [INFO]: Memory peak usage: 4MB
[2024-01-21 14:06:26.180][a9ee09c9] [INFO]: Time delta: 1.0004608631134`

**Comment by 73blazer** [comment]
Ahhh...i guess I lied, there was something different. I was experimenting with icu and had compiled that, it was on it's own to the side but I had left it in the shell libpath when compiling php 8.3.2 and it must have picked it up. When I recompiled 8.3.2 without icu in the libpath, it seems to function just fine with snappymail.
