### ISSUE TITLE
Cannot login after upgrading from v2.28.3 to 2.34.0: Call to a member function GetPersonalPrefix() on null

### ISSUE THREAD

**Issue by setoy** [the-djmaze/snappymail#1430]
**Describe the bug**
Login fails with no message being displayed.

**Please complete the following information:**
- Browser: Google Chrome Version 121.0.6167.161 (Official Build) (64-bit)
- IMAP daemon: hMailServer
- PHP version: 8.2.15
- SnappyMail Version: 2.24.0
- Mode: Standalone

**Debug/logging information**
```
[2024-02-13 13:34:48.291][4a293910] IMAP[DEBUG]: < TAG3 OK LIST completed\r\n
[2024-02-13 13:34:48.291][4a293910] IMAP[DEBUG]: 0.0018570423126221 (TAG3)
[2024-02-13 13:34:48.291][4a293910] SERVICE[WARNING]: Call to a member function GetPersonalPrefix() on null
#0 D:\inetpub\wwwroot\snappymail\snappymail\v\2.34.0\app\libraries\RainLoop\ServiceActions.php(142): RainLoop\Actions->DoFolders()
#1 D:\inetpub\wwwroot\snappymail\snappymail\v\2.34.0\app\libraries\RainLoop\Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 D:\inetpub\wwwroot\snappymail\snappymail\v\2.34.0\app\libraries\RainLoop\Service.php(14): RainLoop\Service::RunResult()
#3 D:\inetpub\wwwroot\snappymail\snappymail\v\2.34.0\include.php(127): RainLoop\Service::Handle()
#4 D:\inetpub\wwwroot\snappymail\index.php(11): include('...')
#5 {main}
[2024-02-13 13:34:48.291][4a293910] [DEBUG]: Error: Call to a member function GetPersonalPrefix() on null in D:\inetpub\wwwroot\snappymail\snappymail\v\2.34.0\app\libraries\RainLoop\Actions\Folders.php:97
Stack trace:
#0 D:\inetpub\wwwroot\snappymail\snappymail\v\2.34.0\app\libraries\RainLoop\ServiceActions.php(142): RainLoop\Actions->DoFolders()
#1 D:\inetpub\wwwroot\snappymail\snappymail\v\2.34.0\app\libraries\RainLoop\Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 D:\inetpub\wwwroot\snappymail\snappymail\v\2.34.0\app\libraries\RainLoop\Service.php(14): RainLoop\Service::RunResult()
#3 D:\inetpub\wwwroot\snappymail\snappymail\v\2.34.0\include.php(127): RainLoop\Service::Handle()
#4 D:\inetpub\wwwroot\snappymail\index.php(11): include('...')
#5 {main}
[2024-02-13 13:34:48.292][4a293910] JSON[DEBUG]: {"Action":"Folders","Result":false,"ErrorCode":999,"ErrorMessage":"0 - Call to a member function GetPersonalPrefix() on null","ErrorMessageAdditional":"","epoch":1707831288}
[2024-02-13 13:34:48.292][4a293910] [DEBUG]: Memory peak usage: 4MB
[2024-02-13 13:34:48.292][4a293910] [DEBUG]: Time delta: 2.0735077857971
[2024-02-13 13:34:48.292][4a293910] IMAP[DEBUG]: > TAG4 LOGOUT\r\n
[2024-02-13 13:34:48.292][4a293910] IMAP[DEBUG]: < * BYE Have a nice day\r\n
[2024-02-13 13:34:48.292][4a293910] IMAP[DEBUG]: < TAG4 OK Logout completed\r\n
[2024-02-13 13:34:48.292][4a293910] IMAP[DEBUG]: 0.00044798851013184 (TAG4)
[2024-02-13 13:34:48.293][4a293910] IMAP[DEBUG]: Disconnected from "tcp://localhost:143" (success)
[2024-02-13 13:34:48.293][4a293910] IMAP[DEBUG]: 2.0508840084076 (net session)
```

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.34.1
