### ISSUE TITLE
After update to 2.34.1 it keeps loading

### ISSUE THREAD

**Issue by lancos** [the-djmaze/snappymail#1434]
**Describe the bug**
With nextcloud 26.0.11 and SnappyMail 2.33 all works fine as expected. After upgrade of SnappyMail app to 2.34.1 Nextcloud can't load SnappyMail app anymore, the page loops forever with a blank page with SnappyMail text in the middle and a spinner animation.

**To Reproduce**
Upgrade the SnappyMail App to latest version 2.34.1

**Expected behavior**
I expect that snappymail page will be loaded

**Screenshots**
![Screenshot_20240214_155332b](https://github.com/the-djmaze/snappymail/assets/15278592/a69621c2-7b2f-4845-accc-25f43e360e6c)

**Please complete the following information:**
- Browser: Firefox 122.0.1
- IMAP daemon: extenal IMAP server
- PHP version: 8.1
- SnappyMail Version: 2.34.1
- Mode: nextcloud 26.0.11

**Comment by TheNomad11** [comment]
And with Nextcloud 28.0.2 Snappymail puts Nextcloud into maintanence mode and made it totally unusable. So in order to use Nextcloud again I had to remove Snappymail. I remember something similar had happnened before.

**Comment by the-djmaze** [comment]
> And with Nextcloud 28.0.2 Snappymail puts Nextcloud into maintanence mode 

That is not related. See #929



> Nextcloud can't load SnappyMail app anymore, the page loops forever

Open your browser developer tools and see what the error is.
Else check logs https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging

**Comment by jmrapin81** [comment]
Same issue here. Snappymail loads forever. There is no error in dev tools. Since it is reloading forever, I am not sure what I am looking for before the page reloads. I turned on the logs and went looking for the logs on Nextcloud. You should update your page to include the correct location for the logs on Nextcloud.
Anyway. 
That's what I saw:

[2024-02-17 05:39:25.265][a2927539] IMAP[INFO]: > TAG3 LIST "" "*" RETURN (SUBSCRIBED STATUS (MESSAGES UNSEEN UIDNEXT UIDVALIDITY HIGHESTMODSEQ))\r\n
[2024-02-17 05:39:25.277][a2927539] IMAP[INFO]: < * LIST (\HasNoChildren) "/" "INBOX"\r\n
[2024-02-17 05:39:25.277][a2927539] IMAP[INFO]: < * STATUS "INBOX" (MESSAGES 12586 UIDNEXT 163074 UIDVALIDITY 1 UNSEEN 12 HIGHESTMODSEQ 325313)\r\n
[2024-02-17 05:39:25.277][a2927539] IMAP[INFO]: < * LIST (\Subscribed \HasNoChildren) "/" "Activity Stream"\r\n
[2024-02-17 05:39:25.277][a2927539] IMAP[INFO]: < * STATUS "Activity Stream" (MESSAGES 6 UIDNEXT 163057 UIDVALIDITY 117659 UNSEEN 2 HIGHESTMODSEQ 325253)\r\n
[2024-02-17 05:39:25.278][a2927539] IMAP[INFO]: < * LIST (\HasNoChildren) "/" "Admin NGMechanical&IBk-s Inbox"\r\n
[2024-02-17 05:39:25.278][a2927539] IMAP[INFO]: < * STATUS "Admin NGMechanical&IBk-s Inbox" (MESSAGES 137 UIDNEXT 2121 UIDVALIDITY 1 UNSEEN 0 HIGHESTMODSEQ 71881)\r\n
[2024-02-17 05:39:25.278][a2927539] IMAP[INFO]: < * LIST (\Subscribed \HasNoChildren) "/" "All Mail"\r\n
[2024-02-17 05:39:25.278][a2927539] IMAP[INFO]: < * STATUS "All Mail" (MESSAGES 47632 UIDNEXT 145207 UIDVALIDITY 8094 UNSEEN 0 HIGHESTMODSEQ 290936)\r\n
[2024-02-17 05:39:25.278][a2927539] IMAP[INFO]: < * LIST (\Subscribed \HasNoChildren) "/" "Drafts"\r\n
[2024-02-17 05:39:25.278][a2927539] IMAP[INFO]: < * STATUS "Drafts" (MESSAGES 39 UIDNEXT 162858 UIDVALIDITY 1 UNSEEN 0 HIGHESTMODSEQ 324802)\r\n
[2024-02-17 05:39:25.278][a2927539] IMAP[INFO]: < * LIST (\Subscribed \HasNoChildren) "/" "Eguelshardt.org"\r\n
[2024-02-17 05:39:25.278][a2927539] IMAP[INFO]: < * STATUS "Eguelshardt.org" (MESSAGES 60 UIDNEXT 162382 UIDVALIDITY 249694 UNSEEN 0 HIGHESTMODSEQ 323977)\r\n
[2024-02-17 05:39:25.278][a2927539] IMAP[INFO]: < * LIST (\HasNoChildren) "/" "Encrypted&IBk-s Inbox"\r\n
[2024-02-17 05:39:25.279][a2927539] IMAP[INFO]: < * STATUS "Encrypted&IBk-s Inbox" (MESSAGES 1 UIDNEXT 1203 UIDVALIDITY 1 UNSEEN 0 HIGHESTMODSEQ 61877)\r\n
[2024-02-17 05:39:25.279][a2927539] IMAP[INFO]: < * LIST (\Subscribed \NoInferiors) "/" "Junk"\r\n
[2024-02-17 05:39:25.279][a2927539] IMAP[INFO]: < * STATUS "Junk" (MESSAGES 820 UIDNEXT 163065 UIDVALIDITY 1 UNSEEN 764 HIGHESTMODSEQ 325287)\r\n
[2024-02-17 05:39:25.279][a2927539] IMAP[INFO]: < * LIST (\Subscribed \HasNoChildren) "/" "Notes"\r\n
[2024-02-17 05:39:25.279][a2927539] IMAP[INFO]: < * STATUS "Notes" (MESSAGES 9 UIDNEXT 160377 UIDVALIDITY 196977 UNSEEN 0 HIGHESTMODSEQ 319598)\r\n
[2024-02-17 05:39:25.279][a2927539] IMAP[INFO]: < * LIST (\Subscribed \HasNoChildren) "/" "Sent"\r\n
[2024-02-17 05:39:25.279][a2927539] IMAP[INFO]: < * STATUS "Sent" (MESSAGES 8284 UIDNEXT 163068 UIDVALIDITY 1 UNSEEN 0 HIGHESTMODSEQ 325303)\r\n
[2024-02-17 05:39:25.279][a2927539] IMAP[INFO]: < * LIST (\HasNoChildren) "/" "Stratford Apartments&IBk-s Inbox"\r\n
[2024-02-17 05:39:25.279][a2927539] IMAP[INFO]: < * STATUS "Stratford Apartments&IBk-s Inbox" (MESSAGES 707 UIDNEXT 2987 UIDVALIDITY 1 UNSEEN 0 HIGHESTMODSEQ 86893)\r\n
[2024-02-17 05:39:25.280][a2927539] IMAP[INFO]: < * LIST (\Subscribed \HasNoChildren) "/" "Trash"\r\n
[2024-02-17 05:39:25.280][a2927539] IMAP[INFO]: < * STATUS "Trash" (MESSAGES 61 UIDNEXT 163067 UIDVALIDITY 1 UNSEEN 0 HIGHESTMODSEQ 325300)\r\n
[2024-02-17 05:39:25.280][a2927539] IMAP[INFO]: < TAG3 OK LIST completed\r\n
[2024-02-17 05:39:25.280][a2927539] IMAP[DEBUG]: 0.015362024307251 (TAG3)
[2024-02-17 05:39:25.280][a2927539] IMAP[INFO]: > TAG4 NAMESPACE\r\n
[2024-02-17 05:39:25.282][a2927539] IMAP[INFO]: < * NAMESPACE (("" "/")) (("/home/" "/")) NIL\r\n
[2024-02-17 05:39:25.282][a2927539] IMAP[INFO]: < TAG4 OK NAMESPACE completed\r\n
[2024-02-17 05:39:25.282][a2927539] IMAP[DEBUG]: 0.0023908615112305 (TAG4)
[2024-02-17 05:39:25.283][a2927539] IMAP[INFO]: > TAG5 LIST "/home/" "*" RETURN (SUBSCRIBED STATUS (MESSAGES UNSEEN UIDNEXT UIDVALIDITY HIGHESTMODSEQ))\r\n
[2024-02-17 05:39:25.290][a2927539] IMAP[INFO]: < TAG5 NO LIST failed: wildcards not permitted in username\r\n
[2024-02-17 05:39:25.290][a2927539] IMAP[DEBUG]: 0.0078160762786865 (TAG5)
[2024-02-17 05:39:25.291][a2927539] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException:  LIST failed: wildcards not permitted in username in /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.34.2/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.34.2/app/libraries/MailSo/Imap/ImapClient.php(584): MailSo\Imap\ResponseCollection->validate()
#1 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.34.2/app/libraries/MailSo/Imap/Commands/Folders.php(514): MailSo\Imap\ImapClient->yieldUntaggedResponses()
#2 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.34.2/app/libraries/MailSo/Imap/Commands/Folders.php(614): MailSo\Imap\ImapClient->FolderList()
#3 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.34.2/app/libraries/MailSo/Mail/MailClient.php(872): MailSo\Imap\ImapClient->FolderStatusList()
#4 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.34.2/app/libraries/RainLoop/Actions/Folders.php(63): MailSo\Mail\MailClient->Folders()
#5 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.34.2/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoFolders()
#6 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.34.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#7 /var/www/nextcloud/apps/snappymail/app/snappymail/v/2.34.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#8 /var/www/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php(117): RainLoop\Service::Handle()
#9 /var/www/nextcloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp()
#10 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\SnappyMail\Controller\PageController->indexPost()
#11 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher->executeController()
#12 /var/www/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\Http\Dispatcher->dispatch()

**Comment by the-djmaze** [comment]
@jmrapin81 see #1438

**Comment by jmrapin81** [comment]
@the-djmaze thanks. That worked. 

It is worth mentioning that, in order to disable namespace, once in the admin > domains, for each of the domains defined, you need to: 
click on the test button, 
fill in a valid username and password, 
and only then will NAMESPACE keywork show in the list. Tick the NAMESPACE keyword to disable it. 
And save.

Took me a while to realise this. 
HTH

**Comment by the-djmaze** [comment]
@jmrapin81 is just wrote a wiki page for it :wink:
https://github.com/the-djmaze/snappymail/wiki/IMAP-capabilities

**Comment by lancos** [comment]
@the-djmaze, thanks. I confirm disabling NAMESPACE works even for me.

**Comment by the-djmaze** [comment]
https://github.com/the-djmaze/snappymail/releases/tag/v2.35.0
