### ISSUE TITLE
Wrong email address

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#1521]
Hello !

We had the following scenario quite some times now: 
We want to send an email to multiple email addresses. One of these is wrong: bad domain, wrong character in the address (letter with an accent for instance), ...

When the user press Send, a "Can't send email" is shown.

Then by activating the logs, we can see the SMTP exchange with the server and find the error.
For instance:

```
[2024-03-26 17:14:27.166][dba2d436] SMTP[INFO]: > RCPT TO:<info@mart.ch>\r\n
[2024-03-26 17:14:27.182][dba2d436] SMTP[INFO]: < 250 2.1.5 Ok\r\n
[2024-03-26 17:14:27.182][dba2d436] SMTP[INFO]: > RCPT TO:<info@naturevaudoise.ch>\r\n
[2024-03-26 17:14:27.212][dba2d436] SMTP[INFO]: < 450 4.1.2 <info@naturevaudoise.ch>: Recipient address rejected: Domain not found\r\n
[2024-03-26 17:14:27.213][dba2d436] SMTP[ERROR]: MailSo\Smtp\Exceptions\NegativeResponseException: Failed to add recipient 'info@naturevaudoise.ch': 450 4.1.2 <info@naturevaudoise.ch>: Recipient address rejected: Domain not found in /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/MailSo/Smtp/SmtpClient.php:596
Stack trace:
#0 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/MailSo/Smtp/SmtpClient.php(504): MailSo\Smtp\SmtpClient->validateResponse(Array, 'Failed to add r...')
#1 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/MailSo/Smtp/SmtpClient.php(289): MailSo\Smtp\SmtpClient->sendRequestWithCheck('RCPT TO:<info@n...', Array, false, 'Failed to add r...')
#2 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Actions/Messages.php(821): MailSo\Smtp\SmtpClient->Rcpt('info@naturevaud...', false)
#3 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Actions/Messages.php(176): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\AdditionalAccount), Object(MailSo\Mime\Message), Resource id #58, 18534, true, false, false)
#4 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoSendMessage()
#5 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#6 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#7 /var/www/html/apps/snappymail/lib/Util/SnappyMailHelper.php(117): RainLoop\Service::Handle()
#8 /var/www/html/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#9 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\SnappyMail\Controller\PageController->indexPost()
#10 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#11 /var/www/html/lib/private/AppFramework/App.php(183): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#12 /var/www/html/lib/private/Route/Router.php(315): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#13 /var/www/html/lib/base.php(1068): OC\Route\Router->match('/apps/snappymai...')
#14 /var/www/html/index.php(38): OC::handleRequest()
#15 {main}
[2024-03-26 17:14:27.213][dba2d436] SMTP[INFO]: > QUIT\r\n
[2024-03-26 17:14:27.227][dba2d436] SMTP[INFO]: < 221 2.0.0 Bye\r\n
[2024-03-26 17:14:27.227][dba2d436] SMTP[INFO]: Disconnected from "ssl://mail.infomaniak.com:465" (success)
[2024-03-26 17:14:27.228][dba2d436] SMTP[DEBUG]: 0.60878992080688 (net session)
[2024-03-26 17:14:27.228][dba2d436] SERVICE[WARNING]: CantSendMessage[302]
#0 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoSendMessage()
#1 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#2 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /var/www/html/apps/snappymail/lib/Util/SnappyMailHelper.php(117): RainLoop\Service::Handle()
#4 /var/www/html/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#5 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\SnappyMail\Controller\PageController->indexPost()
#6 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#7 /var/www/html/lib/private/AppFramework/App.php(183): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#8 /var/www/html/lib/private/Route/Router.php(315): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#9 /var/www/html/lib/base.php(1068): OC\Route\Router->match('/apps/snappymai...')
#10 /var/www/html/index.php(38): OC::handleRequest()
#11 {main}
[2024-03-26 17:14:27.228][dba2d436] SERVICE[WARNING]: - Failed to add recipient 'info@naturevaudoise.ch': 450 4.1.2 <info@naturevaudoise.ch>: Recipient address rejected: Domain not found @ /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/MailSo/Smtp/SmtpClient.php#596
[2024-03-26 17:14:27.228][dba2d436] [ERROR]: MailSo\Smtp\Exceptions\NegativeResponseException: Failed to add recipient 'info@naturevaudoise.ch': 450 4.1.2 <info@naturevaudoise.ch>: Recipient address rejected: Domain not found in /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/MailSo/Smtp/SmtpClient.php:596
Stack trace:
#0 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/MailSo/Smtp/SmtpClient.php(504): MailSo\Smtp\SmtpClient->validateResponse(Array, 'Failed to add r...')
#1 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/MailSo/Smtp/SmtpClient.php(289): MailSo\Smtp\SmtpClient->sendRequestWithCheck('RCPT TO:<info@n...', Array, false, 'Failed to add r...')
#2 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Actions/Messages.php(821): MailSo\Smtp\SmtpClient->Rcpt('info@naturevaud...', false)
#3 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Actions/Messages.php(176): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\AdditionalAccount), Object(MailSo\Mime\Message), Resource id #58, 18534, true, false, false)
#4 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoSendMessage()
#5 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#6 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#7 /var/www/html/apps/snappymail/lib/Util/SnappyMailHelper.php(117): RainLoop\Service::Handle()
#8 /var/www/html/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#9 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\SnappyMail\Controller\PageController->indexPost()
#10 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#11 /var/www/html/lib/private/AppFramework/App.php(183): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#12 /var/www/html/lib/private/Route/Router.php(315): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#13 /var/www/html/lib/base.php(1068): OC\Route\Router->match('/apps/snappymai...')
#14 /var/www/html/index.php(38): OC::handleRequest()
#15 {main}

Next RainLoop\Exceptions\ClientException: CantSendMessage[302] in /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Actions/Messages.php:304
Stack trace:
#0 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoSendMessage()
#1 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#2 /var/www/html/apps/snappymail/app/snappymail/v/2.35.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /var/www/html/apps/snappymail/lib/Util/SnappyMailHelper.php(117): RainLoop\Service::Handle()
#4 /var/www/html/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#5 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\SnappyMail\Controller\PageController->indexPost()
#6 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#7 /var/www/html/lib/private/AppFramework/App.php(183): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#8 /var/www/html/lib/private/Route/Router.php(315): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#9 /var/www/html/lib/base.php(1068): OC\Route\Router->match('/apps/snappymai...')
#10 /var/www/html/index.php(38): OC::handleRequest()
#11 {main}
[2024-03-26 17:14:27.228][dba2d436] JSON[INFO]: {"Action":"SendMessage","Result":false,"ErrorCode":302,"ErrorMessage":"CantSendMessage[302]","ErrorMessageAdditional":"Failed to add recipient 'info@naturevaudoise.ch': 450 4.1.2 <info@naturevaudoise.ch>: Recipient address rejected: Domain not found","ExceptionCode":0,"epoch":1711473267}
[2024-03-26 17:14:27.228][dba2d436] [INFO]: Memory peak usage: 6MB
[2024-03-26 17:14:27.228][dba2d436] [INFO]: Time delta: 0.8150589466095
```

How the user could be helped in this situation ?

Maybe by grep'ing `SMTP[ERROR]` within the SMTP exchange and displaying it to the user ?

Cheers,
Michel

**Comment by the-djmaze** [comment]
The commit above should change the error in:
![afbeelding](https://github.com/the-djmaze/snappymail/assets/3752035/29201404-05dd-4026-824f-bcb8a8b54227)

**Comment by mmallejac** [comment]
Wow ! That is fast ! :+1: 
Yes, it would be awesome

**Comment by the-djmaze** [comment]
The solution works for you?

**Comment by mmallejac** [comment]
It does !
