### ISSUE TITLE
Redis plugin don't work, when redis require authpass

### ISSUE THREAD

**Issue by ossplus** [the-djmaze/snappymail#1534]
Redis plugin don't work, when redis require authpass, snappymail should add option to set the password

```
[01-Apr-2024 02:02:12 UTC] Uncaught exception: Predis\Response\ServerException: NOAUTH Authentication required. in /data/_data_/_default_/plugins/cache-redis/Predis/Client.php:365 Stack trace: #0 /data/_data_/_default_/plugins/cache-redis/Predis/Client.php(330): Predis\Client->onErrorResponse() #1 /data/_data_/_default_/plugins/cache-redis/Predis/Client.php(309): Predis\Client->executeCommand() #2 /data/_data_/_default_/plugins/cache-redis/Redis.php(82): Predis\Client->__call() #3/snappymail/v/2.36.0/app/libraries/MailSo/Cache/CacheClient.php(61): MailSo\Cache\Drivers\Redis->Get() #4 /snappymail/v/2.36.0/app/libraries/RainLoop/Service.php(202): MailSo\Cache\CacheClient->Get() #5 /snappymail/v/2.36.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult() #6 /snappymail/v/2.36.0/include.php(135): RainLoop\Service::Handle() #7 /index.php(11): include('...') #8 {main}
--
```

**Comment by the-djmaze** [comment]
Did you try to set host as `tcp://127.0.0.1:6379?password=foo&username=bar`?

**Comment by ossplus** [comment]
> Did you try to set host as `tcp://127.0.0.1:6379?password=foo&username=bar`?

It don't work.

**Comment by the-djmaze** [comment]
Try the v2.36.2 plugin. It now uses Predis v2.2.2

**Comment by ossplus** [comment]
works now.
