### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by hampoelz** [the-djmaze/snappymail#1598]
**Describe the bug**
After updating to v2.36.2, I cannot log in to my email account. I get the following error message on the login page:

```
Authentication failed
Server message: AUTHENTICATIONFAILED Authentication failed.
```

Everything works when I test the domain in the admin settings. Other email clients also work fine. I have not found any relevant error log messages.

**Please complete the following information:**
- Browser: Google Chrome v124 (arm64)
- IMAP daemon:
- PHP version: 8.2.19
- SnappyMail Version: 2.36.2
- Mode: nextcloud

**Comment by the-djmaze** [comment]
Enable debu logging through admin or application.ini

It should show why it fails.
There were changes handling SCRAM because of some failing errors and it seems SCRAM is correct now, but will see if your SCRAM is handled differently compared to Mox server.

**Comment by hampoelz** [comment]
<details>
  <summary>snappymail error log</summary>

  ```php
  [2024-05-26 15:48:26.054][2f963b14] POST[INFO]: {"Email":"user@domain","Password":"*******","language":"","signMe":"0","Action":"Login"}
  [2024-05-26 15:48:26.055][2f963b14] PLUGIN[INFO]: Hook: login.credentials.step-2
  [2024-05-26 15:48:26.056][2f963b14] PLUGIN[INFO]: Hook: login.credentials
  [2024-05-26 15:48:26.058][2f963b14] IMAP[INFO]: Start connection to "ssl://mail.domain:993"
  [2024-05-26 15:48:26.203][2f963b14] IMAP[INFO]: Connect (success)
  [2024-05-26 15:48:26.203][2f963b14] IMAP[DEBUG]: 0.14469194412231 (raw connection)
  [2024-05-26 15:48:26.270][2f963b14] IMAP[INFO]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot (Ubuntu) ready.\r\n
  [2024-05-26 15:48:26.271][2f963b14] IMAP[DEBUG]: 0.21284198760986 (*)
  [2024-05-26 15:48:26.271][2f963b14] PLUGIN[INFO]: Hook: imap.before-login
  [2024-05-26 15:48:26.272][2f963b14] IMAP[INFO]: > TAG1 AUTHENTICATE PLAIN *******\r\n
  [2024-05-26 15:48:28.417][2f963b14] IMAP[INFO]: < TAG1 NO [AUTHENTICATIONFAILED] Authentication failed.\r\n
  [2024-05-26 15:48:28.417][2f963b14] IMAP[DEBUG]: 2.1458418369293 (TAG1)
  [2024-05-26 15:48:28.418][2f963b14] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException: AUTHENTICATIONFAILED Authentication failed. in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ResponseCollection.php:46
  Stack trace:
  #0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ImapClient.php(528): MailSo\Imap\ResponseCollection->validate()
  #1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ImapClient.php(166): MailSo\Imap\ImapClient->getResponse()
  #2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Model/Account.php(264): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
  #3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Model/Account.php(206): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
  #4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(444): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
  #5 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(159): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
  #6 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/User.php(39): RainLoop\Actions->LoginProcess('user@domain...', Object(SnappyMail\SensitiveString))
  #7 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoLogin()
  #8 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
  #9 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
  #10 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(119): RainLoop\Service::Handle()
  #11 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
  #12 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(232): OCA\SnappyMail\Controller\PageController->indexPost()
  #13 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(138): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #14 /var/www/html/lib/private/AppFramework/App.php(184): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #15 /var/www/html/lib/private/Route/Router.php(338): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
  #16 /var/www/html/lib/base.php(1050): OC\Route\Router->match('/apps/snappymai...')
  #17 /var/www/html/index.php(49): OC::handleRequest()
  #18 {main}
  [2024-05-26 15:48:28.419][2f963b14] IMAP[NOTICE]: MailSo\Imap\Exceptions\NegativeResponseException: AUTHENTICATIONFAILED Authentication failed. in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ResponseCollection.php:46
  Stack trace:
  #0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ImapClient.php(528): MailSo\Imap\ResponseCollection->validate()
  #1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ImapClient.php(166): MailSo\Imap\ImapClient->getResponse()
  #2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Model/Account.php(264): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
  #3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Model/Account.php(206): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
  #4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(444): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
  #5 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(159): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
  #6 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/User.php(39): RainLoop\Actions->LoginProcess('user@domain...', Object(SnappyMail\SensitiveString))
  #7 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoLogin()
  #8 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
  #9 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
  #10 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(119): RainLoop\Service::Handle()
  #11 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
  #12 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(232): OCA\SnappyMail\Controller\PageController->indexPost()
  #13 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(138): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #14 /var/www/html/lib/private/AppFramework/App.php(184): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #15 /var/www/html/lib/private/Route/Router.php(338): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
  #16 /var/www/html/lib/base.php(1050): OC\Route\Router->match('/apps/snappymai...')
  #17 /var/www/html/index.php(49): OC::handleRequest()
  #18 {main}
  
  Next MailSo\Imap\Exceptions\LoginBadCredentialsException: AUTHENTICATIONFAILED Authentication failed. in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ImapClient.php:232
  Stack trace:
  #0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Model/Account.php(264): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
  #1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Model/Account.php(206): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
  #2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(444): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
  #3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(159): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
  #4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/User.php(39): RainLoop\Actions->LoginProcess('user@domain...', Object(SnappyMail\SensitiveString))
  #5 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoLogin()
  #6 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
  #7 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
  #8 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(119): RainLoop\Service::Handle()
  #9 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
  #10 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(232): OCA\SnappyMail\Controller\PageController->indexPost()
  #11 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(138): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #12 /var/www/html/lib/private/AppFramework/App.php(184): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #13 /var/www/html/lib/private/Route/Router.php(338): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
  #14 /var/www/html/lib/base.php(1050): OC\Route\Router->match('/apps/snappymai...')
  #15 /var/www/html/index.php(49): OC::handleRequest()
  #16 {main}
  [2024-05-26 15:48:30.965][2f963b14] SERVICE[WARNING]: AuthError[102]
  #0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(159): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
  #1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/User.php(39): RainLoop\Actions->LoginProcess('user@domain...', Object(SnappyMail\SensitiveString))
  #2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoLogin()
  #3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
  #4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
  #5 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(119): RainLoop\Service::Handle()
  #6 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
  #7 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(232): OCA\SnappyMail\Controller\PageController->indexPost()
  #8 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(138): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #9 /var/www/html/lib/private/AppFramework/App.php(184): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #10 /var/www/html/lib/private/Route/Router.php(338): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
  #11 /var/www/html/lib/base.php(1050): OC\Route\Router->match('/apps/snappymai...')
  #12 /var/www/html/index.php(49): OC::handleRequest()
  #13 {main}
  [2024-05-26 15:48:30.966][2f963b14] SERVICE[WARNING]: - AUTHENTICATIONFAILED Authentication failed. @ /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ImapClient.php#232
  [2024-05-26 15:48:30.966][2f963b14] [ERROR]: MailSo\Imap\Exceptions\NegativeResponseException: AUTHENTICATIONFAILED Authentication failed. in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ResponseCollection.php:46
  Stack trace:
  #0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ImapClient.php(528): MailSo\Imap\ResponseCollection->validate()
  #1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ImapClient.php(166): MailSo\Imap\ImapClient->getResponse()
  #2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Model/Account.php(264): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
  #3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Model/Account.php(206): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
  #4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(444): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
  #5 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(159): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
  #6 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/User.php(39): RainLoop\Actions->LoginProcess('user@domain...', Object(SnappyMail\SensitiveString))
  #7 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoLogin()
  #8 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
  #9 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
  #10 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(119): RainLoop\Service::Handle()
  #11 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
  #12 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(232): OCA\SnappyMail\Controller\PageController->indexPost()
  #13 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(138): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #14 /var/www/html/lib/private/AppFramework/App.php(184): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #15 /var/www/html/lib/private/Route/Router.php(338): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
  #16 /var/www/html/lib/base.php(1050): OC\Route\Router->match('/apps/snappymai...')
  #17 /var/www/html/index.php(49): OC::handleRequest()
  #18 {main}
  
  Next MailSo\Imap\Exceptions\LoginBadCredentialsException: AUTHENTICATIONFAILED Authentication failed. in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/MailSo/Imap/ImapClient.php:232
  Stack trace:
  #0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Model/Account.php(264): MailSo\Imap\ImapClient->Login(Object(MailSo\Imap\Settings))
  #1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Model/Account.php(206): RainLoop\Model\Account->netClientLogin(Object(MailSo\Imap\ImapClient), Object(RainLoop\Plugins\Manager))
  #2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(444): RainLoop\Model\Account->ImapConnectAndLogin(Object(RainLoop\Plugins\Manager), Object(MailSo\Imap\ImapClient), Object(RainLoop\Config\Application))
  #3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(159): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
  #4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/User.php(39): RainLoop\Actions->LoginProcess('user@domain...', Object(SnappyMail\SensitiveString))
  #5 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoLogin()
  #6 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
  #7 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
  #8 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(119): RainLoop\Service::Handle()
  #9 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
  #10 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(232): OCA\SnappyMail\Controller\PageController->indexPost()
  #11 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(138): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #12 /var/www/html/lib/private/AppFramework/App.php(184): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #13 /var/www/html/lib/private/Route/Router.php(338): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
  #14 /var/www/html/lib/base.php(1050): OC\Route\Router->match('/apps/snappymai...')
  #15 /var/www/html/index.php(49): OC::handleRequest()
  #16 {main}
  
  Next RainLoop\Exceptions\ClientException: AuthError[102] in /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php:455
  Stack trace:
  #0 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(159): RainLoop\Actions->imapConnect(Object(RainLoop\Model\MainAccount), true)
  #1 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/User.php(39): RainLoop\Actions->LoginProcess('user@domain...', Object(SnappyMail\SensitiveString))
  #2 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoLogin()
  #3 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
  #4 /var/www/html/custom_apps/snappymail/app/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
  #5 /var/www/html/custom_apps/snappymail/lib/Util/SnappyMailHelper.php(119): RainLoop\Service::Handle()
  #6 /var/www/html/custom_apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
  #7 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(232): OCA\SnappyMail\Controller\PageController->indexPost()
  #8 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(138): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #9 /var/www/html/lib/private/AppFramework/App.php(184): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
  #10 /var/www/html/lib/private/Route/Router.php(338): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
  #11 /var/www/html/lib/base.php(1050): OC\Route\Router->match('/apps/snappymai...')
  #12 /var/www/html/index.php(49): OC::handleRequest()
  #13 {main}
  [2024-05-26 15:48:30.966][2f963b14] JSON[INFO]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"AuthError[102]","ErrorMessageAdditional":"AUTHENTICATIONFAILED Authentication failed.","ExceptionCode":0,"epoch":1716738510}
  ```
</details>

**Comment by the-djmaze** [comment]
```
IMAP[INFO]: > TAG1 AUTHENTICATE PLAIN *******\r\n
IMAP[INFO]: < TAG1 NO [AUTHENTICATIONFAILED] Authentication failed.\r\n
```

It seems the wrong login username or password is passed.

In application.ini turn off `hide_passwords` and check your log to see which username and password is used.
Don't post the data here as it reveals your credentials.
And after turning on hide_passwords again, remove your logs for safety.

**Comment by hampoelz** [comment]
The username is correct, but the password seems to be a hash and not the actual password.

**Comment by the-djmaze** [comment]
Great, now i can look into it.

**Comment by joergmschulz** [comment]
I've got more like that: Undefined variable $aTokenData at /data/apps/snappymail/app/snappymail/v/2.36.2 . My dovecot log complains login failed:
`Disconnected: Connection closed (auth failed, 1 attempts in 5 secs): user=<firstname.lastname>` where I would expect (and had before): user=email.address@domain.tld which would work. The configuration setting short/long is set correct, and the email of the user is NOT firstname.lastname@domain.tld but ab@domain.tld.

**Comment by CarlBishop** [comment]
Got same issue.

**Comment by nonplusnl** [comment]
Same here. Problem here is that the Nextcloud username is now used by 2.36.2 to log in to the IMAP server, instead of the (different) username actually needed for IMAP.
For another Nextcloud/Snappymail user for which Nextcloud and IMAP username are identical, there is no issue on my instance.

**Comment by extobi** [comment]
same here. AUTHENTICATIONFAILED Authentication failed. after update, nothing change on the IMAP Server or User/Password.

**Comment by cm-schl** [comment]
> The username was already displayed previously and is correct, but the displayed password seems to be a hash and not the actual password.

Have had something similar, maybe this helps to find the problem: https://github.com/the-djmaze/snappymail/issues/1544#issuecomment-2108042898

**Comment by hampoelz** [comment]
v2.36.3 fixed it for me. I'm not sure if anyone else still has authentication problems, otherwise the issue can be closed.
