### ISSUE TITLE
Can't login after update to 2.36.4

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#1653]
**Describe the bug**
I just updated my test instance from 2.33.0 to 2.36.4 and I can't login anymore.

**To Reproduce**
1. Go to login page
2. Fill user/email and password (and TOTP if you use it) and click SIGN IN.
3. It looks like it is going to sign in, but I get back on the login page.

**Expected behavior**
To login :)

**Screenshots**
N/A

**Please complete the following information:**
- Browser: Firefox 127.0.2 , Edge 126.0.2592.87 on Windows 11.
- IMAP daemon: dovecot
- PHP version: 8.1
- SnappyMail Version: 2.36.4
- Mode: standalone

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
- [x] I've placed them here (few lines) or as attachments (many lines)
```
[2024-07-05 08:21:50.745][2fd74ed8] SERVICE[WARNING]: InvalidToken[101]
#0 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail-test/snappymail/v/2.36.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#1 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail-test/snappymail/v/2.36.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#2 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail-test/snappymail/v/2.36.4/include.php(136): RainLoop\Service::Handle()
#3 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail-test/index.php(11): include('...')
#4 {main}
[2024-07-05 08:21:50.948][27b21718] SERVICE[WARNING]: InvalidToken[101]
#0 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail-test/snappymail/v/2.36.4/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#1 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail-test/snappymail/v/2.36.4/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#2 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail-test/snappymail/v/2.36.4/include.php(136): RainLoop\Service::Handle()
#3 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail-test/index.php(11): include('...')
#4 {main}
```

**Additional context**
I also notice the login screen changed from asking Email/Password to Email/Passphrase. Did I miss something in a release note?

**Comment by the-djmaze** [comment]
There are 3 InvalidToken errors:

1. Token mismatch
2. Session gone
3. Account undefined

You probably hit no. 1 so try to clear browser cookies/cache of that website and try again.

**Comment by ervee** [comment]
I tried 3 browsers. Normal and in Private mode. None work with 2.36.4. The log just throws this error.

**Comment by the-djmaze** [comment]
Continued at #1706
