### ISSUE TITLE
IMAP/SMTP test works in admin panel but cannot login

### ISSUE THREAD

**Issue by jobst** [the-djmaze/snappymail#1664]
**Describe the bug**
New to snappymail, just discovered it - do not know where to leave HELP, but also this MAYBE a bug (see below)

The installation process was 100% flawless (thanks!), very quick to set up and get the config going.
I setup admin, changed the username/password and can login.
I have set the IMAP/SMTP stuff correctly (I own the mail server), when I click on test IMAPS/SMTP are successful.
I have also enabled the LOGS so I can see both servers (sendmail/dovecot) respond correctly.

However LOGGING in with the SAME credentials used in the tests does NOT let me login.
The message is "UNKNOWN ERROR"

**To Reproduce**
1. Go to login
2. Enter credentials
3. "Unknown error"

**Expected behavior**
Since I can login using the TESTS, I thought login should be easy.
I can also login using Thunderbird.

**Please complete the following information:**
- Browser: N/A
- IMAP daemon: dovecot 2.2.36
- PHP version: 8.2 (php-fpm)
- SnappyMail Version: I have tried both 2.36.2 and 2.36.4
- Mode: standalone
- MYQLD: 8.0.36

**Debug/logging information**
```
[2024-07-12 08:31:07.135][ea3d65bb] [INFO]: [SM:2.36.2][IP:220.233.246.149][PID:3580][Apache][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2][POST https://voicesoftasmania.org/snappymail/?/Json/&q[]=/0/]
[2024-07-12 08:31:07.139][ea3d65bb] JSON[INFO]: Action: DoLogin
[2024-07-12 08:31:07.139][ea3d65bb] POST[INFO]: {"Email":"HIDDEN","Password":"*******","language":"","signMe":"1","Action":"Login"}
[2024-07-12 08:31:07.141][ea3d65bb] LOGIN[INFO]: The email address 'HIDDEN' is incomplete
[2024-07-12 08:31:07.141][ea3d65bb] LOGIN[INFO]: Default domain '@voicesoftasmania.org' will be used.
[2024-07-12 08:31:12.109][ea3d65bb] SERVICE[WARNING]: Call to a member function SmtpSettings() on null
#0 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Actions.php(268): RainLoop\Model\Account->SmtpUser()
#1 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Actions.php(534): RainLoop\Actions->compileLogParams()
#2 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(155): RainLoop\Actions->LoggerAuthHelper()
#3 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/User.php(41): RainLoop\Actions->LoginProcess()
#4 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoLogin()
#5 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#6 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#7 {PATH}/snappymail/v/2.36.2/include.php(136): RainLoop\Service::Handle()
#8 {PATH}/snappymail/index.php(11): include('{PATH}...')
#9 {main}
[2024-07-12 08:31:12.109][ea3d65bb] [NOTICE]: Error: Call to a member function SmtpSettings() on null in {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Model/Account.php:48
Stack trace:
#0 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Actions.php(268): RainLoop\Model\Account->SmtpUser()
#1 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Actions.php(534): RainLoop\Actions->compileLogParams()
#2 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/UserAuth.php(155): RainLoop\Actions->LoggerAuthHelper()
#3 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Actions/User.php(41): RainLoop\Actions->LoginProcess()
#4 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/ServiceActions.php(134): RainLoop\Actions->DoLogin()
#5 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#6 {PATH}/snappymail/v/2.36.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#7 {PATH}/snappymail/v/2.36.2/include.php(136): RainLoop\Service::Handle()
#8 {PATH}/snappymail/index.php(11): include('{PATH}...')
#9 {main}
[2024-07-12 08:31:12.109][ea3d65bb] JSON[INFO]: {"Action":"Login","Result":false,"ErrorCode":999,"ErrorMessage":"Call to a member function SmtpSettings() on null","ErrorMessageAdditional":"","ExceptionCode":0,"epoch":1720773072}
[2024-07-12 08:31:12.110][ea3d65bb] [INFO]: Memory peak usage: 18MB
[2024-07-12 08:31:12.110][ea3d65bb] [INFO]: Time delta: 5.0006630420685
```

**Additional context**
If there is a "stable version" I would test that.

**Comment by the-djmaze** [comment]
> The email address 'HIDDEN' is incomplete

This means you login with `username` and not with `username@domain.tld`.
So it will use `username@voicesoftasmania.org`.

Is there a domain config in the admin with that domain or you using *?
