### ISSUE TITLE
Unknown Error when deleting an email

### ISSUE THREAD

**Issue by Zero3K** [the-djmaze/snappymail#170]
When I try to delete an email in my account, it gives me a message box stating Unknown Error after deleting the message and then the "Refresh Messages" button spins for a while. The version of Snappymail being used on the server hosting my account is 2.9.4.

**Comment by Zero3K** [comment]
Its also happening in its mobile designed interface.

**Comment by the-djmaze** [comment]
Do you have anything in the error logs?

**Comment by Zero3K** [comment]
Nothing in the developer console of Google Chrome.

**Comment by the-djmaze** [comment]
No i mean, the server php error logs

**Comment by Zero3K** [comment]
I will ask uncled1023 soon and let you know if there are any errors in his logs.

**Comment by uncled1023** [comment]
The only errors I see in the php logs for the time range are the following:

```
[07-Dec-2021 05:24:11 UTC] AuthError[102]
[07-Dec-2021 05:24:11 UTC] 	 Invalid user name or password. @ C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.9.4\app\libraries\MailSo\Imap\ImapClient.php#267
[07-Dec-2021 05:24:15 UTC] AuthError[102]
[07-Dec-2021 05:24:15 UTC] 	 Invalid user name or password. @ C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.9.4\app\libraries\MailSo\Imap\ImapClient.php#267
[07-Dec-2021 07:49:41 UTC] AuthError[102]
[07-Dec-2021 07:49:41 UTC] 	 Invalid user name or password. @ C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.9.4\app\libraries\MailSo\Imap\ImapClient.php#267
[07-Dec-2021 12:40:14 UTC] AuthError[102]
[07-Dec-2021 12:40:14 UTC] 	 Invalid user name or password. @ C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.9.4\app\libraries\MailSo\Imap\ImapClient.php#267
[07-Dec-2021 16:53:57 UTC] AuthError[102]
[07-Dec-2021 18:43:27 UTC] Argument 1 passed to RainLoop\Actions::setContactsSyncData() must be an instance of RainLoop\Model\Account, array given, called in C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.9.4\app\libraries\RainLoop\Actions\Contacts.php on line 30
[07-Dec-2021 20:22:47 UTC] Argument 1 passed to RainLoop\Actions::setContactsSyncData() must be an instance of RainLoop\Model\Account, array given, called in C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.9.4\app\libraries\RainLoop\Actions\Contacts.php on line 30
[07-Dec-2021 20:57:24 UTC] Class 'RainLoop\Model\Notifications' not found
[07-Dec-2021 20:57:38 UTC] Class 'RainLoop\Model\Notifications' not found
[07-Dec-2021 20:57:53 UTC] Class 'RainLoop\Model\Notifications' not found
[07-Dec-2021 20:58:07 UTC] Class 'RainLoop\Model\Notifications' not found
[07-Dec-2021 20:59:23 UTC] Class 'RainLoop\Model\Notifications' not found
[07-Dec-2021 20:59:38 UTC] Class 'RainLoop\Model\Notifications' not found
[07-Dec-2021 20:59:52 UTC] Class 'RainLoop\Model\Notifications' not found
[07-Dec-2021 21:00:09 UTC] Class 'RainLoop\Model\Notifications' not found
[07-Dec-2021 21:02:19 UTC] Class 'RainLoop\Model\Notifications' not found
[07-Dec-2021 21:02:37 UTC] Class 'RainLoop\Model\Notifications' not found
[07-Dec-2021 21:02:53 UTC] Class 'RainLoop\Model\Notifications' not found
[07-Dec-2021 21:03:09 UTC] Class 'RainLoop\Model\Notifications' not found
[08-Dec-2021 15:44:36 UTC] AuthError[102]
[08-Dec-2021 15:44:36 UTC] 	 Invalid user name or password. @ C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.9.4\app\libraries\MailSo\Imap\ImapClient.php#267
[08-Dec-2021 15:44:50 UTC] AuthError[102]
[08-Dec-2021 15:44:50 UTC] 	 Invalid user name or password. @ C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.9.4\app\libraries\MailSo\Imap\ImapClient.php#267
[08-Dec-2021 15:45:48 UTC] AuthError[102]
[08-Dec-2021 15:45:48 UTC] 	 Invalid user name or password. @ C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.9.4\app\libraries\MailSo\Imap\ImapClient.php#267
```

**Comment by Zero3K** [comment]
I think the message asking if a user wants to delete a message is missing (which is resulting in the unknown error).

**Comment by the-djmaze** [comment]
Try with https://github.com/the-djmaze/snappymail/releases/tag/v2.9.5

**Comment by Zero3K** [comment]
Its still happening in 2.9.6.

**Comment by Zero3K** [comment]
I thought you fixed it.

**Comment by Zero3K** [comment]
@uncled1023 what does the log state now?

**Comment by uncled1023** [comment]
I'm not seeing any PHP errors on the backend.  As well, it does look like it actually deletes the email.

**Comment by Zero3K** [comment]
Why am I still getting the error then?

**Comment by the-djmaze** [comment]
@Zero3K I really have no idea why you get the error.
So i made two screenshots of Chromium developer toolbar.

1. Message delete (moves to Trash)
![delete](https://user-images.githubusercontent.com/3752035/147148683-b0cf16d2-47ca-459f-b50f-a763bf2d8b8f.png)

2. Message shift+delete (destroys the image)
![shift-delete](https://user-images.githubusercontent.com/3752035/147148714-335d205e-d843-4953-9d80-a018a469730a.png)

Compare those with your error responses and we might find out.

**Comment by Zero3K** [comment]
1. Message delete (moves to Trash)
![image](https://user-images.githubusercontent.com/6194332/147153794-b91222b2-ab49-4ef5-aaef-74bb03798a5d.png)

2. Message shift+delete (destroys the message)
![image](https://user-images.githubusercontent.com/6194332/147154190-d34ed2ea-37d4-463a-a4e6-03fd9afea2bb.png)

**Comment by Zero3K** [comment]
Why only a partial fix?

**Comment by the-djmaze** [comment]
Because now it:
1. does return data
2. doesn't solve the $this->MailClient()->FolderHash($sFolder) error
3. does log the FolderHash error

Also i removed the FolderHash() from MessageCopy() because it makes no sense there.

To make a full fix the php error log should be examined why FolderHash() fails.

**Comment by Zero3K** [comment]
Okay. Do you get the error or does uncled1023 need to upgrade to the latest source code /version in order to help find the cause of the error?

**Comment by the-djmaze** [comment]
Editing the source will break it due to JavaScript changes.
Just wait for next lease.

**Comment by Zero3K** [comment]
Maybe whatever he needs to generate a hash isn't working for him.

**Comment by Zero3K** [comment]
When will a new release be available?

**Comment by the-djmaze** [comment]
Now

**Comment by Zero3K** [comment]
Thanks :)

**Comment by uncled1023** [comment]
Ok, so tested with latest version and seeing this in the logs now:

```
--- FlushLogCache: WriteOnErrorOnly
[2021-12-29 18:26:02.634][5bcb3772] INFO[DATA]: [DATE:2021-12-29 UTC][SM:2.10.0][IP:157.131.90.2][PID:15900][Microsoft-IIS/10.0][cgi-fcgi][Streams:tcp,udp,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3]
[2021-12-29 18:26:02.634][5bcb3772] REQUEST[NOTE]: [POST] https://mail.teknik.io/?/Json/&q[]=/0/
[2021-12-29 18:26:02.636][5bcb3772] JSON[NOTE]: Action: DoMessageMove
[2021-12-29 18:26:02.636][5bcb3772] POST[DATA]: {"FromFolder":"INBOX","ToFolder":"Trash","Uids":"15413","MarkAsRead":"1","Learning":"","Action":"MessageMove","XToken":"abdbb5936bfc5b5d7d745f06f215adcb40b1dd28"}
[2021-12-29 18:26:02.649][5bcb3772] IMAP[NOTE]: Start connection to "ssl://mail.teknik.io:993"
[2021-12-29 18:26:02.662][5bcb3772] IMAP[NOTE]: Connect (success)
[2021-12-29 18:26:02.663][5bcb3772] IMAP[DATA]: < * OK IMAPrev1

[2021-12-29 18:26:02.663][5bcb3772] IMAP[DATA]: > TAG1 CAPABILITY

[2021-12-29 18:26:02.664][5bcb3772] IMAP[DATA]: < * CAPABILITY IMAP4 IMAP4rev1 CHILDREN IDLE QUOTA SORT ACL NAMESPACE RIGHTS=texk

[2021-12-29 18:26:02.664][5bcb3772] IMAP[DATA]: < TAG1 OK CAPABILITY completed

[2021-12-29 18:26:02.664][5bcb3772] IMAP[SECURE]: > TAG2 LOGIN "support@teknik.io" "********"

[2021-12-29 18:26:02.670][5bcb3772] IMAP[DATA]: < TAG2 OK LOGIN completed

[2021-12-29 18:26:02.670][5bcb3772] IMAP[DATA]: > TAG3 CAPABILITY

[2021-12-29 18:26:02.670][5bcb3772] IMAP[DATA]: < * CAPABILITY IMAP4 IMAP4rev1 CHILDREN IDLE QUOTA SORT ACL NAMESPACE RIGHTS=texk

[2021-12-29 18:26:02.670][5bcb3772] IMAP[DATA]: < TAG3 OK CAPABILITY completed

[2021-12-29 18:26:02.671][5bcb3772] IMAP[DATA]: > TAG4 SELECT "INBOX"

[2021-12-29 18:26:02.672][5bcb3772] IMAP[DATA]: < * 14545 EXISTS

[2021-12-29 18:26:02.672][5bcb3772] IMAP[DATA]: < * 0 RECENT

[2021-12-29 18:26:02.672][5bcb3772] IMAP[DATA]: < * FLAGS (\Deleted \Seen \Draft \Answered \Flagged)

[2021-12-29 18:26:02.672][5bcb3772] IMAP[DATA]: < * OK [UIDVALIDITY 1382623263] current uidvalidity

[2021-12-29 18:26:02.672][5bcb3772] IMAP[DATA]: < * OK [UIDNEXT 15415] next uid

[2021-12-29 18:26:02.672][5bcb3772] IMAP[DATA]: < * OK [PERMANENTFLAGS (\Deleted \Seen \Draft \Answered \Flagged)] limited

[2021-12-29 18:26:02.672][5bcb3772] IMAP[DATA]: < TAG4 OK [READ-WRITE] SELECT completed

[2021-12-29 18:26:02.673][5bcb3772] IMAP[DATA]: > TAG5 SELECT "INBOX"

[2021-12-29 18:26:02.674][5bcb3772] IMAP[DATA]: < * 14545 EXISTS

[2021-12-29 18:26:02.674][5bcb3772] IMAP[DATA]: < * 0 RECENT

[2021-12-29 18:26:02.674][5bcb3772] IMAP[DATA]: < * FLAGS (\Deleted \Seen \Draft \Answered \Flagged)

[2021-12-29 18:26:02.674][5bcb3772] IMAP[DATA]: < * OK [UIDVALIDITY 1382623263] current uidvalidity

[2021-12-29 18:26:02.674][5bcb3772] IMAP[DATA]: < * OK [UIDNEXT 15415] next uid

[2021-12-29 18:26:02.674][5bcb3772] IMAP[DATA]: < * OK [PERMANENTFLAGS (\Deleted \Seen \Draft \Answered \Flagged)] limited

[2021-12-29 18:26:02.674][5bcb3772] IMAP[DATA]: < TAG5 OK [READ-WRITE] SELECT completed

[2021-12-29 18:26:02.675][5bcb3772] IMAP[DATA]: > TAG6 UID STORE 15413 +FLAGS.SILENT (\Seen)

[2021-12-29 18:26:02.679][5bcb3772] IMAP[DATA]: < TAG6 OK UID completed

[2021-12-29 18:26:02.679][5bcb3772] IMAP[DATA]: > TAG7 UID COPY 15413 "Trash"

[2021-12-29 18:26:02.691][5bcb3772] IMAP[DATA]: < TAG7 OK UID completed

[2021-12-29 18:26:02.691][5bcb3772] IMAP[DATA]: > TAG8 UID STORE 15413 +FLAGS.SILENT (\Deleted)

[2021-12-29 18:26:02.699][5bcb3772] IMAP[DATA]: < TAG8 OK UID completed

[2021-12-29 18:26:02.699][5bcb3772] IMAP[DATA]: > TAG9 EXPUNGE

[2021-12-29 18:26:02.711][5bcb3772] IMAP[DATA]: < * 14545 EXPUNGE

[2021-12-29 18:26:02.711][5bcb3772] IMAP[DATA]: < TAG9 OK EXPUNGE Completed

--- FlushLogCache: Trigger
[2021-12-29 18:26:02.712][5bcb3772] INFO[NOTICE]: ArgumentCountError: Too few arguments to function SnappyMail\LOG::warning(), 1 passed in C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.10.0\app\libraries\RainLoop\Actions\Messages.php on line 575 and exactly 2 expected in C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.10.0\app\libraries\snappymail\log.php:18
Stack trace:
#0 C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.10.0\app\libraries\RainLoop\Actions\Messages.php(575): SnappyMail\LOG::warning('FolderHash(INBO...')
#1 C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.10.0\app\libraries\RainLoop\ServiceActions.php(143): RainLoop\Actions->DoMessageMove()
#2 C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.10.0\app\libraries\RainLoop\Service.php(152): RainLoop\ServiceActions->ServiceJson('')
#3 C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.10.0\app\libraries\RainLoop\Service.php(38): RainLoop\Service->RunResult()
#4 C:\inetpub\wwwroot\SnappyMail\snappymail\v\2.10.0\include.php(161): RainLoop\Service::Handle()
#5 C:\inetpub\wwwroot\SnappyMail\index.php(11): include('C:\\inetpub\\wwwr...')
#6 {main}
[2021-12-29 18:26:02.713][5bcb3772] JSON[DATA]: {"Action":"MessageMove","Result":false,"ErrorCode":999,"ErrorMessage":"0 - Too few arguments to function SnappyMail\\LOG::warning(), 1 passed in C:\\inetpub\\wwwroot\\SnappyMail\\snappymail\\v\\2.10.0\\app\\libraries\\RainLoop\\Actions\\Messages.php on line 575 and exactly 2 expected","ErrorMessageA...
[2021-12-29 18:26:02.713][5bcb3772] IMAP[DATA]: > TAG10 LOGOUT\r\n
[2021-12-29 18:26:02.714][5bcb3772] IMAP[DATA]: < * BYE Have a nice day\r\n
[2021-12-29 18:26:02.714][5bcb3772] IMAP[DATA]: < TAG10 OK Logout completed\r\n
[2021-12-29 18:26:02.715][5bcb3772] IMAP[NOTE]: Disconnected from "ssl://mail.teknik.io:993" (success)
[2021-12-29 18:26:02.715][5bcb3772] INFO[MEMORY]: Memory peak usage: 2MB
[2021-12-29 18:26:02.716][5bcb3772] INFO[TIME]: Time delta: 0.1081211566925
```

Either this is a new error around logging, or the original issue is that it can't log a message correctly.

**Comment by the-djmaze** [comment]
I've made a fix for the ArgumentCountError.
Now it should log the error properly

**Comment by Zero3K** [comment]
So he should modify that line himself?

**Comment by Zero3K** [comment]
Or just wait for another release. And then one more once the issue is fixed.

**Comment by the-djmaze** [comment]
@uncled1023 could simply apply the small change and then we should have better info.

**Comment by tobkra** [comment]
I just applied [119f22a](https://github.com/the-djmaze/snappymail/commit/119f22ae611fbe111c14172b52a4d7ed5e957e34) and the error went away in 2.10.0 for me.

**Comment by Zero3K** [comment]
@tobkra does the server log mention the Folder Hash error?

**Comment by tobkra** [comment]
@Zero3K short answer: yes. 

Long answer: Sorry, should have been more specific on the error. The `ArgumentCountError` at `TAG9` disappeared from the logs which in the UI made the *Unkown Error* go away. 

Here is a log for a _message deletion_ **before** I applied 119f22a:

```
[2022-01-04 09:58:47.922][edaf95cf] IMAP[DATA]: > TAG7 UID COPY 16297 "INBOX.Trash"\r\n
[2022-01-04 09:58:47.926][edaf95cf] IMAP[DATA]: < TAG7 OK [COPYUID 470902904 16297 25443] COPY completed.\r\n
[2022-01-04 09:58:47.926][edaf95cf] IMAP[DATA]: > TAG8 UID STORE 16297 +FLAGS.SILENT (\Deleted)\r\n
[2022-01-04 09:58:47.927][edaf95cf] IMAP[DATA]: < TAG8 OK STORE completed.\r\n
[2022-01-04 09:58:47.927][edaf95cf] IMAP[DATA]: > TAG9 UID EXPUNGE 16297\r\n
[2022-01-04 09:58:47.928][edaf95cf] IMAP[DATA]: < * 4 EXPUNGE\r\n
[2022-01-04 09:58:47.928][edaf95cf] IMAP[DATA]: < * 3 EXISTS\r\n
[2022-01-04 09:58:47.928][edaf95cf] IMAP[DATA]: < * 0 RECENT\r\n
[2022-01-04 09:58:47.928][edaf95cf] IMAP[DATA]: < TAG9 OK EXPUNGE completed\r\n
[2022-01-04 09:58:47.928][edaf95cf] SERVICE[WARNING]: Too few arguments to function SnappyMail\LOG::warning(), 1 passed in /var/www/MY_DOMAIN/htdocs/spm-2.10/snappymail/v/2.10.0/app/libraries/RainLoop/Actions/Messages.php on line 575 and exactly 2 expected
[2022-01-04 09:58:47.928][edaf95cf] INFO[NOTICE]: ArgumentCountError: Too few arguments to function SnappyMail\LOG::warning(), 1 passed in /var/www/MY_DOMAIN/htdocs/spm-2.10/snappymail/v/2.10.0/app/libraries/RainLoop/Actions/Messages.php on line 575 and exactly 2 expected in /var/www/MY_DOMAIN/htdocs/spm-2.10/snappymail/v/2.10.0/app/libraries/snappymail/log.php:18
Stack trace:
#0 /var/www/MY_DOMAIN/htdocs/spm-2.10/snappymail/v/2.10.0/app/libraries/RainLoop/Actions/Messages.php(575): SnappyMail\LOG::warning()
#1 /var/www/MY_DOMAIN/htdocs/spm-2.10/snappymail/v/2.10.0/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoMessageMove()
#2 /var/www/MY_DOMAIN/htdocs/spm-2.10/snappymail/v/2.10.0/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceJson()
#3 /var/www/MY_DOMAIN/htdocs/spm-2.10/snappymail/v/2.10.0/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#4 /var/www/MY_DOMAIN/htdocs/spm-2.10/snappymail/v/2.10.0/include.php(161): RainLoop\Service::Handle()
#5 /var/www/MY_DOMAIN/htdocs/spm-2.10/index.php(11): include('/var/www/MY_DOMAIN...')
#6 {main}
```   
And here is a _delete operation_ **after** applying it:
```
[2022-01-04 11:21:27.084][c0ef81e3] IMAP[DATA]: > TAG6 UID STORE 16305 +FLAGS.SILENT (\Seen)\r\n
[2022-01-04 11:21:27.084][c0ef81e3] IMAP[DATA]: < TAG6 OK STORE completed.\r\n
[2022-01-04 11:21:27.084][c0ef81e3] IMAP[DATA]: > TAG7 UID COPY 16305 "INBOX.Trash"\r\n
[2022-01-04 11:21:27.086][c0ef81e3] IMAP[DATA]: < TAG7 OK [COPYUID 470902904 16305 25449] COPY completed.\r\n
[2022-01-04 11:21:27.086][c0ef81e3] IMAP[DATA]: > TAG8 UID STORE 16305 +FLAGS.SILENT (\Deleted)\r\n
[2022-01-04 11:21:27.086][c0ef81e3] IMAP[DATA]: < TAG8 OK STORE completed.\r\n
[2022-01-04 11:21:27.086][c0ef81e3] IMAP[DATA]: > TAG9 UID EXPUNGE 16305\r\n
[2022-01-04 11:21:27.087][c0ef81e3] IMAP[DATA]: < * 3 EXPUNGE\r\n
[2022-01-04 11:21:27.087][c0ef81e3] IMAP[DATA]: < * 2 EXISTS\r\n
[2022-01-04 11:21:27.087][c0ef81e3] IMAP[DATA]: < * 0 RECENT\r\n
[2022-01-04 11:21:27.087][c0ef81e3] IMAP[DATA]: < TAG9 OK EXPUNGE completed\r\n
[2022-01-04 11:21:27.087][c0ef81e3] IMAP[WARNING]: FolderHash(INBOX) Exception: Argument 2 passed to MailSo\Imap\ImapClient::SendRequestGetResponse() must be of the type array, string given, called in /var/www/MY_DOMAIN/htdocs/spm-2.10/snappymail/v/2.10.0/app/libraries/MailSo/Imap/ImapClient.php on line 835
[2022-01-04 11:21:27.087][c0ef81e3] JSON[DATA]: {"Action":"MessageMove","Result":["INBOX"],"Time":38}
[2022-01-04 11:21:27.087][c0ef81e3] IMAP[DATA]: > TAG10 LOGOUT\r\n
[2022-01-04 11:21:27.087][c0ef81e3] IMAP[DATA]: < * BYE Courier-IMAP server shutting down\r\n
[2022-01-04 11:21:27.087][c0ef81e3] IMAP[DATA]: < TAG10 OK LOGOUT completed\r\n
[2022-01-04 11:21:27.087][c0ef81e3] IMAP[NOTE]: Disconnected from "ssl://imap.MY_DOMAIN:993" (success)
```
So, there now I have the an `FolderHash` exception.

**Comment by Zero3K** [comment]
Thanks. That will help in getting the actual problem fixed.

**Comment by the-djmaze** [comment]
Found and solved it 😉

**Comment by Zero3K** [comment]
Thanks. I hope you release a new build soon.

**Comment by Zero3K** [comment]
The error is happening again. Now its a "Can't move message" when I delete one. Here's the error that I get:

```
{Action: "MessageMove", Result: false, ErrorCode: 204, ErrorMessage: "",…}
Action: "MessageMove"
ErrorCode: 204
ErrorMessage: ""
ErrorMessageAdditional: "Argument 1 passed to MailSo\\Imap\\ImapClient::FolderExpunge() must be an instance of MailSo\\Imap\\Commands\\SequenceSet or null, instance of MailSo\\Imap\\SequenceSet given, called in C:\\inetpub\\wwwroot\\SnappyMail\\snappymail\\v\\2.10.2\\app\\libraries\\MailSo\\Mail\\MailClient.php on line 323"
Result: false
Time: 129
```

**Comment by Zero3K** [comment]
Thanks for fixing it.
