### ISSUE TITLE
TypeError: RainLoop\Model\Account::SetPassword(): Argument #1 ($oPassword) must be of type SnappyMail\SensitiveString, string given when changing password on hMailServer

### ISSUE THREAD

**Issue by setoy** [the-djmaze/snappymail#1734]
**Describe the bug**
When trying to change my password, the button simply becomes red. The password, however, is changed.

**To Reproduce**
- Try to change password using hMailServer plugin

**Expected behavior**
The password change should reflect with a green button, not a red one indicating a failure.

**Please complete the following information:**
- Browser: Chrome v128.0.6613.114 (Official Build) (64-bit)
- IMAP daemon: hMailServer
- PHP version: 8.2.21
- SnappyMail Version: 2.37.3
- Mode: standalone

**Debug/logging information**
```
[2024-08-30 21:31:04.999][b3eb8ae2] JSON[DEBUG]: Action: DoPluginChangePassword
[2024-08-30 21:31:04.999][b3eb8ae2] POST[DEBUG]: {"PrevPassword":"*******","NewPassword":"*******","Action":"PluginChangePassword"}
[2024-08-30 21:31:05.000][b3eb8ae2] [DEBUG]: hMailServer: Try to change password for user@domain.com
[2024-08-30 21:31:05.032][b3eb8ae2] [DEBUG]: hMailServer password changed for user@domain.com
[2024-08-30 21:31:05.033][b3eb8ae2] SERVICE[WARNING]: TypeError: RainLoop\Model\Account::SetPassword(): Argument #1 ($oPassword) must be of type SnappyMail\SensitiveString, string given, called in C:\inetpub\wwwroot\webmail\data\_data_\_default_\plugins\change-password\index.php on line 199 and defined in C:\inetpub\wwwroot\webmail\v\2.37.3\app\libraries\RainLoop\Model\Account.php:292
Stack trace:
#0 C:\inetpub\wwwroot\webmail\data\_data_\_default_\plugins\change-password\index.php(199): RainLoop\Model\Account->SetPassword()
#1 C:\inetpub\wwwroot\webmail\snappymail\v\2.37.3\app\libraries\RainLoop\Plugins\Manager.php(370): ChangePasswordPlugin->ChangePassword()
#2 C:\inetpub\wwwroot\webmail\snappymail\v\2.37.3\app\libraries\RainLoop\ServiceActions.php(144): RainLoop\Plugins\Manager->RunAdditionalJson()
#3 C:\inetpub\wwwroot\webmail\snappymail\v\2.37.3\app\libraries\RainLoop\Service.php(132): RainLoop\ServiceActions->ServiceJson()
#4 C:\inetpub\wwwroot\webmail\snappymail\v\2.37.3\app\libraries\RainLoop\Service.php(14): RainLoop\Service::RunResult()
#5 C:\inetpub\wwwroot\webmail\snappymail\v\2.37.3\include.php(137): RainLoop\Service::Handle()
#6 C:\inetpub\wwwroot\webmail\index.php(11): include('...')
#7 {main}
[2024-08-30 21:31:05.033][b3eb8ae2] [DEBUG]: TypeError: RainLoop\Model\Account::SetPassword(): Argument #1 ($oPassword) must be of type SnappyMail\SensitiveString, string given, called in C:\inetpub\wwwroot\webmail\data\_data_\_default_\plugins\change-password\index.php on line 199 and defined in C:\inetpub\wwwroot\webmail\snappymail\v\2.37.3\app\libraries\RainLoop\Model\Account.php:292
Stack trace:
#0 C:\inetpub\wwwroot\webmail\data\_data_\_default_\plugins\change-password\index.php(199): RainLoop\Model\Account->SetPassword()
#1 C:\inetpub\wwwroot\webmail\snappymail\v\2.37.3\app\libraries\RainLoop\Plugins\Manager.php(370): ChangePasswordPlugin->ChangePassword()
#2 C:\inetpub\wwwroot\webmail\snappymail\v\2.37.3\app\libraries\RainLoop\ServiceActions.php(144): RainLoop\Plugins\Manager->RunAdditionalJson()
#3 C:\inetpub\wwwroot\webmail\snappymail\v\2.37.3\app\libraries\RainLoop\Service.php(132): RainLoop\ServiceActions->ServiceJson()
#4 C:\inetpub\wwwroot\webmail\snappymail\v\2.37.3\app\libraries\RainLoop\Service.php(14): RainLoop\Service::RunResult()
#5 C:\inetpub\wwwroot\webmail\snappymail\v\2.37.3\include.php(137): RainLoop\Service::Handle()
#6 C:\inetpub\wwwroot\webmail\index.php(11): include('...')
#7 {main}
[2024-08-30 21:31:05.033][b3eb8ae2] JSON[DEBUG]: {"Action":"PluginChangePassword","Result":false,"code":999,"message":"RainLoop\\Model\\Account::SetPassword(): Argument #1 ($oPassword) must be of type SnappyMail\\SensitiveString, string given, called in C:\\inetpub\\wwwroot\\webmail\\data\\_data_\\_default_\\plugins\\change-password\\index.php ...
[2024-08-30 21:31:05.033][b3eb8ae2] [DEBUG]: Last error: {"type":8192,"message":"Creation of dynamic property ChangePasswordHMailServerDriver::$oLogger is deprecated","file":"C:\\inetpub\\wwwroot\\webmail\\data\\_data_\\_default_\\plugins\\change-password-hmailserver\\driver.php","line":17}
```

**Comment by setoy** [comment]
Nevermind. Had a really old plugin version installed.
