### ISSUE TITLE
Folders error: Undefined constant "LOG_ERROR"

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#1754]
**Describe the bug**
Just updated my instance to 2.38.0 and when logging in with a user with multiple account I get an error: Folders error: Undefined constant "LOG_ERROR". When I login with a standard user with no additional accounts configured this is not an issue as far as I can test.

The log shows:

```
[2024-09-17 07:48:56.168][aca59387] SERVICE[WARNING]: Error: Undefined constant "LOG_ERROR" in /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.38.0/app/libraries/RainLoop/ServiceActions.php:103
Stack trace:
#0 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.38.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#1 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.38.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#2 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.38.0/include.php(137): RainLoop\Service::Handle()
#3 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/index.php(11): include('...')
#4 {main}
```

**To Reproduce**
1. Update to 2.38.0
2. Login with a user with multiple accounts configured (I have 2 extra accounts)

**Expected behavior**
Just login :)

**Screenshots**
![image](https://github.com/user-attachments/assets/389f001f-9e9d-48d2-a23f-944b0b3c57c8)

**Please complete the following information:**
- Browser: All
- IMAP daemon: Dovecot
- PHP version: 8.1
- SnappyMail Version: 2.38.0
- Mode: Standalone

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
- [x] I've placed them here (few lines) or as attachments (many lines)

**Additional context**
Seems only a relevant issue for users with multiple accounts.

**Comment by the-djmaze** [comment]
Related to #1706

**Comment by ervee** [comment]
I made the 2 edits in ServiceActions.php and now I get ```Folders error: HTTP Token mismatch``` when logging in with an account with multiple accounts configured. I changed the index and fast_cache_index in the config amnd reloaded nginx and php-fpm and loaded SnappyMail in a primate window.

**Comment by the-djmaze** [comment]
Change or delete the `data/SALT.php`, maybe that helps

**Comment by ervee** [comment]
It generated a new one on page refresh but the login error stays the same.

**Comment by ervee** [comment]
I just got a message from another user with a "Folders error: HTTP Token mismatch" and not being able to login.

logs:
```
[2024-09-17 19:54:52.141][fbe7af77] Crypt[WARNING]: Decrypt() invalid $data or $key
[2024-09-17 19:54:52.143][fbe7af77] SERVICE[WARNING]: InvalidToken[101]
#0 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#1 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#2 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/include.php(127): RainLoop\Service::Handle()
#3 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/index.php(11): include('...')
#4 {main}
[2024-09-17 19:54:55.902][c75ce0c0] Crypt[WARNING]: Decrypt() invalid $data or $key
[2024-09-17 19:54:55.903][c75ce0c0] SERVICE[WARNING]: InvalidToken[101]
#0 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#1 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#2 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/include.php(127): RainLoop\Service::Handle()
#3 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/index.php(11): include('...')
#4 {main}
[2024-09-17 19:55:00.654][615ea92d] Crypt[WARNING]: Decrypt() invalid $data or $key
[2024-09-17 19:55:00.745][00c5c828] Crypt[WARNING]: Decrypt() invalid $data or $key
[2024-09-17 19:55:05.295][7a196e2a] Crypt[WARNING]: Decrypt() invalid $data or $key
[2024-09-17 19:55:10.724][c5bd29d6] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException: CANNOT Invalid mailbox name: Name is empty (0.001 + 0.000 secs). in /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/MailSo/Imap/ImapClient.php(542): MailSo\Imap\ResponseCollection->validate()
#1 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/MailSo/Imap/ImapClient.php(465): MailSo\Imap\ImapClient->getResponse()
#2 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/MailSo/Imap/Commands/Folders.php(270): MailSo\Imap\ImapClient->SendRequestGetResponse()
#3 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/MailSo/Imap/Commands/Folders.php(192): MailSo\Imap\ImapClient->FolderUnselect()
#4 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/MailSo/Mail/MailClient.php(397): MailSo\Imap\ImapClient->FolderStatus()
#5 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/Actions/Messages.php(550): MailSo\Mail\MailClient->FolderHash()
#6 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoMessageMove()
#7 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#8 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#9 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/include.php(127): RainLoop\Service::Handle()
#10 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/index.php(11): include('...')
#11 {main}
[2024-09-17 19:55:15.433][84b585a5] PdoAddressBook[WARNING]: Sync() invalid DavClient
[2024-09-17 19:55:15.433][84b585a5] SERVICE[WARNING]: ContactsSyncError[140]
#0 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoContactsSync()
#1 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/include.php(127): RainLoop\Service::Handle()
#4 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/index.php(11): include('...')
#5 {main}
[2024-09-17 19:55:15.628][969d9167] PdoAddressBook[WARNING]: Sync() invalid DavClient
[2024-09-17 19:55:15.629][969d9167] SERVICE[WARNING]: ContactsSyncError[140]
#0 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/ServiceActions.php(142): RainLoop\Actions->DoContactsSync()
#1 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#2 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.33.0/include.php(127): RainLoop\Service::Handle()
#4 /srv/www/vhosts/mydomain.tld/htdocs/webmail/snappymail/index.php(11): include('...')
#5 {main}
```

Not sure if this is related. I can create a new bug for it if you want.

I could work-around the update to 2.38 for myself, but this user relies on webmail so I had to revert back to 2.33 (known good for me). Given the security announcement I hope you can get me on 2.38 back soon. Please ask if you need anything from me.
