### ISSUE TITLE
Wrong SMTP server used for selected identity

### ISSUE THREAD

**Issue by gaaf** [the-djmaze/snappymail#1776]
**Describe the bug**
I have multiple domains (A, B) configured and the user has multiple identities on those domains. When viewing account A and composing an email, the user selects the identity `user@B`. When sending the email, the email is sent to domain A's SMTP server instead of domain B's and thus fails to send with an authentication error.

When viewing account B and following the same steps, the email is sent using the correct SMTP server.

**To Reproduce**
See bug description

**Expected behavior**
The email gets sent using the SMTP server configured under the selected identity's domain.

**Please complete the following information:**
- SnappyMail Version: 2.38.0
- Mode: standalone

**Debug/logging information**
- [x] I've placed them here (few lines)
```
[2024-09-25 12:31:13.683][07bf1e05] SMTP[ERROR]: MailSo\Smtp\Exceptions\NegativeResponseException: 535 Incorrect authentication data in /usr/share/snappymail/snappymail/v/2.38.0/app/libr
aries/MailSo/Smtp/SmtpClient.php:598
Stack trace:
#0 /usr/share/snappymail/snappymail/v/2.38.0/app/libraries/MailSo/Smtp/SmtpClient.php(506): MailSo\Smtp\SmtpClient->validateResponse()
#1 /usr/share/snappymail/snappymail/v/2.38.0/app/libraries/MailSo/Smtp/SmtpClient.php(229): MailSo\Smtp\SmtpClient->sendRequestWithCheck()
#2 /usr/share/snappymail/snappymail/v/2.38.0/app/libraries/RainLoop/Model/Account.php(264): MailSo\Smtp\SmtpClient->Login()
#3 /usr/share/snappymail/snappymail/v/2.38.0/app/libraries/RainLoop/Model/Account.php(230): RainLoop\Model\Account->netClientLogin()
#4 /usr/share/snappymail/snappymail/v/2.38.0/app/libraries/RainLoop/Actions/Messages.php(797): RainLoop\Model\Account->SmtpConnectAndLogin()
#5 /usr/share/snappymail/snappymail/v/2.38.0/app/libraries/RainLoop/Actions/Messages.php(192): RainLoop\Actions->smtpSendMessage()
#6 /usr/share/snappymail/snappymail/v/2.38.0/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoSendMessage()
#7 /usr/share/snappymail/snappymail/v/2.38.0/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson()
#8 /usr/share/snappymail/snappymail/v/2.38.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#9 /usr/share/snappymail/snappymail/v/2.38.0/include.php(137): RainLoop\Service::Handle()
#10 /usr/share/snappymail/index.php(11): include('...')
#11 {main}

**Comment by the-djmaze** [comment]
Correct. That's not how identities work.
Accounts is the place to be.
