### ISSUE TITLE
ERROR: Can't get message list

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#181]
**Describe the bug**
After login, the inbox does not show any mails, but only "Can't get message list".
![image](https://user-images.githubusercontent.com/2138442/148594312-a6a78cff-8ff4-45d3-97ad-bbc22fd69f90.png)

**Desktop (please complete the following information):**
 - Google Chrome 96
 - SnappyMail Version 2.10.2

**Log**
```
[2022-01-07 18:56:54.497][85441663] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException:  Error in IMAP command UID FETCH: Unknown parameter: INDEX (0.001 + 0.000 secs). in /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Imap/ImapClient.php(576): MailSo\Imap\ResponseCollection->validate()
#1 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Imap/Commands/Messages.php(90): MailSo\Imap\ImapClient->yieldUntaggedResponses()
#2 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Mail/MailClient.php(677): MailSo\Imap\ImapClient->Fetch(Array, '11299,11289,112...', true)
#3 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Mail/MailClient.php(953): MailSo\Mail\MailClient->MessageListByRequestIndexOrUids(Object(MailSo\Mail\MessageCollection), Object(MailSo\Imap\SequenceSet))
#4 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Actions/Messages.php(73): MailSo\Mail\MailClient->MessageList(Object(MailSo\Mail\MessageListParams))
#5 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoMessageList()
#6 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceJson('')
#7 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#8 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/include.php(162): RainLoop\Service::Handle()
#9 /home/httpd/vhosts/url.com/httpdocs/apps/mail/index.php(11): include('/home/httpd/vho...')
#10 {main}
[2022-01-07 18:56:54.498][85441663] SERVICE[WARNING]: CantGetMessageList[201]
[2022-01-07 18:56:54.499][85441663] SERVICE[WARNING]: 	 Error in IMAP command UID FETCH: Unknown parameter: INDEX (0.001 + 0.000 secs). @ /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Imap/ResponseCollection.php#46
[2022-01-07 18:56:54.499][85441663] INFO[ERROR]: MailSo\Imap\Exceptions\NegativeResponseException:  Error in IMAP command UID FETCH: Unknown parameter: INDEX (0.001 + 0.000 secs). in /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Imap/ResponseCollection.php:46
Stack trace:
#0 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Imap/ImapClient.php(576): MailSo\Imap\ResponseCollection->validate()
#1 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Imap/Commands/Messages.php(90): MailSo\Imap\ImapClient->yieldUntaggedResponses()
#2 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Mail/MailClient.php(677): MailSo\Imap\ImapClient->Fetch(Array, '11299,11289,112...', true)
#3 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Mail/MailClient.php(953): MailSo\Mail\MailClient->MessageListByRequestIndexOrUids(Object(MailSo\Mail\MessageCollection), Object(MailSo\Imap\SequenceSet))
#4 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Actions/Messages.php(73): MailSo\Mail\MailClient->MessageList(Object(MailSo\Mail\MessageListParams))
#5 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoMessageList()
#6 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceJson('')
#7 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#8 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/include.php(162): RainLoop\Service::Handle()
#9 /home/httpd/vhosts/url.com/httpdocs/apps/mail/index.php(11): include('/home/httpd/vho...')
#10 {main}

Next RainLoop\Exceptions\ClientException: CantGetMessageList[201] in /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Actions/Messages.php:77
Stack trace:
#0 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoMessageList()
#1 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceJson('')
#2 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#3 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/include.php(162): RainLoop\Service::Handle()
#4 /home/httpd/vhosts/url.com/httpdocs/apps/mail/index.php(11): include('/home/httpd/vho...')
#5 {main}
[2022-01-07 18:56:54.499][85441663] JSON[DATA]: {"Action":"MessageList","Result":false,"ErrorCode":201,"ErrorMessage":"","ErrorMessageAdditional":" Error in IMAP command UID FETCH: Unknown parameter: INDEX (0.001 + 0.000 secs).","Time":45}
```

**Comment by phsc84** [comment]
Sorry, it works. I must have messed something during the upload...
