### ISSUE TITLE
Problem with Php 8.1 -> sorry it's not php 8.1 as 2.10.2 works

### ISSUE THREAD

**Issue by gene-git** [the-djmaze/snappymail#183]
Happy New Year!

Arch linux - after updating to php 8.1 snappy works to allow login and get list of mail folders, but is unable to retrieve any mail itself. It seems as if the breakage occurred with updated php.

Tested with latest git commit 29fa09079533287f12033047b87726d957362be4

First error in logs is right after the line below:

IMAP[DATA]: > TAG7 UID FETCH 250395,250394,250393,250392,250391,250390,250388,250387,250386,250385,250384,250383,250382,250381,250380,250379,250378,250377,250376,250375 (INDEX UID RFC822.SIZE INTERNALDATE FLAGS BODYSTRUCTURE BODY.PEEK[HEADER.FIELDS (RETURN-PATH RECEIVED MIME-VERSION MESSAGE-ID CONTENT-TYPE FROM TO CC BCC SENDER REPLY-TO DELIVERED-TO IN-REPLY-TO REFERENCES DATE SUBJECT X-MSMAIL-PRIORITY IMPORTANCE X-PRIORITY X-DRAFT-INFO RETURN-RECEIPT-TO DISPOSITION-NOTIFICATION-TO X-CONFIRM-READING-TO AUTHENTICATION-RESULTS X-DKIM-AUTHENTICATION-RESULTS LIST-UNSUBSCRIBE X-SPAM-STATUS X-SPAMD-RESULT X-BOGOSITY X-VIRUS X-VIRUS-SCANNED X-VIRUS-STATUS)])\r\n

IMAP[DATA]: < TAG7 BAD Error in IMAP command UID FETCH: Unknown parameter: INDEX (0.001 + 0.000 secs).\r\n
IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException:  Error in IMAP command UID FETCH: Unknown parameter: INDEX (0.001 + 0.000 secs). in /usr/share/webapps/snappymail/snappymail/v/2.10.2/app/libraries/MailSo/Imap/ResponseCollection.php:46

Stack trace:
#0 /usr/share/webapps/snappymail/snappymail/v/2.10.2/app/libraries/MailSo/Imap/ImapClient.php(577): MailSo\Imap\ResponseCollection->validate()
#1 /usr/share/webapps/snappymail/snappymail/v/2.10.2/app/libraries/MailSo/Imap/Commands/Messages.php(90): MailSo\Imap\ImapClient->yieldUntaggedResponses()
#2 /usr/share/webapps/snappymail/snappymail/v/2.10.2/app/libraries/MailSo/Mail/MailClient.php(677): MailSo\Imap\ImapClient->Fetch()
#3 /usr/share/webapps/snappymail/snappymail/v/2.10.2/app/libraries/MailSo/Mail/MailClient.php(953): MailSo\Mail\MailClient->MessageListByRequestIndexOrUids()
#4 /usr/share/webapps/snappymail/snappymail/v/2.10.2/app/libraries/RainLoop/Actions/Messages.php(73): MailSo\Mail\MailClient->MessageList()
#5 /usr/share/webapps/snappymail/snappymail/v/2.10.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoMessageList()
#6 /usr/share/webapps/snappymail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceJson()
#7 /usr/share/webapps/snappymail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#8 /usr/share/webapps/snappymail/snappymail/v/2.10.2/include.php(162): RainLoop\Service::Handle()
#9 /usr/share/webapps/snappymail/index.php(11): include('...')

**Comment by gene-git** [comment]
Wondering now if this could be related to commit b9c18966ea7218a01d18ec as well?

**Comment by gene-git** [comment]
Release tag 2.10.2 works so its something after the release - between commit b9c18966ea7218a01d18eca2d9b179e15d9d0135 and commit 29fa09079533287f12033047b87726d957362be4 inclusive

**Comment by gene-git** [comment]
Terrific - confirm working fine here - thank you!
