### ISSUE TITLE
RemoteAuthLogin no longer works

### ISSUE THREAD

**Issue by sevmonster** [the-djmaze/snappymail#1835]
**Describe the bug**
I upgraded from v2.35, and now `login-remote` no longer works. It will redirect back to the login page instead of logging in. If the custom login URL is set to `/?RemoteAutoLogin`, you will enter an endless loop.

**To Reproduce**
1. Set up a proxy in front of Snappymail or use a browser that can add headers
2. Send `REMOTE_USER` and `REMOTE_PASSWORD` in request to `/?RemoveAutoLogin`
3. Get redirected back to `/` with login cookies set
4. Doesn't work, asks you to log in again

**Expected behavior**
It works

**Please complete the following information:**
- Browser: Firefox 132.0-1
- IMAP daemon: dovecot
- PHP version: 8.3.13
- SnappyMail Version: 2.38.2
- Mode: standalone

**Debug/logging information**
- [ ] I've placed them here (few lines) or as attachments (many lines)
I cannot get logs. With logging enabled, the process loops and eats memory until it runs out and dies. Probably worthy of a separate issue.

**Additional context**
I set up a new instance with new configuration and it still happens after reinstalling the plugin.

**Comment by sevmonster** [comment]
I managed to get logs working on the latest version of SnappyMail. So I was able to see what caused this.
```
[2024-12-18 18:48:36.051][b72e10fe] [NOTICE]: TypeError: RainLoop\Actions::LoginProcess(): Argument #2 ($oPassword) must be of type SnappyMail\SensitiveString, string given, called in /srv/www/snappymail/data/_data_/_default_/plugins/login-remote/index.php on line 48 and defined in /srv/www/snappymail/snappymail/v/2.38.2/app/libraries/RainLoop/Actions/UserAuth.php:142
Stack trace:
#0 /srv/www/snappymail/data/_data_/_default_/plugins/login-remote/index.php(48): RainLoop\Actions->LoginProcess()
#1 /srv/www/snappymail/snappymail/v/2.38.2/app/libraries/RainLoop/Plugins/Manager.php(371): LoginRemotePlugin->ServiceRemoteAutoLogin()
#2 /srv/www/snappymail/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(133): RainLoop\Plugins\Manager->RunAdditionalPart()
#3 /srv/www/snappymail/snappymail/v/2.38.2/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#4 /srv/www/snappymail/snappymail/v/2.38.2/include.php(137): RainLoop\Service::Handle()
#5 /srv/www/snappymail/index.php(11): include('...')
#6 {main}
```
Looks like at some point the login mechanism was updated to use the `SecureString` class, and the plugin was not. This also affects the `login-cpanel` plugin since it uses the same code.
