### ISSUE TITLE
Folder cannot be deleted

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#221]
**Describe the bug**
Folder cannot be deleted.

**To Reproduce**
Go to folders and try click the delete icon on an empty folder.

**Expected behavior**
Folder is deleted.

**Desktop (please complete the following information):**
 - Chrome 97
 - SnappyMail 2.10.2

**Additional context**
[2022-02-09 08:44:18.086][b761b1dd] SERVICE[WARNING]: CantDeleteFolder[402]
[2022-02-09 08:44:18.086][b761b1dd] SERVICE[WARNING]: 	Call to undefined method MailSo\Mail\MailClient::IsSupported() @ /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Mail/MailClient.php#1266
[2022-02-09 08:44:18.086][b761b1dd] INFO[NOTICE]: Error: Call to undefined method MailSo\Mail\MailClient::IsSupported() in /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Mail/MailClient.php:1266
Stack trace:
#0 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Actions/Folders.php(353): MailSo\Mail\MailClient->FolderDelete('INBOX.folder...', true)
#1 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoFolderDelete()
#2 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceJson('')
#3 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#4 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/include.php(162): RainLoop\Service::Handle()
#5 /home/httpd/vhosts/url.com/httpdocs/apps/mail/index.php(11): include('/home/httpd/vho...')
#6 {main}
[2022-02-09 08:44:18.086][b761b1dd] INFO[ERROR]: Error: Call to undefined method MailSo\Mail\MailClient::IsSupported() in /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/MailSo/Mail/MailClient.php:1266
Stack trace:
#0 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Actions/Folders.php(353): MailSo\Mail\MailClient->FolderDelete('INBOX.folder...', true)
#1 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoFolderDelete()
#2 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceJson('')
#3 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#4 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/include.php(162): RainLoop\Service::Handle()
#5 /home/httpd/vhosts/url.com/httpdocs/apps/mail/index.php(11): include('/home/httpd/vho...')
#6 {main}

Next RainLoop\Exceptions\ClientException: CantDeleteFolder[402] in /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Actions/Folders.php:362
Stack trace:
#0 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoFolderDelete()
#1 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceJson('')
#2 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#3 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.10.2/include.php(162): RainLoop\Service::Handle()
#4 /home/httpd/vhosts/url.com/httpdocs/apps/mail/index.php(11): include('/home/httpd/vho...')
#5 {main}
[2022-02-09 08:44:18.086][b761b1dd] JSON[DATA]: {"Action":"FolderDelete","Result":false,"ErrorCode":402,"ErrorMessage":"","ErrorMessageAdditional":"Call to undefined method MailSo\\Mail\\MailClient::IsSupported()","Time":29}

**Comment by phsc84** [comment]
Ah, ok. Didn't know that. Thanks!
