### ISSUE TITLE
Fatal php Error with v2.12.0

### ISSUE THREAD

**Issue by gene-git** [the-djmaze/snappymail#232]
No login screen is presented - instead there is the 3 dot animation.
php has open_basedir in effect and /usr/bin is not in open_basedir.

 I checked the server log and saw this - perhaps its  relevant:

"PHP message: PHP Fatal error:  Uncaught ArggumentCountError: Too few arguments to function SnappyMail\Log::warning(), 1 passed in /usr/share/webapps/snappymail/snappymail/v/2.12.0/app/libraries/RainLoop/Utils.php on line 230 and exactly 2 expected in /usr/share/webapps/snappymail/snappymail/v/2.12.0/app/libraries/snappymail/log.php:18
Stack trace:
#0 /usr/share/webapps/snappymail/snappymail/v/2.12.0/app/libraries/RainLoop/Utils.php(230): SnappyMail\Log::warning()
#1 [internal function]: RainLoop\Utils::inOpenBasedir()
#2 /usr/share/webapps/snappymail/snappymail/v/2.12.0/app/libraries/snappymail/pgp/gpg.php(1394): array_filter()
...

**Comment by gene-git** [comment]
Thank you - confirm 2.12.1 works well.
