### ISSUE TITLE
No login after update to 2.13.2

### ISSUE THREAD

**Issue by Parodontitis** [the-djmaze/snappymail#263]
**Describe the bug**
Error: "Unknown error" during login with TOTP

**Desktop (please complete the following information):**
 - Browser [e.g. chromium 89, firefox 86, safari 14]
 - SnappyMail Version 2.13.2

**Logfile**

[2022-03-04 10:11:53.441][dab11c04] IMAP[NOTE]: Start connection to "ssl://xx.yy.net:993"
[2022-03-04 10:11:53.460][dab11c04] IMAP[NOTE]: Connect (success)
[2022-03-04 10:11:53.460][dab11c04] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.\r\n
[2022-03-04 10:11:53.461][dab11c04] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN *******\r\n
[2022-03-04 10:11:53.468][dab11c04] IMAP[DATA]: < TAG1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE QUOTA] Logged in\r\n
[2022-03-04 10:11:53.469][dab11c04] PLUGIN[NOTE]: Hook: login.success
[2022-03-04 10:11:53.469][dab11c04] SERVICE[WARNING]: Call to undefined method RainLoop\Utils::DecodeKeyValues()
[2022-03-04 10:11:53.469][dab11c04] INFO[NOTICE]: Error: Call to undefined method RainLoop\Utils::DecodeKeyValues() in /var/www/snappymail/data/_data_/_default_/plugins/two-factor-auth/index.php:250
Stack trace:
#0 /var/www/xx.yy.de/data/_data_/_default_/plugins/two-factor-auth/index.php(39): TwoFactorAuthPlugin->getTwoFactorInfo()
#1 /var/www/xx.yy.de/snappymail/v/2.13.2/app/libraries/RainLoop/Plugins/Manager.php(322): TwoFactorAuthPlugin->DoLogin()
#2 /var/www/xx.yy.de/snappymail/v/2.13.2/app/libraries/RainLoop/Actions/User.php(61): RainLoop\Plugins\Manager->RunHook()
#3 /var/www/xx.yy.de/snappymail/v/2.13.2/app/libraries/RainLoop/ServiceActions.php(144): RainLoop\Actions->DoLogin()
#4 /var/www/xx.yy.de/snappymail/v/2.13.2/app/libraries/RainLoop/Service.php(134): RainLoop\ServiceActions->ServiceJson()
#5 /var/www/xx.yy.de/snappymail/v/2.13.2/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#6 /var/www/xx.yy.de/snappymail/v/2.13.2/include.php(169): RainLoop\Service::Handle()
#7 /var/www/xx.yy.de/index.php(11): include('/var/www/xx.yy...')
#8 {main}
[2022-03-04 10:11:53.469][dab11c04] JSON[DATA]: {"Action":"Login","Result":false,"ErrorCode":999,"ErrorMessage":"0 - Call to undefined method RainLoop\\Utils::DecodeKeyValues()","ErrorMessageAdditional":"","Time":31}
[2022-03-04 10:11:53.470][dab11c04] IMAP[DATA]: > TAG2 LOGOUT\r\n
[2022-03-04 10:11:53.470][dab11c04] IMAP[DATA]: < * BYE Logging out\r\n
[2022-03-04 10:11:53.470][dab11c04] IMAP[DATA]: < TAG2 OK Logout completed (0.001 + 0.000 secs).\r\n
[2022-03-04 10:11:53.470][dab11c04] IMAP[NOTE]: Disconnected from "ssl://xx.yy.net:993" (success)

**Comment by the-djmaze** [comment]
Sorry, i broke the TOTP plugin.
Fixed it.

**Comment by Parodontitis** [comment]
But here is no link to v.2.13.3 and the 2.13.2 shows to nirvana (404).

![grafik](https://user-images.githubusercontent.com/41056353/156755872-aee21142-f372-4719-a30c-dc9b235a4c03.png)

How to install the v.2.13.3?

**Comment by the-djmaze** [comment]
Cache is in effect. Clear the cache in `/_data_/_default_/cache`

**Comment by Parodontitis** [comment]
sorry: but after delete all cache files no TOTP Plugin! :-)

![grafik](https://user-images.githubusercontent.com/41056353/156760195-03d8e31b-fb90-47d6-9d03-7cba45f91965.png)

**Comment by the-djmaze** [comment]
Ah, i uploaded wrong version in repo.
It should be back now (after clearing cache).

**Comment by Parodontitis** [comment]
YESSS! Thank you!
