### ISSUE TITLE
plugin ldap-contacts-suggestions: all to undefined method RainLoop\\Model\\MainAccount ::DomainIncHost()

### ISSUE THREAD

**Issue by ZephOne** [the-djmaze/snappymail#367]
**Describe the bug**
I tried to set up the plugin ldap-contacts-suggestions with the same config I used on RainLoop and I got an error in the log when the front-end does a post to the backend to get a suggestions

**To Reproduce**
1. Install, configure and enable plugin `ldap-contacts-suggestions`
2. Click on the `New message` button to write a new mail
3. In the `To` field type a few letters
4. See error in log file on the server

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chromium 89, firefox 86, safari 14]
 - SnappyMail Version [e.g. 2.3.4]

**Mobile (please complete the following information):**
 - firefox 99.0
 - SnappyMail Version 2.15.1

**Error in log**
```
May  5 14:58:24 mysub snappymail: [2022-05-05 12:58:24.147][xxxxxxxx] REQUEST[NOTE]: [POST] https://mysub.domain.com/?/Json/&q[]=/0/
May  5 14:58:24 mysub snappymail: [2022-05-05 12:58:24.148][xxxxxxxx] JSON[NOTE]: Action: DoSuggestions 
May  5 14:58:24 mysub snappymail: [2022-05-05 12:58:24.148][xxxxxxxx] POST[DATA]: {"Query":"laur","Action":"Suggestions","XToken":"mytoken"}
May  5 14:58:24 mysub snappymail: [2022-05-05 12:58:24.156][xxxxxxxx] LDAP[DATA]: ldap_connect: connected
May  5 14:58:24 mysub snappymail: [2022-05-05 12:58:24.158][xxxxxxxx] SERVICE[WARNING]: Call to undefined method RainLoop\Model\MainAccount::DomainIncHost()
May  5 14:58:24 mysub snappymail: [2022-05-05 12:58:24.159][xxxxxxxx] INFO[NOTICE]: Error: Call to undefined method RainLoop\Model\MainAccount::DomainIncHost() in /var/www/webmail/data/_data_/_default_/plugins/ldap-contacts-suggestions/LdapContactsSuggestions.php:227
May  5 14:58:24 mysub snappymail: Stack trace:
May  5 14:58:24 mysub snappymail: #0 /var/www/webmail/data/_data_/_default_/plugins/ldap-contacts-suggestions/LdapContactsSuggestions.php(113): LdapContactsSuggestions->ldapSearch()
May  5 14:58:24 mysub snappymail: #1 /var/www/webmail/snappymail/v/2.15.1/app/libraries/RainLoop/Providers/Suggestions.php(37): LdapContactsSuggestions->Process()
May  5 14:58:24 mysub snappymail: #2 /var/www/webmail/snappymail/v/2.15.1/app/libraries/RainLoop/Actions/User.php(424): RainLoop\Providers\Suggestions->Process()
May  5 14:58:24 mysub snappymail: #3 /var/www/webmail/snappymail/v/2.15.1/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoSuggestions()
May  5 14:58:24 mysub snappymail: #4 /var/www/webmail/snappymail/v/2.15.1/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
May  5 14:58:24 mysub snappymail: #5 /var/www/webmail/snappymail/v/2.15.1/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
May  5 14:58:24 mysub snappymail: #6 /var/www/webmail/snappymail/v/2.15.1/include.php(169): RainLoop\Service::Handle()
May  5 14:58:24 mysub snappymail: #7 /var/www/webmail/index.php(11): include('/var/www/webmai...')
May  5 14:58:24 mysub snappymail: #8 {main}
May  5 14:58:24 mysub snappymail: [2022-05-05 12:58:24.159][ee146968] JSON[DATA]: {"Action":"Suggestions","Result":false,"ErrorCode":999,"ErrorMessage":"0 - Call to undefined method RainLoop\\Model\\MainAccount
::DomainIncHost()","ErrorMessageAdditional":"","Time":19}

```

Should the method `DomainIncHost()` also be defined in LdapContactsSuggestions abstract class ? It was in RainLoop source code but  RainLoop\Model\Account (abstract class of  RainLoop\Model\MainAccount) definition seems totally different.

If apply this patch:
```diff
diff --git a/snappymail/v/0.0.0/app/libraries/RainLoop/Model/Account.php b/snappymail/v/0.0.0/app/libraries/RainLoop/Model/Account.php
index eb8aa36f6..cfb7f5804 100644
--- a/snappymail/v/0.0.0/app/libraries/RainLoop/Model/Account.php
+++ b/snappymail/v/0.0.0/app/libraries/RainLoop/Model/Account.php
@@ -105,6 +105,16 @@ abstract class Account implements \JsonSerializable
                return $this->oDomain;
        }
 
+       public function DomainIncHost()
+       {
+               return $this->Domain()->IncHost();
+       }
+
+       public function DomainIncPort()
+       {
+               return $this->Domain()->IncPort();
+       }
+
        public function Hash() : string
        {
                return \sha1(\implode(APP_SALT, [
```
it works. But I don't know if it's the good way to do it.
If it is, I can of course do a pull request.

**Comment by ZephOne** [comment]
@the-djmaze Thanks !
