### ISSUE TITLE
Cannot login with 2.16.1 (no such table: rainloop_users)

### ISSUE THREAD

**Issue by gramakri** [the-djmaze/snappymail#418]
**Describe the bug**
Login fails with a fresh install of 2.16.1

**To Reproduce**
1. Install 2.16.1
2. Try to login
3. Says "Unknown error"

**Expected behavior**
Should be able to login

**Screenshots**
![image](https://user-images.githubusercontent.com/82041/170417465-a1267ef8-1f3d-4ca7-a17b-1bc8eee1ae28.png)

**Additional context**
- Cloudron package

**Logs**
```
21:37:08 - [Thu May 26 04:37:08.551628 2022] [php7:notice] [pid 21] [client 172.18.0.1:56756] TOKENS DEBUG: New SESSION_TOKEN
21:37:08 - [Thu May 26 04:37:08.565542 2022] [php7:notice] [pid 21] [client 172.18.0.1:56756] SERVICE WARNING: SQLSTATE[HY000]: General error: 1 no such table: rainloop_users
```

The sqlite3 table is also empty:
```
root@a47bcf4b-9a56-4f30-82cf-4c83701290a2:/app/data# ls -l ./_data_/_default_/AddressBook.sqlite
-rw------- 1 www-data www-data 0 May 26 04:37 ./_data_/_default_/AddressBook.sqlite
```

**Comment by gramakri** [comment]
With 2.16.0, we hit #411 , #409 which is supposed to be fixed in 2.16.1

**Comment by gramakri** [comment]
It looks like some query is made against the sqlite address book but the migrations have not been run .

Sometimes, I get the exception below:

```
[Thu May 26 05:01:44.484336 2022] [php7:error] [pid 84] [client 172.18.0.1:57966] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: rainloop_users in /app/code/snappymail/v/2.16.1/app/libraries/RainLoop/Common/PdoAbstract.php:171\nStack trace:\n#0 /app/code/snappymail/v/2.16.1/app/libraries/RainLoop/Common/PdoAbstract.php(171): PDO->prepare()\n#1 /app/code/snappymail/v/2.16.1/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(1422): RainLoop\\Common\\PdoAbstract->prepareAndExecute()\n#2 /app/code/snappymail/v/2.16.1/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(79): RainLoop\\Providers\\AddressBook\\PdoAddressBook->getUserId()\n#3 /app/code/snappymail/v/2.16.1/app/libraries/RainLoop/Actions.php(508): RainLoop\\Providers\\AddressBook\\PdoAddressBook->SetEmail()\n#4 /app/code/snappymail/v/2.16.1/app/libraries/RainLoop/Actions.php(793): RainLoop\\Actions->AddressBookProvider()\n#5 /app/code/snappymail/v/2.16.1/app/libraries/RainLoop/ServiceActions.php(837): RainLoop\\Actions->AppData()\n#6 /app/code/snappymail/v/2.16.1/app/libraries/RainLoop/ServiceActions.p in /app/code/snappymail/v/2.16.1/app/libraries/RainLoop/Common/PdoAbstract.php on line 171

```

**Comment by gramakri** [comment]
@the-djmaze thanks! Should I keep this report open?

**Comment by the-djmaze** [comment]
@gramakri yes, just keep it open so that people know the contacts system is broken.
