### ISSUE TITLE
Override SMTP Credential plugin seems to work with one identity only

### ISSUE THREAD

**Issue by xmzl** [the-djmaze/snappymail#431]
The Override SMTP Credential plugin seems to work correctly with accounts that have one identity. However, with multi-identity accounts it always returns the error 'Authentication failed', whatever identity is used.
Debian 11, Linux 4.19.0-17-amd64 on x86_64

To Reproduce
Setup of sending via an external SMTP
Adding one or more identities to an account
Route all outgoing mail with the SMTP Override plugin

Expected behavior
Authentication failed message

**Comment by xmzl** [comment]
If you mean the configuration in the Administrator panel, the one in the screenshot is the current configuration. I intentionally deleted SMTP User to take the screenshot. The exact same configuration worked in Rainloop

![Schermata del 2022-06-07 15-58-52](https://user-images.githubusercontent.com/71021946/172399992-df209514-e4e2-4048-a73a-88c13ac0261d.png)

**Comment by the-djmaze** [comment]
With the above change you can log what is working and what fails.
However, since the log is `DEBUG` you must modify application.ini to set logging on and the log level at 7

**Comment by xmzl** [comment]
Thanks for the tip. I tried various combinations, e.g. Use short login yes and no, use wildcards or the user list with domain, etc., but nothing seems to work. In fact, looking at the log, it seems that authentication is rejected by the provider, but I am absolutely certain about the User ID + Password since we use them constantly with the phone.
On top of that, when in the Administrator panel I try the connection with the Test button, I always get a green

`[2022-06-09 10:18:38.947][08ec5960] INFO[DATA]: [DATE:2022-06-09 UTC][SM:2.16.3][IP:192.168.1.245][PID:167182][Apache/2.4.53 (Debian) OpenSSL/1.1.1n][apache2handler][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3]
[2022-06-09 10:18:38.948][08ec5960] REQUEST[NOTE]: [POST] https://192.168.1.100/posta2/?/Json/&q[]=/0/
[2022-06-09 10:18:38.948][08ec5960] JSON[NOTE]: Action: DoSendMessage
[2022-06-09 10:18:38.948][08ec5960] POST[DATA]: {"IdentityID":"","MessageFolder":"","MessageUid":0,"SaveFolder":"Sent","From":"Leonardo Zillo Monte Xillo <leonardo@zillo.it>","To":"leonardozmx@gmail.com","Cc":"","Bcc":"","ReplyTo":"","Subject":"tets 0","DraftInfo":null,"InReplyTo":"","References":"","MarkAsImportant":0,"Attachments":[],"Dsn":0,"ReadReceiptRequest":0,"Html":"<div>test 0<br><\/div>","Text":"test 0","Action":"SendMessage","XToken":"69e35985fccd9da11e8614236bedfc0f31a71dce"}
[2022-06-09 10:18:38.951][08ec5960] IMAP[NOTE]: Start connection to "tcp://localhost:143"
[2022-06-09 10:18:38.951][08ec5960] IMAP[NOTE]: Connect (success)
[2022-06-09 10:18:38.963][08ec5960] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN] Dovecot (Debian) ready.\r\n
[2022-06-09 10:18:38.964][08ec5960] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN *******\r\n
[2022-06-09 10:18:38.995][08ec5960] IMAP[DATA]: < TAG1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE] Logged in\r\n
[2022-06-09 10:18:38.996][08ec5960] SMTP[NOTE]: Start connection to "ssl://authsmtp.securemail.pro:465"
[2022-06-09 10:18:39.075][08ec5960] SMTP[NOTE]: Connect (success)
[2022-06-09 10:18:39.092][08ec5960] SMTP[DATA]: < 220 paganini02 cmsmtp authsmtp ESMTP server ready\r\n
[2022-06-09 10:18:39.092][08ec5960] SMTP[DATA]: > EHLO [192.168.1.100]\r\n
[2022-06-09 10:18:39.115][08ec5960] SMTP[DATA]: < 250-paganini02 hello [79.2.139.141], pleased to meet you\r\n
[2022-06-09 10:18:39.115][08ec5960] SMTP[DATA]: < 250-HELP\r\n
[2022-06-09 10:18:39.115][08ec5960] SMTP[DATA]: < 250-AUTH LOGIN PLAIN\r\n
[2022-06-09 10:18:39.115][08ec5960] SMTP[DATA]: < 250-SIZE 2000000000\r\n
[2022-06-09 10:18:39.115][08ec5960] SMTP[DATA]: < 250-ENHANCEDSTATUSCODES\r\n
[2022-06-09 10:18:39.115][08ec5960] SMTP[DATA]: < 250-PIPELINING\r\n
[2022-06-09 10:18:39.115][08ec5960] SMTP[DATA]: < 250-8BITMIME\r\n
[2022-06-09 10:18:39.115][08ec5960] SMTP[DATA]: < 250 OK\r\n
[2022-06-09 10:18:39.116][08ec5960] SMTP[DATA]: > AUTH LOGIN\r\n
[2022-06-09 10:18:39.137][08ec5960] SMTP[DATA]: < 334 VXNlcm5hbWU6\r\n
[2022-06-09 10:18:39.137][08ec5960] SMTP[DATA]: > bGVvbmFyZG9AemlsbG8uaXQ=\r\n
[2022-06-09 10:18:39.157][08ec5960] SMTP[DATA]: < 334 UGFzc3dvcmQ6\r\n
[2022-06-09 10:18:39.157][08ec5960] SMTP[SECURE]: > ********\r\n
[2022-06-09 10:18:39.198][08ec5960] SMTP[DATA]: < 535 5.7.0 ...authentication rejected\r\n
[2022-06-09 10:18:39.198][08ec5960] SMTP[ERROR]: MailSo\Smtp\Exceptions\NegativeResponseException: 535 5.7.0 ...authentication rejected in /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php:568
Stack trace:
#0 /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php(467): MailSo\Smtp\SmtpClient->validateResponse()
#1 /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php(173): MailSo\Smtp\SmtpClient->sendRequestWithCheck()
#2 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Model/Account.php(331): MailSo\Smtp\SmtpClient->Login()
#3 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Model/Account.php(262): RainLoop\Model\Account->netClientLogin()
#4 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(804): RainLoop\Model\Account->OutConnectAndLoginHelper()
#5 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(176): RainLoop\Actions->smtpSendMessage()
#6 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoSendMessage()
#7 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#8 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#9 /var/www/posta2/snappymail/v/2.16.3/include.php(169): RainLoop\Service::Handle()
#10 /var/www/posta2/index.php(11): include('/var/www/posta2...')
#11 {main}
[2022-06-09 10:18:39.199][08ec5960] SMTP[NOTICE]: MailSo\Smtp\Exceptions\NegativeResponseException: 535 5.7.0 ...authentication rejected in /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php:568
Stack trace:
#0 /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php(467): MailSo\Smtp\SmtpClient->validateResponse()
#1 /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php(173): MailSo\Smtp\SmtpClient->sendRequestWithCheck()
#2 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Model/Account.php(331): MailSo\Smtp\SmtpClient->Login()
#3 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Model/Account.php(262): RainLoop\Model\Account->netClientLogin()
#4 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(804): RainLoop\Model\Account->OutConnectAndLoginHelper()
#5 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(176): RainLoop\Actions->smtpSendMessage()
#6 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoSendMessage()
#7 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#8 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#9 /var/www/posta2/snappymail/v/2.16.3/include.php(169): RainLoop\Service::Handle()
#10 /var/www/posta2/index.php(11): include('/var/www/posta2...')
#11 {main}

Next MailSo\Smtp\Exceptions\LoginBadCredentialsException: 535 5.7.0 ...authentication rejected in /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php:191
Stack trace:
#0 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Model/Account.php(331): MailSo\Smtp\SmtpClient->Login()
#1 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Model/Account.php(262): RainLoop\Model\Account->netClientLogin()
#2 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(804): RainLoop\Model\Account->OutConnectAndLoginHelper()
#3 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(176): RainLoop\Actions->smtpSendMessage()
#4 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoSendMessage()
#5 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#6 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#7 /var/www/posta2/snappymail/v/2.16.3/include.php(169): RainLoop\Service::Handle()
#8 /var/www/posta2/index.php(11): include('/var/www/posta2...')
#9 {main}
[2022-06-09 10:18:39.199][08ec5960] SMTP[DATA]: > QUIT\r\n
[2022-06-09 10:18:39.199][08ec5960] SMTP[ERROR]: Stream Meta: Array
(
    [crypto] => Array
        (
            [protocol] => TLSv1.2
            [cipher_name] => ECDHE-RSA-AES256-GCM-SHA384
            [cipher_bits] => 256
            [cipher_version] => TLSv1.2
        )

    [timed_out] => 
    [blocked] => 1
    [eof] => 1
    [stream_type] => tcp_socket/ssl
    [mode] => r+
    [unread_bytes] => 0
    [seekable] => 
)

[2022-06-09 10:18:39.199][08ec5960] SMTP[ERROR]: MailSo\Net\Exceptions\SocketReadException: MailSo-Net-Exceptions-SocketReadException (NetClient.php ~ 384) in /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Net/NetClient.php:384
Stack trace:
#0 /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php(560): MailSo\Net\NetClient->getNextBuffer()
#1 /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php(467): MailSo\Smtp\SmtpClient->validateResponse()
#2 /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php(399): MailSo\Smtp\SmtpClient->sendRequestWithCheck()
#3 /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Net/NetClient.php(244): MailSo\Smtp\SmtpClient->Logout()
#4 /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Net/NetClient.php(84): MailSo\Net\NetClient->Disconnect()
#5 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(176): MailSo\Net\NetClient->__destruct()
#6 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoSendMessage()
#7 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#8 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#9 /var/www/posta2/snappymail/v/2.16.3/include.php(169): RainLoop\Service::Handle()
#10 /var/www/posta2/index.php(11): include('/var/www/posta2...')
#11 {main}
[2022-06-09 10:18:39.200][08ec5960] SERVICE[WARNING]: AuthError[102]
#0 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(176): RainLoop\Actions->smtpSendMessage()
#1 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoSendMessage()
#2 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#3 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#4 /var/www/posta2/snappymail/v/2.16.3/include.php(169): RainLoop\Service::Handle()
#5 /var/www/posta2/index.php(11): include('/var/www/posta2...')
#6 {main}
[2022-06-09 10:18:39.200][08ec5960] SERVICE[WARNING]: - 535 5.7.0 ...authentication rejected @ /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php#191
[2022-06-09 10:18:39.200][08ec5960] INFO[ERROR]: MailSo\Smtp\Exceptions\NegativeResponseException: 535 5.7.0 ...authentication rejected in /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php:568
Stack trace:
#0 /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php(467): MailSo\Smtp\SmtpClient->validateResponse()
#1 /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php(173): MailSo\Smtp\SmtpClient->sendRequestWithCheck()
#2 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Model/Account.php(331): MailSo\Smtp\SmtpClient->Login()
#3 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Model/Account.php(262): RainLoop\Model\Account->netClientLogin()
#4 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(804): RainLoop\Model\Account->OutConnectAndLoginHelper()
#5 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(176): RainLoop\Actions->smtpSendMessage()
#6 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoSendMessage()
#7 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#8 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#9 /var/www/posta2/snappymail/v/2.16.3/include.php(169): RainLoop\Service::Handle()
#10 /var/www/posta2/index.php(11): include('/var/www/posta2...')
#11 {main}

Next MailSo\Smtp\Exceptions\LoginBadCredentialsException: 535 5.7.0 ...authentication rejected in /var/www/posta2/snappymail/v/2.16.3/app/libraries/MailSo/Smtp/SmtpClient.php:191
Stack trace:
#0 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Model/Account.php(331): MailSo\Smtp\SmtpClient->Login()
#1 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Model/Account.php(262): RainLoop\Model\Account->netClientLogin()
#2 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(804): RainLoop\Model\Account->OutConnectAndLoginHelper()
#3 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(176): RainLoop\Actions->smtpSendMessage()
#4 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoSendMessage()
#5 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#6 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#7 /var/www/posta2/snappymail/v/2.16.3/include.php(169): RainLoop\Service::Handle()
#8 /var/www/posta2/index.php(11): include('/var/www/posta2...')
#9 {main}

Next RainLoop\Exceptions\ClientException: AuthError[102] in /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php:897
Stack trace:
#0 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Actions/Messages.php(176): RainLoop\Actions->smtpSendMessage()
#1 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoSendMessage()
#2 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#3 /var/www/posta2/snappymail/v/2.16.3/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#4 /var/www/posta2/snappymail/v/2.16.3/include.php(169): RainLoop\Service::Handle()
#5 /var/www/posta2/index.php(11): include('/var/www/posta2...')
#6 {main}
[2022-06-09 10:18:39.200][08ec5960] JSON[DATA]: {"Action":"SendMessage","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"535 5.7.0 ...authentication rejected","Time":256}
[2022-06-09 10:18:39.200][08ec5960] IMAP[DATA]: > TAG2 LOGOUT\r\n
[2022-06-09 10:18:39.201][08ec5960] IMAP[DATA]: < * BYE Logging out\r\n
[2022-06-09 10:18:39.201][08ec5960] IMAP[DATA]: < TAG2 OK Logout completed (0.001 + 0.000 secs).\r\n
[2022-06-09 10:18:39.201][08ec5960] IMAP[NOTE]: Disconnected from "tcp://localhost:143" (success)
[2022-06-09 10:18:39.201][08ec5960] INFO[MEMORY]: Memory peak usage: 2MB
[2022-06-09 10:18:39.201][08ec5960] INFO[TIME]: Time delta: 0.25808501243591`

**Comment by xmzl** [comment]
Thanks for the tip. I tried various combinations, e.g. Use short login yes and no, use wildcards or the user list with domain, etc., but nothing seems to work. In fact, looking at the log, it seems that authentication is rejected by the provider, but I am absolutely certain about the User ID + Password since we use them constantly with the phone.
On top of that, when in the Administrator panel I try the connection with the Test button, I always get a green
[5_log-2022-06-09.txt](https://github.com/the-djmaze/snappymail/files/8869485/5_log-2022-06-09.txt)

**Comment by the-djmaze** [comment]
Looking at your log the important part is:
```
[2022-06-09 10:18:38.996][08ec5960] SMTP[NOTE]: Start connection to "ssl://authsmtp.securemail.pro:465"
[2022-06-09 10:18:39.075][08ec5960] SMTP[NOTE]: Connect (success)
[2022-06-09 10:18:39.116][08ec5960] SMTP[DATA]: > AUTH LOGIN\r\n
[2022-06-09 10:18:39.137][08ec5960] SMTP[DATA]: < 334 VXNlcm5hbWU6\r\n
[2022-06-09 10:18:39.137][08ec5960] SMTP[DATA]: > Base32String=\r\n 
```

Where the `Base32String=\r\n` is something like `da.vinci@zillo.it`
But the question is: which password is used for that username?
To find that out you must edit `application.ini` and set:
```
hide_passwords = Off
```
NOTE:
* never post the log
* only do this while testing
* remove the log afterwards
* set back to `On`

**Comment by the-djmaze** [comment]
Added a new plugin named "Login Override" for next v2.25.2
It has two mapping options: IMAP and SMTP

Each line in the field will be like `user@example.com:user1:password1`
* `user@example.com` the currently used email address to login with
* `user1` when set it will be used for IMAP or SMTP login
* `password1` when set it will be used for IMAP or SMTP login

`user@example.com::password1` will use the default login name
`user@example.com:user1:` will use the default login password

Why v2.25.2? Well i've modified the config options system to allow storing encrypted values.
As the mapping contains sensitive login credentials it will be stored encrypted.
