### ISSUE TITLE
Unable to send outbound mail

### ISSUE THREAD

**Issue by CodehXodeh** [the-djmaze/snappymail#478]
**SnappyMail version, browser, browser version:**
2.17.1, Firefox 103.0.1

Keep having issue come up when trying to send email "Can't send message" using both SSL/Non-SSL methods still no luck.

```
[2022-08-05 00:18:14.879][f24ab670] SERVICE[WARNING]: CantSendMessage[302]
#0 /home/kaspnuez/party1033.com/mail/snappymail/v/2.17.1/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoSendMessage()
#1 /home/kaspnuez/party1033.com/mail/snappymail/v/2.17.1/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson('')
#2 /home/kaspnuez/party1033.com/mail/snappymail/v/2.17.1/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#3 /home/kaspnuez/party1033.com/mail/snappymail/v/2.17.1/include.php(169): RainLoop\Service::Handle()
#4 /home/kaspnuez/party1033.com/mail/index.php(11): include('/home/kaspnuez/...')
#5 {main}
[2022-08-05 00:18:14.879][f24ab670] SERVICE[WARNING]: - Failed to add recipient "webmaster@party1033.com": 550-"Your IP: 198.54.120.203 : Your domain party1033.com is not allowed in

550 header From" @ /home/kaspnuez/party1033.com/mail/snappymail/v/2.17.1/app/libraries/MailSo/Smtp/SmtpClient.php#568
[2022-08-05 00:18:14.879][f24ab670] INFO[ERROR]: MailSo\Smtp\Exceptions\NegativeResponseException: Failed to add recipient "webmaster@party1033.com": 550-"Your IP: 198.54.120.203 : Your domain party1033.com is not allowed in

550 header From" in /home/kaspnuez/party1033.com/mail/snappymail/v/2.17.1/app/libraries/MailSo/Smtp/SmtpClient.php:568
```

**Comment by the-djmaze** [comment]
Error is at:
```
Failed to add recipient "webmaster@party1033.com":
"Your domain party1033.com is not allowed in header From"
```

How is your SMTP setup?
* which daemon
* which daemon verion
* who configured it
* etc.

**Comment by CodehXodeh** [comment]
Turned out to be a host routing issue which got resolved. Everything is working now! :)
