### ISSUE TITLE
General slowdown

### ISSUE THREAD

**Issue by grawlinson** [the-djmaze/snappymail#49]
**RainLoop version, browser, OS:**

- snappymail 2.1.1
- macOS (Safari & Firefox)
- Arch Linux (Firefox)

**Expected behavior and actual behavior:**

- Sieve filters never get "saved", the loading icon keeps spinning.
- Initial load of Inbox takes a minute or two. Subsequent loads (Inbox/Folders) sometimes take longer.

**Steps to reproduce the problem:**

Have only just swapped over to Snappymail from Rainloop, clean install. Deleted all old configuration.

**Logs or screenshots:**

There's a _lot_ of this in my logs.

```
[2020-12-30 03:25:08.401][b6ccf64c] PHP[NOTICE]: Error: Undefined property: MailSo\Log\Drivers\File::$DateTimeZone
[2020-12-30 03:25:08.402][b6ccf64c] AJAX[DATA]: {"Action":"FolderInformationMultiply","Result":{"List":[{"Folder":"deadbeef-general","Hash":"xxx","MessageCount":1016,"MessageUnseenCount":10,"UidNext":"1022","Flags":[],"HighestModSeq":"2033","NewMessages":[]},{"Folder":"deadbeef-requests","Hash":"xxx...
[2020-12-30 03:25:08.404][b6ccf64c] PHP[NOTICE]: /usr/share/snappymail/snappymail/v/2.1.1/app/libraries/MailSo/Log/Driver.php [line:194, code:8]
[2020-12-30 03:25:08.405][b6ccf64c] PHP[NOTICE]: Error: Undefined property: MailSo\Log\Drivers\File::$DateTimeZone
[2020-12-30 03:25:08.405][b6ccf64c] IMAP[DATA]: > TAG7 LOGOUT\r\n
[2020-12-30 03:25:08.405][b6ccf64c] PHP[NOTICE]: /usr/share/snappymail/snappymail/v/2.1.1/app/libraries/MailSo/Log/Driver.php [line:194, code:8]
[2020-12-30 03:25:08.405][b6ccf64c] PHP[NOTICE]: Error: Undefined property: MailSo\Log\Drivers\File::$DateTimeZone
[2020-12-30 03:25:08.406][b6ccf64c] IMAP[DATA]: < * BYE Logging out\r\n
[2020-12-30 03:25:08.406][b6ccf64c] PHP[NOTICE]: /usr/share/snappymail/snappymail/v/2.1.1/app/libraries/MailSo/Log/Driver.php [line:194, code:8]
[2020-12-30 03:25:08.406][b6ccf64c] PHP[NOTICE]: Error: Undefined property: MailSo\Log\Drivers\File::$DateTimeZone
[2020-12-30 03:25:08.406][b6ccf64c] IMAP[DATA]: < TAG7 OK Logout completed (0.001 + 0.000 secs).\r\n
[2020-12-30 03:25:08.407][b6ccf64c] PHP[NOTICE]: /usr/share/snappymail/snappymail/v/2.1.1/app/libraries/MailSo/Log/Driver.php [line:194, code:8]
[2020-12-30 03:25:08.407][b6ccf64c] PHP[NOTICE]: Error: Undefined property: MailSo\Log\Drivers\File::$DateTimeZone
[2020-12-30 03:25:08.407][b6ccf64c] IMAP[NOTE]: Disconnected from "ssl://domain.tld:993" (success)
[2020-12-30 03:25:08.408][b6ccf64c] PHP[NOTICE]: /usr/share/snappymail/snappymail/v/2.1.1/app/libraries/MailSo/Log/Driver.php [line:194, code:8]
[2020-12-30 03:25:08.408][b6ccf64c] PHP[NOTICE]: Error: Undefined property: MailSo\Log\Drivers\File::$DateTimeZone
[2020-12-30 03:25:08.408][b6ccf64c] INFO[MEMORY]: Memory peak usage: 4MB
[2020-12-30 03:25:08.408][b6ccf64c] PHP[NOTICE]: /usr/share/snappymail/snappymail/v/2.1.1/app/libraries/MailSo/Log/Driver.php [line:194, code:8]
[2020-12-30 03:25:08.409][b6ccf64c] PHP[NOTICE]: Error: Undefined property: MailSo\Log\Drivers\File::$DateTimeZone
[2020-12-30 03:25:08.409][b6ccf64c] INFO[TIME]: Time delta: 0.18784308433533
```

**Comment by the-djmaze** [comment]
Are you sure the settings are the same as with RainLoop?
Because the only way SnappyMail is slow, is when you use Argon2 encrypted passwords.
Else just put back the RainLoop data folder en only clear the `/data/_data_/_default_/cache/` folder.

**Comment by grawlinson** [comment]
I deleted rainloop before installing snappymail, so no settings were transferred over.

I've merged that commit into my snappymail instance and the logs have stopped filling up.

Interacted with sieve filters via web interface, no logs on server-side. There seems to be a few of these in dev console: `Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`. When editing a sieve filter, the "save" button has a loading animation that never stops and no actions/requests occur when the button is clicked.

**Comment by the-djmaze** [comment]
Great! The json syntaxerror says it all.
The server response has invalid data and should be inspected in the browser debugger.

I will improve the promise error handling, but you might be able to find the issue in the debugger or php error log.

**Comment by the-djmaze** [comment]
Are you able to test this new Filters editor?
https://snappymail.eu/demo/#/settings/filters

**Comment by the-djmaze** [comment]
Please try v2.2.1 if it solves your problem.
https://github.com/the-djmaze/snappymail/releases/tag/v2.2.1

**Comment by grawlinson** [comment]
Can't compile 2.2.0 or 2.2.1, errors out when executing `gulp snappymail`

```
[10:57:07] 'cssAdminBuild' errored after 355 ms
[10:57:07] Error: File not found with singular glob: /snappymail/dev/Styles/@Admin.less (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/snappymail/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:486:26)
    at Glob.emit (node:events:379:20)
    at Glob.EventEmitter.emit (node:domain:470:12)
    at Glob._finish (/snappymail/node_modules/glob/glob.js:197:8)
    at done (/snappymail/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/snappymail/node_modules/glob/glob.js:688:12)
    at /snappymail/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/snappymail/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/snappymail/node_modules/glob/glob.js:764:12)
[10:57:07] 'snappymail' errored after 1.67 s

```

**Comment by the-djmaze** [comment]
You are right!
That shouldn't be enabled yet. I was testing a split of app.css and admin.css without result.

B.t.w. `gulp snappymail` is broken due to replacing WebPack with Rollup, and i couldn't get gulp-rollup properly working yet.
Try with `./release.php`

**Comment by the-djmaze** [comment]
@grawlinson i made some changes to the release.php for you, regarding your AUR.
Use as: `php release.php --aur`

If you need more improvements we can update it

**Comment by grawlinson** [comment]
Thanks, I'll have a look at some point and get back to you 👍

**Comment by grawlinson** [comment]
I'm impressed with the performance improvements so far! 💯

**Comment by the-djmaze** [comment]
> I'm impressed with the performance improvements so far!

Thanks!
But i need to focus on testing because the speed of releases is to fast to properly test.
Atleast v2.3.1 is tested and bugfixed...

**Comment by ervee** [comment]
> But i need to focus on testing because the speed of releases is too fast to properly test.
> Atleast v2.3.1 is tested and bugfixed...

Perhaps do Beta releases to get feedback. I'm willing (and sometimes capable) of testing new releases with possible breaking changes :)
