### ISSUE TITLE
Cannot change password with plugin 

### ISSUE THREAD

**Issue by ffuentese** [the-djmaze/snappymail#526]
**SnappyMail version, browser, browser version:** 2.17.0 , Firefox 103.0.2, Host OpenBSD 7.1/OpenSMTPD (self-hosted in VPS) with MariaDB as db 

**Expected behavior and actual behavior:**
Installing change password plugin should allow password change for users. 
Actual behavior: Password change throws message that password couldn't be saved.

**Steps to reproduce the problem:**
Over configured snappymail install "Change Password" plugin, enable PDO, DSN and SQL sentence.  

**Logs or screenshots:**

php-fpm.log

```
doas tail -f php-fpm.log 
[20-Sep-2022 01:33:15] WARNING: [pool www] child 68575 said into stderr: "NOTICE: PHP message: PHP Notice:  ChangePasswordDriverpdo failed: UnknownNotification[130] in /htdocs/webmail/data/_data_/_default_/plugins/change-password/index.php on line 182"
[20-Sep-2022 01:33:15] WARNING: [pool www] child 68575 said into stderr: "NOTICE: PHP message: PHP Notice:  ChangePassword failed in /htdocs/webmail/data/_data_/_default_/plugins/change-password/index.php on line 193"
"20-Sep-2022 01:33:15] WARNING: [pool www] child 68575 said into stderr: "NOTICE: PHP message: SERVICE WARNING: UnknownNotification[130]
[20-Sep-2022 01:33:15] WARNING: [pool www] child 68575 said into stderr: "#0 /htdocs/webmail/snappymail/v/2.17.0/app/libraries/RainLoop/Plugins/Manager.php(405): ChangePasswordPlugin->ChangePassword()"
[20-Sep-2022 01:33:15] WARNING: [pool www] child 68575 said into stderr: "#1 /htdocs/webmail/snappymail/v/2.17.0/app/libraries/RainLoop/ServiceActions.php(161): RainLoop\Plugins\Manager->RunAdditionalJson()"
[20-Sep-2022 01:33:15] WARNING: [pool www] child 68575 said into stderr: "#2 /htdocs/webmail/snappymail/v/2.17.0/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()"
[20-Sep-2022 01:33:15] WARNING: [pool www] child 68575 said into stderr: "#3 /htdocs/webmail/snappymail/v/2.17.0/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()"

```

httpd php-fpm error.log
```

PHP message: SERVICE WARNING: Argument 1 passed to RainLoop\Actions::SetAuthToken() must be an instance of RainLoop\Model\MainAccount, instance of RainLoop\Model\AdditionalAccount given, called in /htdocs/webmail/data/_data_/_default_/plugins/change-password/index.php on line 198
#0 /htdocs/webmail/data/_data_/_default_/plugins/change-password/index.php(198): RainLoop\Actions->SetAuthToken()
#1 /htdocs/webmail/snappymail/v/2.17.0/app/libraries/RainLoop/Plugins/Manager.php(405): ChangePasswordPlugin->ChangePassword()
#2 /htdocs/webmail/snappymail/v/2.17.0/app/libraries/RainLoop/ServiceActions.php(161): RainLoop\Plugins\Manager->RunAdditionalJson()
#3 /htdocs/webmail/snappymail/v/2.17.0/app/libraries/RainLoop/Service.php(133): RainLoop\ServiceActions->ServiceJson()
#4 /htdocs/webmail/snappymail/v/2.17.0/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#5 /htdocs/webmail/snappymail/v/2.17.0/include.php(169): RainLoop\Service::Handle()
#6 /htdocs/webmail/index.php(11): include('/...
```

**Comment by the-djmaze** [comment]
Argument 1 passed to RainLoop\Actions::SetAuthToken() must be an
instance of RainLoop\Model\MainAccount,
instance of RainLoop\Model\AdditionalAccount given

This means that you are trying to change the password of an additional account.
I've fixed this to support it better.

**Comment by jerheij** [comment]
I just noticed I am having this problem as well, it shows the error above and an error in snappymail even though it changes the password successfully.

**Comment by the-djmaze** [comment]
> I just noticed I am having this problem as well, 

Then you didn't update the extensions. It is not possible anymore with latest releases

**Comment by jerheij** [comment]
My version of password changer shows as 2.20, is that not the latest?

**Comment by the-djmaze** [comment]
That is the latest, but then the "Argument 1 passed to RainLoop\Actions::SetAuthToken() must be an
instance of RainLoop\Model\MainAccount," error is not possible

**Comment by jerheij** [comment]
You're right, it's a slightly different error. It just looked similar. My bad! I will create a new issue.

Sorry!
