### ISSUE TITLE
CardDAV contacts synchronization error

### ISSUE THREAD

**Issue by dertinger** [the-djmaze/snappymail#674]
Despite the fix for the OpenSSL v3-related login issues (#641), CardDAV sync is still broken for OpenSSL reasons.

**To Reproduce**
1. Log in to an account for which CardDAV synchronisation has been set up (in my case with a Radicale server) 
2. Click on the icon in the top right corner
3. Click "Contacts"
4. The contacts from the local database appear 
5. Click "Synchronization (CardDAV)"
6. See "Contacts synchronization error"

**Expected behavior**
Local contacts are being synchronized with the CardDAV server as they used to before the OpenSSL issue.

**System information**
- PHP version: 8.1.12
- SnappyMail Version: 2.21.0, 2.21.1
- Radicale version: 3.1.8
- OpenSSL version: 3.0.7

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
```
[2022-11-13 21:12:34.521][5589861f] PHP-USER[NOTICE]: SnappyMail\Crypt::opensslDecrypt(): Control character error, possibly incorrectly encoded /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/snappymail/crypt.php [line:66, code:1024]
[2022-11-13 21:12:34.523][5589861f] PdoAddressBook[WARNING]: Sync() invalid DavClient
[2022-11-13 21:12:34.523][5589861f] SERVICE[WARNING]: ContactsSyncError[140]
#0 /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoContactsSync()
#1 /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson()
#2 /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#3 /usr/share/snappymail/snappymail/v/2.21.0/include.php(167): RainLoop\Service::Handle()
#4 /usr/share/snappymail/index.php(11): include('...')
#5 {main}
[2022-11-13 21:12:34.523][5589861f] [NOTICE]: RainLoop\Exceptions\ClientException: ContactsSyncError[140] in /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/RainLoop/Actions/Contacts.php:44
Stack trace:
#0 /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoContactsSync()
#1 /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson()
#2 /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#3 /usr/share/snappymail/snappymail/v/2.21.0/include.php(167): RainLoop\Service::Handle()
#4 /usr/share/snappymail/index.php(11): include('...')
#5 {main}
[2022-11-13 21:12:34.523][5589861f] [ERROR]: RainLoop\Exceptions\ClientException: ContactsSyncError[140] in /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/RainLoop/Actions/Contacts.php:44
Stack trace:
#0 /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoContactsSync()
#1 /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson()
#2 /usr/share/snappymail/snappymail/v/2.21.0/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#3 /usr/share/snappymail/snappymail/v/2.21.0/include.php(167): RainLoop\Service::Handle()
#4 /usr/share/snappymail/index.php(11): include('...')
#5 {main}
```

**Comment by the-djmaze** [comment]
Probably same issue as #653

`SnappyMail\Crypt::opensslDecrypt(): Control character error, possibly incorrectly encoded`

1. Remove your CardDAV password
2. Put back your CardDAV password

Now it should be saved properly
