### ISSUE TITLE
401 Unauthorized on CardDav synchronisation (nextcloud)

### ISSUE THREAD

**Issue by Nono-m0le** [the-djmaze/snappymail#680]
**Describe the bug**
The bug is similar as  #653 but I didn't wanted to high-jack the thread.

**To Reproduce**

    got to the contact view
    open the burger menu
    click on Synchronization (CardDav)

**Expected behavior**
Get the contact synced

**Please complete the following information:**
- Browser: FireFox 106
- PHP version: 7.4.30
- SnappyMail Version: 2.21.2

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
```
[2022-11-16 22:33:54.422][80e1fe72] [INFO]: [SM:2.21.2][IP:X.X.X.X][PID:2875574][nginx/1.18.0][fpm-fcgi][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3][GET https://mail.domain.tld/?/Json/&q[]=/0/ContactsSync]
[2022-11-16 22:33:54.423][80e1fe72] JSON[INFO]: Action: DoContactsSync
[2022-11-16 22:33:54.439][80e1fe72] SQL[INFO]: SELECT MAX(value_int) FROM rainloop_system WHERE sys_name = ?
[2022-11-16 22:33:54.440][80e1fe72] SQL[INFO]: SELECT id_user FROM rainloop_users WHERE rl_email = :rl_email
[2022-11-16 22:33:54.442][80e1fe72] DAV[INFO]: DavClient: User: nono@domain.tld, Url: https://cloud.domain.tld/remote.php/dav/addressbooks/users/nono/contacts/
[2022-11-16 22:33:54.442][80e1fe72] DAV[INFO]: PROPFIND /remote.php/dav/addressbooks/users/nono/contacts/
[2022-11-16 22:34:09.680][80e1fe72] [NOTICE]: SnappyMail\HTTP\Exception: 401 Unauthorized: PROPFIND https://cloud.domain.tld/remote.php/dav/addressbooks/users/nono/contacts/ in /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/snappymail/dav/client.php:83
Stack trace:
#0 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/snappymail/dav/client.php(127): SnappyMail\DAV\Client->request()
#1 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook/CardDAV.php(346): SnappyMail\DAV\Client->propFind()
#2 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook/CardDAV.php(446): RainLoop\Providers\AddressBook\PdoAddressBook->checkContactsPath()
#3 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(138): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient()
#4 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook.php(30): RainLoop\Providers\AddressBook\PdoAddressBook->Sync()
#5 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Actions/Contacts.php(43): RainLoop\Providers\AddressBook->Sync()
#6 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoContactsSync()
#7 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson()
#8 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#9 /var/www/html/webmail/snappymail/v/2.21.2/include.php(167): RainLoop\Service::Handle()
#10 /var/www/html/webmail/index.php(11): include('/var/www/html/w...')
#11 {main}
[2022-11-16 22:34:09.680][80e1fe72] DAV[INFO]: PROPFIND /.well-known/carddav
[2022-11-16 22:34:09.748][80e1fe72] PHP-USER[NOTICE]: Redirect https://cloud.domain.tld/.well-known/carddav to https://cloud.domain.tld/remote.php/dav/ /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/snappymail/dav/client.php [line:76, code:1024]
[2022-11-16 22:34:24.979][80e1fe72] [NOTICE]: SnappyMail\HTTP\Exception: 401 Unauthorized: PROPFIND https://cloud.domain.tld/remote.php/dav/ in /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/snappymail/dav/client.php:83
Stack trace:
#0 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/snappymail/dav/client.php(127): SnappyMail\DAV\Client->request()
#1 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook/CardDAV.php(149): SnappyMail\DAV\Client->propFind()
#2 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook/CardDAV.php(171): RainLoop\Providers\AddressBook\PdoAddressBook->detectionPropFind()
#3 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook/CardDAV.php(450): RainLoop\Providers\AddressBook\PdoAddressBook->getContactsPaths()
#4 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(138): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient()
#5 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook.php(30): RainLoop\Providers\AddressBook\PdoAddressBook->Sync()
#6 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Actions/Contacts.php(43): RainLoop\Providers\AddressBook->Sync()
#7 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoContactsSync()
#8 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson()
#9 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#10 /var/www/html/webmail/snappymail/v/2.21.2/include.php(167): RainLoop\Service::Handle()
#11 /var/www/html/webmail/index.php(11): include('/var/www/html/w...')
#12 {main}
[2022-11-16 22:34:24.980][80e1fe72] [INFO]: Array
(
)

[2022-11-16 22:34:24.980][80e1fe72] DAV[INFO]: PROPFIND 
[2022-11-16 22:34:25.053][80e1fe72] [NOTICE]: SnappyMail\HTTP\Exception: 405 Method Not Allowed: PROPFIND https://cloud.domain.tld
<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html> in /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/snappymail/dav/client.php:83
Stack trace:
#0 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/snappymail/dav/client.php(127): SnappyMail\DAV\Client->request()
#1 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook/CardDAV.php(346): SnappyMail\DAV\Client->propFind()
#2 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook/CardDAV.php(496): RainLoop\Providers\AddressBook\PdoAddressBook->checkContactsPath()
#3 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(138): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient()
#4 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Providers/AddressBook.php(30): RainLoop\Providers\AddressBook\PdoAddressBook->Sync()
#5 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Actions/Contacts.php(43): RainLoop\Providers\AddressBook->Sync()
#6 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoContactsSync()
#7 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson()
#8 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#9 /var/www/html/webmail/snappymail/v/2.21.2/include.php(167): RainLoop\Service::Handle()
#10 /var/www/html/webmail/index.php(11): include('/var/www/html/w...')
#11 {main}
[2022-11-16 22:34:25.054][80e1fe72] PdoAddressBook[WARNING]: Sync() invalid DavClient
[2022-11-16 22:34:25.054][80e1fe72] SERVICE[WARNING]: ContactsSyncError[140]
#0 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoContactsSync()
#1 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson()
#2 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#3 /var/www/html/webmail/snappymail/v/2.21.2/include.php(167): RainLoop\Service::Handle()
#4 /var/www/html/webmail/index.php(11): include('/var/www/html/w...')
#5 {main}
[2022-11-16 22:34:25.054][80e1fe72] [NOTICE]: RainLoop\Exceptions\ClientException: ContactsSyncError[140] in /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Actions/Contacts.php:44
Stack trace:
#0 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoContactsSync()
#1 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson()
#2 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#3 /var/www/html/webmail/snappymail/v/2.21.2/include.php(167): RainLoop\Service::Handle()
#4 /var/www/html/webmail/index.php(11): include('/var/www/html/w...')
#5 {main}
[2022-11-16 22:34:25.055][80e1fe72] [ERROR]: RainLoop\Exceptions\ClientException: ContactsSyncError[140] in /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Actions/Contacts.php:44
Stack trace:
#0 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\Actions->DoContactsSync()
#1 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson()
#2 /var/www/html/webmail/snappymail/v/2.21.2/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
#3 /var/www/html/webmail/snappymail/v/2.21.2/include.php(167): RainLoop\Service::Handle()
#4 /var/www/html/webmail/index.php(11): include('/var/www/html/w...')
#5 {main}
[2022-11-16 22:34:25.055][80e1fe72] JSON[INFO]: {"Action":"ContactsSync","Result":false,"ErrorCode":140,"ErrorMessage":"","ErrorMessageAdditional":"","Time":30638}
[2022-11-16 22:34:25.056][80e1fe72] [INFO]: Memory peak usage: 2MB
[2022-11-16 22:34:25.056][80e1fe72] [INFO]: Time delta: 30.640661001205
```
nginx log are a bit smaller, but less useful I guess : 
```
X.X.X.X - - [16/Nov/2022:23:28:56 +0100] "PROPFIND /remote.php/dav/addressbooks/users/nono/contacts/ HTTP/2.0" 401 450 "-" "SnappyMail/2.21.2"
X.X.X.X - nono@domain.tld [16/Nov/2022:23:29:11 +0100] "PROPFIND /remote.php/dav/addressbooks/users/nono/contacts/ HTTP/2.0" 499 0 "-" "SnappyMail/2.21.2"
X.X.X.X - - [16/Nov/2022:23:29:11 +0100] "PROPFIND /.well-known/carddav HTTP/2.0" 301 169 "-" "SnappyMail/2.21.2"
X.X.X.X - - [16/Nov/2022:23:29:12 +0100] "PROPFIND /remote.php/dav/ HTTP/2.0" 401 450 "-" "SnappyMail/2.21.2"
X.X.X.X - nono@domain.tld [16/Nov/2022:23:29:27 +0100] "PROPFIND /remote.php/dav/ HTTP/2.0" 499 0 "-" "SnappyMail/2.21.2"
X.X.X.X - - [16/Nov/2022:23:29:27 +0100] "PROPFIND / HTTP/2.0" 405 157 "-" "SnappyMail/2.21.2"
```
**Additional context**
I did a refresh, remove the password and add it back etc ...

**Comment by the-djmaze** [comment]
I've tested this and made changes to the code.

It works with my Nextcloud 25 and i don't get `401 Unauthorized`, so i've improved the debug logging for next release.
That should get you started why yours is failing.

**Comment by Nono-m0le** [comment]
Can I already check without installing NC 25 ? One of my app (Carnet) isn't compatible, so I "can't" upgrade yet.

**Comment by the-djmaze** [comment]
Here you go https://github.com/the-djmaze/snappymail/releases/tag/v2.21.3

**Comment by Nono-m0le** [comment]
Well, I have now quite some of [Object Object] (but with correct email address), so I assume it works now. Thanks !

**Comment by the-djmaze** [comment]
`[Object Object]` is a bug where a vCard has email address but no (full) name

**Comment by Nono-m0le** [comment]
Does it commes from NextCloud or Snappy ?
If possible, I would put the entry into the (full) name ie:
If only email => full name == email
if only phone number => Full name == phone number

**Comment by the-djmaze** [comment]
Fixed for next release
https://github.com/the-djmaze/snappymail/commit/7e1b85d0236d13a2671fcc964cbf44b8e5aee740

**Comment by Nono-m0le** [comment]
well.
"I like it when the plan comes together" ! 
Thanks !

**Comment by the-djmaze** [comment]
> "I like it when the plan comes together" !

So sad he is dead. Atleast BA Baracus is still alive to create things with a welding torch.
