### ISSUE TITLE
Can't login (Unsupported SASL mechanism type)

### ISSUE THREAD

**Issue by ervee** [the-djmaze/snappymail#73]
**Describe the bug**
Can't login after update from 2.4.1 top 2.4.3.

**To Reproduce**
1. Have a working 2.4.1 setup
2. Update to 2.4.3
3. Try to login.
At least for me :)

**Expected behavior**
Just login.

**Screenshots**
Not of any help. I have logs though:
```
--- FlushLogCache: WriteOnErrorOnly
[2021-03-31 08:04:12.641][cbddd423] INFO[DATA]: [DATE:2021-03-31 UTC][RL:2.4.3][PHP:7.3.27-9+0~20210227.82+debian9~1.gbpa4a3d6][IP:192.168.2.12][PID:1068][nginx/1.18.0][fpm-fcgi]
[2021-03-31 08:04:12.641][cbddd423] INFO[DATA]: [APC:on][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[2021-03-31 08:04:12.641][cbddd423] REQUEST[NOTE]: [POST] https://###myhosting.domain###/webmail/snappymail/?/Json/&q[]=/_bP9..snip..GAg/
[2021-03-31 08:04:12.642][cbddd423] JSON[NOTE]: Action: DoLogin
[2021-03-31 08:04:12.642][cbddd423] POST[DATA]: {"Email":"###myemailadres###","Login":"","Password":"*******","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0","SignMe":"0","Action":"Login","XToken":"cc..snip..e8"}
[2021-03-31 08:04:12.642][cbddd423] PLUGIN[NOTE]: Hook: filter.login-credentials
[2021-03-31 08:04:12.647][cbddd423] IMAP[NOTE]: Start connection to "tcp://localhost:1143"
[2021-03-31 08:04:12.647][cbddd423] IMAP[NOTE]: Connected (success)
[2021-03-31 08:04:12.648][cbddd423] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ LOGIN-REFERRALS ID ENABLE XIMAPPROXY] Dovecot ready.

--- FlushLogCache: Trigger
[2021-03-31 08:04:15.649][cbddd423] INFO[NOTICE]: Exception: Unsupported SASL mechanism type:  in /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/snappymail/sasl.php:30
Stack trace:
#0 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/MailSo/Imap/ImapClient.php(181): SnappyMail\SASL::factory('')
#1 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/MailSo/Mail/MailClient.php(63): MailSo\Imap\ImapClient->Login('###myloginuseraccount###', '*******', '', true, false)
#2 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Model/Account.php(313): MailSo\Mail\MailClient->Login('###myloginuseraccount###', '*******', '', true, false)
#3 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Actions.php(1394): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application))
#4 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Actions.php(1585): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#5 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Actions/User.php(48): RainLoop\Actions->LoginProcess('###myemailadres###', '*******', '', '', false)
#6 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoLogin()
#7 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Service.php(135): RainLoop\ServiceActions->ServiceJson('')
#8 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Service.php(64): RainLoop\Service->localHandle()
#9 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Service.php(80): RainLoop\Service->__construct()
#10 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/handle.php(57): RainLoop\Service::Handle()
#11 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/include.php(246): include('/srv/www/vhosts...')
#12 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/index.php(12): include('/srv/www/vhosts...')
#13 {main}
[2021-03-31 08:04:15.653][cbddd423] INFO[ERROR]: Exception: Unsupported SASL mechanism type:  in /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/snappymail/sasl.php:30
Stack trace:
#0 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/MailSo/Imap/ImapClient.php(181): SnappyMail\SASL::factory('')
#1 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/MailSo/Mail/MailClient.php(63): MailSo\Imap\ImapClient->Login('###myloginuseraccount###', '*******', '', true, false)
#2 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Model/Account.php(313): MailSo\Mail\MailClient->Login('###myloginuseraccount###', '*******', '', true, false)
#3 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Actions.php(1394): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application))
#4 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Actions.php(1585): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#5 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Actions/User.php(48): RainLoop\Actions->LoginProcess('###myemailadres###', '*******', '', '', false)
#6 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoLogin()
#7 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Service.php(135): RainLoop\ServiceActions->ServiceJson('')
#8 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Service.php(64): RainLoop\Service->localHandle()
#9 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Service.php(80): RainLoop\Service->__construct()
#10 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/handle.php(57): RainLoop\Service::Handle()
#11 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/include.php(246): include('/srv/www/vhosts...')
#12 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/index.php(12): include('/srv/www/vhosts...')
#13 {main}

Next RainLoop\Exceptions\ClientException: AuthError[102] in /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Actions.php:1411
Stack trace:
#0 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Actions.php(1585): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#1 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Actions/User.php(48): RainLoop\Actions->LoginProcess('###myemailadres###', '*******', '', '', false)
#2 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoLogin()
#3 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Service.php(135): RainLoop\ServiceActions->ServiceJson('')
#4 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Service.php(64): RainLoop\Service->localHandle()
#5 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/libraries/RainLoop/Service.php(80): RainLoop\Service->__construct()
#6 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/app/handle.php(57): RainLoop\Service::Handle()
#7 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/snappymail/v/2.4.3/include.php(246): include('/srv/www/vhosts...')
#8 /srv/www/vhosts/###myhosting.domain###/path/to/snappymail/index.php(12): include('/srv/www/vhosts...')
#9 {main}
[2021-03-31 08:04:15.656][cbddd423] JSON[DATA]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":3071}
[2021-03-31 08:04:15.658][cbddd423] INFO[MEMORY]: Memory peak usage: 2MB
[2021-03-31 08:04:15.660][cbddd423] INFO[TIME]: Time delta: 3.0761299133301
[2021-03-31 08:04:15.661][cbddd423] IMAP[NOTE]: Disconnected from "tcp://localhost:1143" (success)
```
Note 1: I use a plain text IMAP Proxy (which talks TLS to a remote Dovecot IMAP Server.
Note 2: I use the login mapping plugin to map login e-mail to user account for that login.

**Desktop (please complete the following information):**
 - Browser: Firefox 87.0 64bit on Windows 10 20H2
 - SnappyMail Version 2.4.3

**Additional context**
Perhaps to do with the commit https://github.com/the-djmaze/snappymail/commit/389e473e221c01c4e8248a5c6c8b39272da53af3 ?

**Comment by the-djmaze** [comment]
The system is now very strict when it comes to login.
When you connect it looks for AUTH= rules in response, but your server response:
`OK [CAPABILITY IMAP4rev1 LITERAL+ LOGIN-REFERRALS ID ENABLE XIMAPPROXY]`

Here are some tests i made on my server.
See the AUTH= rules on different connections.
Tests with `mail.example.com` are remote and not local tests.

```
telnet localhost 143
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
```

```
telnet mail.example.com 143
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready.
```

```
openssl s_client -starttls imap -connect mail.example.com:143
CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN
```

```
openssl s_client -connect mail.example.com:993
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
```

**Comment by the-djmaze** [comment]
Seems that LOGIN should be always available UNLESS the LOGINDISABLED is advertised.
https://tools.ietf.org/html/rfc3501#section-6.2.3

So i've added the missing check for LOGINDISABLED as well
https://github.com/the-djmaze/snappymail/commit/bb836fdb59983c927da6506d69d6de2cf8d3addf

**Comment by ervee** [comment]
Works as a charm via ImapProxy again!
