### ISSUE TITLE
Setting up GMX: "SSL Handshake timed out" / "Cannot enable STARTTLS"

### ISSUE THREAD

**Issue by CountCypher** [the-djmaze/snappymail#743]
**Describe the bug**
When I enter the Domain details for the German email provider GMX in the Admin panel and test the connection, I receive an "SSL Handshake timed out" / "Cannot enable STARTTLS" error.

**To Reproduce**
1. Go to Admin Panel > Domains
2. Add new Domain "gmx.net" with the server settings mentioned in [their online help](https://hilfe.gmx.net/pop-imap/imap/imap-serverdaten.html#p=1&q=Serverdaten%20f%C3%BCr%20IMAP%20und%20SMTP).
3. Click "Test"
4. Error "SSL Handshake timed out" is shown when button "Test" is clicked from "IMAP" tab and error "Cannot enable STARTTLS" is shown when button "Test" is clicked from "SMTP" tab (see screenshots below)

**Expected behavior**
Successful connection.

**Screenshots**
![image](https://user-images.githubusercontent.com/54265000/205444644-900a327c-b0ef-4be6-a0b0-b40ffe9763f8.png)
![image](https://user-images.githubusercontent.com/54265000/205444765-3e9597c5-e2f1-4035-acd3-820cd49c3e7d.png)

- Browser: LibreWolf 107 (Firefox fork)
- IMAP daemon: Don't know which one GMX is using.
- PHP version: 8.1.6
- SnappyMail Version: 2.22.5 (Docker image fffrantz/snappymail)

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
```
snappymail    | [2022-12-03 14:01:02.532][5b1a2e04] [ERROR]: MailSo\Net\Exceptions\SocketCanNotConnectToHostException: Can't connect to host "ssl://imap.gmx.net:993" in /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Net/NetClient.php:189
snappymail    | Stack trace:
snappymail    | #0 /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Imap/ImapClient.php(94): MailSo\Net\NetClient->Connect(Object(MailSo\Imap\Settings))
snappymail    | #1 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/ActionsAdmin.php(298): MailSo\Imap\ImapClient->Connect(Object(MailSo\Imap\Settings))
snappymail    | #2 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\ActionsAdmin->DoAdminDomainTest()
snappymail    | #3 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson('')
snappymail    | #4 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
snappymail    | #5 /snappymail/snappymail/v/2.22.5/include.php(169): RainLoop\Service::Handle()
snappymail    | #6 /snappymail/index.php(11): include('/snappymail/sna...')
snappymail    | #7 {main}
snappymail    | [2022-12-03 14:01:07.597][5b1a2e04] PHP[WARNING]: stream_socket_enable_crypto(): SSL: Handshake timed out /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Net/NetClient.php [line:222, code:2]
snappymail    | [03-Dec-2022 14:01:07] WARNING: [pool default] child 107 said into stderr: "[03-Dec-2022 14:01:07 UTC] PHP Warning:  stream_socket_enable_crypto(): SSL: Handshake timed out in /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Net/NetClient.php on line 222"
snappymail    | [2022-12-03 14:01:07.598][5b1a2e04] SMTP[ERROR]: MailSo\RuntimeException: Cannot enable STARTTLS. in /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Net/NetClient.php:229
snappymail    | Stack trace:
snappymail    | #0 /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Smtp/SmtpClient.php(125): MailSo\Net\NetClient->EnableCrypto()
snappymail    | #1 /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Smtp/SmtpClient.php(117): MailSo\Smtp\SmtpClient->StartTLS()
snappymail    | #2 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/ActionsAdmin.php(341): MailSo\Smtp\SmtpClient->Connect(Object(MailSo\Smtp\Settings), '[192.168.178.62...')
snappymail    | #3 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\ActionsAdmin->DoAdminDomainTest()
snappymail    | #4 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson('')
snappymail    | #5 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
snappymail    | #6 /snappymail/snappymail/v/2.22.5/include.php(169): RainLoop\Service::Handle()
snappymail    | #7 /snappymail/index.php(11): include('/snappymail/sna...')
snappymail    | #8 {main}
snappymail    | [2022-12-03 14:01:07.598][5b1a2e04] [ERROR]: MailSo\RuntimeException: Cannot enable STARTTLS. in /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Net/NetClient.php:229
snappymail    | Stack trace:
snappymail    | #0 /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Smtp/SmtpClient.php(125): MailSo\Net\NetClient->EnableCrypto()
snappymail    | #1 /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Smtp/SmtpClient.php(117): MailSo\Smtp\SmtpClient->StartTLS()
snappymail    | #2 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/ActionsAdmin.php(341): MailSo\Smtp\SmtpClient->Connect(Object(MailSo\Smtp\Settings), '[192.168.178.62...')
snappymail    | #3 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/ServiceActions.php(155): RainLoop\ActionsAdmin->DoAdminDomainTest()
snappymail    | #4 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson('')
snappymail    | #5 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
snappymail    | #6 /snappymail/snappymail/v/2.22.5/include.php(169): RainLoop\Service::Handle()
snappymail    | #7 /snappymail/index.php(11): include('/snappymail/sna...')
snappymail    | #8 {main}
snappymail    | [2022-12-03 14:01:07.599][5b1a2e04] SMTP[ERROR]: Stream Meta: Array
snappymail    | (
snappymail    |     [timed_out] => 
snappymail    |     [blocked] => 
snappymail    |     [eof] => 
snappymail    |     [stream_type] => tcp_socket/ssl
snappymail    |     [mode] => r+
snappymail    |     [unread_bytes] => 0
snappymail    |     [seekable] => 
snappymail    | )
snappymail    | 
snappymail    | [2022-12-03 14:01:07.600][5b1a2e04] SMTP[ERROR]: MailSo\Net\Exceptions\SocketReadException in /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Net/NetClient.php:366
snappymail    | Stack trace:
snappymail    | #0 /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Smtp/SmtpClient.php(576): MailSo\Net\NetClient->getNextBuffer()
snappymail    | #1 /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Smtp/SmtpClient.php(481): MailSo\Smtp\SmtpClient->validateResponse(Array, '')
snappymail    | #2 /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Smtp/SmtpClient.php(440): MailSo\Smtp\SmtpClient->sendRequestWithCheck('QUIT', 221)
snappymail    | #3 /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Net/NetClient.php(244): MailSo\Smtp\SmtpClient->Logout()
snappymail    | #4 /snappymail/snappymail/v/2.22.5/app/libraries/MailSo/Net/NetClient.php(84): MailSo\Net\NetClient->Disconnect()
snappymail    | #5 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/ServiceActions.php(155): MailSo\Net\NetClient->__destruct()
snappymail    | #6 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(123): RainLoop\ServiceActions->ServiceJson('')
snappymail    | #7 /snappymail/snappymail/v/2.22.5/app/libraries/RainLoop/Service.php(15): RainLoop\Service::RunResult()
snappymail    | #8 /snappymail/snappymail/v/2.22.5/include.php(169): RainLoop\Service::Handle()
snappymail    | #9 /snappymail/index.php(11): include('/snappymail/sna...')
snappymail    | #10 {main}
```
**Additional information**
I have SnappyMail 2.19.7 (PHP 7.3.31-1) running on another server "natively" (i.e., not as a Docker container). On that server connection to GMX works fine.

**Comment by the-djmaze** [comment]
> I have SnappyMail 2.19.7 (PHP 7.3.31-1) running on another server "natively" (i.e., not as a Docker container). On that server connection to GMX works fine.

Check your docker firewall

**Comment by CountCypher** [comment]
> Check your docker firewall

Thanks for the super quick reply. :) I forgot to mention one important thing: In that same SnappyMail instance I could setup two other mail providers without an issue (mailbox.org and dismail.de). The only difference I can see to GMX: The other two providers use STARTTLS for both IMAP and SMTP. So you believe it's a problem with the Docker firewall preventing connection to port 993?

**Comment by CountCypher** [comment]
Your hint has steered me into the right direction:
The Docker host was connected via Wireguard VPN to a VPS while I was testing this. Once I disconnected the VPN, setup of GMX in SnappyMail worked fine. Thanks again for the quick help and your great work on this project! :)

**Comment by the-djmaze** [comment]
Good you found the problem
