### ISSUE TITLE
CardDAV sync does not work

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#79]
**Describe the bug**
CardDAV sync does not work

**To Reproduce**
1. Enable CardDAV synchronization in settings.
2. Force synchronization.
3. Error appears.

**Expected behavior**
Contacts are synchronised and stored in the database.

**Desktop (please complete the following information):**
Browser: Google Chrome 89, 64-bit
SnappyMail: 2.5.0-RC1

**Additional context**
[error.log](https://github.com/the-djmaze/snappymail/files/6283593/error.log)

**Comment by the-djmaze** [comment]
It crashes on the redirect
```
PROPFIND /.well-known/carddav
SnappyMail\HTTP\Exception: 301 Moved Permanently
```
I've modified the dav client to log where it wants to go.
Currently i've disabled redirects for security reasons.

**Comment by phsc84** [comment]
It would be great if you could allow that, because I've tried to sync with Nextcloud and Nextcloud shows a warning, if well-known/carddav is not configured.
See here for more details: https://docs.nextcloud.com/server/21/admin_manual/issues/general_troubleshooting.html#service-discovery

**Comment by the-djmaze** [comment]
I've set the max redirects to 1 for this case.
Try with these two files:
https://github.com/the-djmaze/snappymail/blob/4ee905c5684f1400b117c61a1480186712113f8f/snappymail/v/0.0.0/app/libraries/snappymail/dav/client.php
https://github.com/the-djmaze/snappymail/blob/4ee905c5684f1400b117c61a1480186712113f8f/snappymail/v/0.0.0/app/libraries/snappymail/http/request.php

**Comment by the-djmaze** [comment]
Modified to secure it to same host

**Comment by phsc84** [comment]
Ok, great! I would be happy to test again (but only in the evening), if you could build an RC2.

**Comment by the-djmaze** [comment]
Thanks! I will create RC2

**Comment by phsc84** [comment]
Just tested the RC2. Now I get the following error:
[2021-04-09 19:10:34.128][4d975b5f] INFO[NOTICE]: Error: Call to undefined method SnappyMail\HTTP\Exception::getHeader() in /home/httpd/vhosts/url.com/httpdocs/apps/mail2/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/http/exception.php:74

**Comment by phsc84** [comment]
I've just applied your patch and now get the following error:
[2021-04-10 16:58:45.359][8c2dedb9] INFO[NOTICE]: SnappyMail\HTTP\Exception: 405 Method Not Allowed in /home/httpd/vhosts/url.com/httpdocs/apps/mail2/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php:125

**Comment by ervee** [comment]
I'm getting this:
```
[2021-04-11 14:52:08.421][fb364ba9] REQUEST[NOTE]: [POST] https://mydomain.tld/webmail/snappymail/?/Json/&q[]=/_hrs[...snip...]MZw/
[2021-04-11 14:52:08.428][fb364ba9] DAV[DATA]: DavClient: User: myuseraccount, Url: https://mydomain.tld/cloud/remote.php/dav/addressbooks/users/myuseraccount/contacts/
[2021-04-11 14:52:08.428][fb364ba9] DAV[DATA]: PROPFIND /cloud/remote.php/dav/addressbooks/users/myuseraccount/contacts/
[2021-04-11 14:52:09.008][fb364ba9] PHP[NOTICE]: /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php [line:142, code:2]
[2021-04-11 14:52:09.009][fb364ba9] PHP[NOTICE]: /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php [line:142, code:2]
[2021-04-11 14:52:09.009][fb364ba9] PHP[NOTICE]: Error: simplexml_load_string(): t&gt;&lt;/d:response&gt;&lt;d:response&gt;&lt;d:href&gt;/cloud/remote.php/dav/addressbooks/users/myuse
[2021-04-11 14:52:09.010][fb364ba9] PHP[NOTICE]: /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php [line:142, code:2]
[2021-04-11 14:52:09.010][fb364ba9] PHP[NOTICE]: /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php [line:142, code:2]
[2021-04-11 14:52:09.010][fb364ba9] PHP[NOTICE]: /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php [line:142, code:2]
[2021-04-11 14:52:09.011][fb364ba9] PHP[NOTICE]: Error: simplexml_load_string(): t&gt;&lt;/d:response&gt;&lt;d:response&gt;&lt;d:href&gt;/cloud/remote.php/dav/addressbooks/users/myuse
[2021-04-11 14:52:09.011][fb364ba9] PHP[NOTICE]: /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php [line:142, code:2]
[2021-04-11 14:52:09.011][fb364ba9] PHP[NOTICE]: /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php [line:142, code:2]
[2021-04-11 14:52:09.012][fb364ba9] PHP[NOTICE]: /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php [line:142, code:2]
[2021-04-11 14:52:09.012][fb364ba9] PHP[NOTICE]: Error: simplexml_load_string(): t&gt;&lt;/d:response&gt;&lt;d:response&gt;&lt;d:href&gt;/cloud/remote.php/dav/addressbooks/users/myuse
[2021-04-11 14:52:09.012][fb364ba9] PHP[NOTICE]: /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php [line:142, code:2]
[2021-04-11 14:52:09.013][fb364ba9] INFO[NOTICE]: InvalidArgumentException: The passed data is not valid XML in /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php:145
#0 /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(438): SnappyMail\DAV\Client->propFind('https://mydomai...', Array, 1)
#1 /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(536): RainLoop\Providers\AddressBook\PdoAddressBook->checkContactsPath(Object(SnappyMail\DAV\Client), '/cloud/remote.p...')
#2 /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(602): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient('https://mydomai...', 'myuseraccount', '*******', '')
[2021-04-11 14:52:09.013][fb364ba9] DAV[DATA]: PROPFIND /.well-known/carddav
[2021-04-11 14:52:09.027][fb364ba9] INFO[NOTICE]: SnappyMail\HTTP\Exception: 404 Not Found in /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php:125
#0 /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(231): SnappyMail\DAV\Client->propFind('https://mydomai...', Array, 1)
#1 /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(253): RainLoop\Providers\AddressBook\PdoAddressBook->detectionPropFind(Object(SnappyMail\DAV\Client), '/.well-known/ca...')
#2 /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(540): RainLoop\Providers\AddressBook\PdoAddressBook->getContactsPaths(Object(SnappyMail\DAV\Client), 'myuseraccount', '*******', '')
#3 /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(602): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient('https://mydomai...', 'myuseraccount', '*******', '')
[2021-04-11 14:52:09.027][fb364ba9] DAV[DATA]: PROPFIND
#0 /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/snappymail/dav/client.php(125): SnappyMail\HTTP\Exception->__construct('', 405, Object(SnappyMail\HTTP\Response))
#1 /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(438): SnappyMail\DAV\Client->propFind('https://mydomai...', Array, 1)
#2 /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(586): RainLoop\Providers\AddressBook\PdoAddressBook->checkContactsPath(Object(SnappyMail\DAV\Client), '')
#3 /myinstallpathtosnappymail/snappymail/v/2.5.0-rc.2/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(602): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient('https://mydomai...', 'myuseraccount', '*******', '')
```

Also, the "hamburger" icon changes to a line and spins out of its designated area :)

![image](https://user-images.githubusercontent.com/4435930/114308952-c9dfae80-9ae5-11eb-85f2-40051476c2cf.png)

**Comment by the-djmaze** [comment]
This is annoying.
`405 Method Not Allowed` should respond with an `Allow` header to notify the client which methods are allowed.

PROPFIND is not allowed so i'm clueless what is allowed.

So i've made a change to see if that improves logging.

**Comment by the-djmaze** [comment]
I did a test on https://demo2.nextcloud.com
```
PROPFIND /remote.php/dav/addressbooks/users/ HTTP/1.1
Host: demo2.nextcloud.com
User-Agent: SnappyMail/1.0
Connection: Close
Depth: 1
Content-Type: application/xml
Authorization: Basic UjM3ZHg5VGVtbzlQY0RjQTpkZW1v
Content-Length: 109
```

Response is:
```
HTTP/1.1 405 Method Not Allowed
Allow: OPTIONS, GET, HEAD, DELETE, PROPFIND, PUT, PROPPATCH, COPY, MOVE, REPORT
```
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\MethodNotAllowed</s:exception>
  <s:message>Listing members of this collection is disabled</s:message>
</d:error>
```

So i'm improving error logging for this behaviour

**Comment by ervee** [comment]
RC3 logs:
```
--- FlushLogCache: WriteOnErrorOnly
[2021-04-13 14:53:26.214][69a934c1] INFO[DATA]: [DATE:2021-04-13 UTC][RL:2.5.0-rc.3][PHP:7.3.27-9+0~20210227.82+debian9~1.gbpa4a3d6][IP:212.61.12.100][PID:9509][nginx/1.18.0][fpm-fcgi]
[2021-04-13 14:53:26.215][69a934c1] INFO[DATA]: [APC:on][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[2021-04-13 14:53:26.215][69a934c1] REQUEST[NOTE]: [POST] https://mydomain.tld/webmail/snappymail/?/Json/&q[]=/_9bS[...snip..]TAZ/
[2021-04-13 14:53:26.215][69a934c1] JSON[NOTE]: Action: DoContactsSync
[2021-04-13 14:53:26.215][69a934c1] POST[DATA]: {"Action":"ContactsSync","XToken":"0a9be594e61eec623bc2fb0608262272"}
[2021-04-13 14:53:26.219][69a934c1] SQL[DATA]: SELECT value_int FROM rainloop_system WHERE sys_name = ?
[2021-04-13 14:53:26.219][69a934c1] SQL[DATA]: SELECT id_user FROM rainloop_users WHERE rl_email = :rl_email
[2021-04-13 14:53:26.220][69a934c1] DAV[DATA]: DavClient: User: myusername, Url: https://mydomain.tld/cloud/remote.php/dav/addressbooks/users/myusername/contacts/
[2021-04-13 14:53:26.220][69a934c1] DAV[DATA]: PROPFIND /cloud/remote.php/dav/addressbooks/users/myusername/contacts/
[2021-04-13 14:53:26.784][69a934c1] DAV[DATA]: PROPFIND /.well-known/carddav
--- FlushLogCache: Trigger
[2021-04-13 14:53:26.796][69a934c1] INFO[NOTICE]: SnappyMail\HTTP\Exception: 404 Not Found: PROPFIND https://mydomain.tld/.well-known/carddav
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html> in /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/snappymail/dav/client.php:128
Stack trace:
#0 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(231): SnappyMail\DAV\Client->propFind('https://mydomai...', Array, 1)
#1 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(253): RainLoop\Providers\AddressBook\PdoAddressBook->detectionPropFind(Object(SnappyMail\DAV\Client), '/.well-known/ca...')
#2 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(540): RainLoop\Providers\AddressBook\PdoAddressBook->getContactsPaths(Object(SnappyMail\DAV\Client), 'myusername', '*******', '')
#3 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(602): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient('https://mydomai...', 'myusername', '*******', '')
#4 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Providers/AddressBook.php(46): RainLoop\Providers\AddressBook\PdoAddressBook->Sync('myemail@address.tld', 'https://mydomai...', 'myusername', '*******')
#5 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Actions/Contacts.php(53): RainLoop\Providers\AddressBook->Sync('myemail@address.tld', 'https://mydomai...', 'myusername', '*******')
#6 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoContactsSync()
#7 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Service.php(135): RainLoop\ServiceActions->ServiceJson('')
#8 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Service.php(64): RainLoop\Service->localHandle()
#9 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Service.php(80): RainLoop\Service->__construct()
#10 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/handle.php(47): RainLoop\Service::Handle()
#11 /pathtosnappymail/snappymail/v/2.5.0-rc.3/include.php(242): include('/pathto......')
#12 /pathtosnappymail/index.php(12): include('/pathto......')
#13 {main}
[2021-04-13 14:53:26.797][69a934c1] INFO[DATA]: Array
(
)

[2021-04-13 14:53:26.797][69a934c1] DAV[DATA]: PROPFIND
[2021-04-13 14:53:26.808][69a934c1] INFO[NOTICE]: SnappyMail\HTTP\Exception: 405 Method Not Allowed: PROPFIND https://mydomain.tld
<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html> in /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/snappymail/dav/client.php:128
Stack trace:
#0 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(438): SnappyMail\DAV\Client->propFind('https://mydomai...', Array, 1)
#1 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(586): RainLoop\Providers\AddressBook\PdoAddressBook->checkContactsPath(Object(SnappyMail\DAV\Client), '')
#2 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(602): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient('https://mydomai...', 'myusername', '*******', '')
#3 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Providers/AddressBook.php(46): RainLoop\Providers\AddressBook\PdoAddressBook->Sync('myemail@address.tld', 'https://mydomai...', 'myusername', '*******')
#4 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Actions/Contacts.php(53): RainLoop\Providers\AddressBook->Sync('myemail@address.tld', 'https://mydomai...', 'myusername', '*******')
#5 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoContactsSync()
#6 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Service.php(135): RainLoop\ServiceActions->ServiceJson('')
#7 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Service.php(64): RainLoop\Service->localHandle()
#8 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Service.php(80): RainLoop\Service->__construct()
#9 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/handle.php(47): RainLoop\Service::Handle()
#10 /pathtosnappymail/snappymail/v/2.5.0-rc.3/include.php(242): include('/pathto......')
#11 /pathtosnappymail/index.php(12): include('/pathto......')
#12 {main}
[2021-04-13 14:53:26.809][69a934c1] INFO[NOTICE]: RainLoop\Exceptions\ClientException: ContactsSyncError[140] in /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Actions/Contacts.php:59
Stack trace:
#0 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoContactsSync()
#1 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Service.php(135): RainLoop\ServiceActions->ServiceJson('')
#2 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Service.php(64): RainLoop\Service->localHandle()
#3 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/libraries/RainLoop/Service.php(80): RainLoop\Service->__construct()
#4 /pathtosnappymail/snappymail/v/2.5.0-rc.3/app/handle.php(47): RainLoop\Service::Handle()
#5 /pathtosnappymail/snappymail/v/2.5.0-rc.3/include.php(242): include('/pathto......')
#6 /pathtosnappymail/index.php(12): include('/pathto......')
#7 {main}
[2021-04-13 14:53:26.809][69a934c1] JSON[DATA]: {"Action":"ContactsSync","Result":false,"ErrorCode":140,"ErrorMessage":"","ErrorMessageAdditional":"","Time":605}
[2021-04-13 14:53:26.810][69a934c1] INFO[MEMORY]: Memory peak usage: 2MB
[2021-04-13 14:53:26.810][69a934c1] INFO[TIME]: Time delta: 0.60440015792847
```

**Comment by the-djmaze** [comment]
Yes, i've figured it out!

**Comment by ervee** [comment]
That's some commit(ment) there. I'll see if I can verify this tonight.

**Comment by the-djmaze** [comment]
Copy/merge mine with other people code somehow opened a lot of bugs.
Mine, theirs and others.

Found RainLoop, NextCloud, Synology and mine, so i hope most are solved!

**Comment by phsc84** [comment]
Much appreciate your work!
As soon as you release a new RC, I'm happy to test again.

**Comment by ervee** [comment]
I pulled the 2 changed file and the new file from your commit above and i though it worked again. No error. But when I now open my contacts there are none (zero, nothing, null) contacts anymore. There are still in my CardDAV thank god :)

Just to be sure, I also checked the commit at #2089 but those changes seem to have moved to the new CardDAV.php so I kept the PdoAddressBook.php from the commit above.

**Comment by the-djmaze** [comment]
@ervee i know :cry:
I've removed RainLoop#2089 because the problem i missed there was that he uses array_change_key_case()
XML != HTML so you should never lowercase XML.

So again i made changes to remove array_change_key_case() and fix the code again.

**Comment by the-djmaze** [comment]
Try with:
[snappymail-2.5.0-rc.4.tar.gz](https://github.com/the-djmaze/snappymail/files/6311604/snappymail-2.5.0-rc.4.tar.gz)

**Comment by phsc84** [comment]
[carddav.log](https://github.com/the-djmaze/snappymail/files/6313149/carddav.log)
This is the most recent log. It still does not work...

**Comment by the-djmaze** [comment]
@phsc84
`401 Unauthorized: PROPFIND https://.../apps/cloud/remote.php/dav/addressbooks/users/user/Kontakte/`
Are you sure the username and password are correct?

I've also noticed an issue in AddressBook where it was looking for \class_exists('Sabre\DAV\Client') while it should not.
Try again with:
[snappymail-2.5.0-rc.4.tar.gz](https://github.com/the-djmaze/snappymail/files/6317087/snappymail-2.5.0-rc.4.tar.gz)

**Comment by phsc84** [comment]
Next try with RC4.
[carddav_2021-04-15.log](https://github.com/the-djmaze/snappymail/files/6320343/carddav_2021-04-15.log)

**Comment by phsc84** [comment]
Btw. the hamburger icon is still a little bit strange. Could you add the same spinner as here?
![image](https://user-images.githubusercontent.com/2138442/114919241-4812bc80-9e28-11eb-8d7a-6332f1a4e455.png)

**Comment by phsc84** [comment]
I've applied your latest 2 commits manually. Now the synchronization does not interrupt anymore. But it still does not work (see log and screenshot).
[carddav_2021-04-18.log](https://github.com/the-djmaze/snappymail/files/6330562/carddav_2021-04-18.log)
<img width="678" alt="carddav_2021-04-18" src="https://user-images.githubusercontent.com/2138442/115135732-0138e880-a01b-11eb-958a-f120854fd021.png">

**Comment by the-djmaze** [comment]
Test and now fully working on demo1.nextcloud.com

**Comment by phsc84** [comment]
Now it works like a charm! The spinner is also beautiful!
Congratulations!
