### ISSUE TITLE
problem accessing imap inbox cause of caching issue with redis driver

### ISSUE THREAD

**Issue by thomas-niphba** [the-djmaze/snappymail#792]
**Describe the bug**
Since update 2.24.0 snappymail showns only empty mailboxes. But the count of unread mails in a folder is shown.

**To Reproduce**
1. Update snappymail in nextcloud to 2.24.0
2. Go to 'Inbox'

**Expected behavior**
Mails should be listed

**Please complete the following information:**
- Browser: brave 1.46.144 (chromium 108)
- IMAP daemon: dovecot
- PHP version: 8.1
- SnappyMail Version: 2.24.0

**Additional context**
![2022-12-23_16-43](https://user-images.githubusercontent.com/2904995/209362879-13367a8b-8378-42ab-a2e8-3237f61cd1b9.png)

**Comment by thomas-niphba** [comment]
I have to correct myself.
Mails are listed again, if I disable caching.

WIth enable caching by redis the following logs are written:

[2022-12-23 17:07:38.096][aa4eabcf] SERVICE[WARNING]: - Typed property MailSo\Cache\Drivers\**Redis**::$**sKeyPrefix must not be accessed before initialization** @ /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/MailSo/Cache/Drivers/Redis.php#57
[2022-12-23 17:07:38.096][aa4eabcf] [ERROR]: Error: Typed property MailSo\Cache\Drivers\Redis::$sKeyPrefix must not be accessed before initialization in /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/MailSo/Cache/Drivers/Redis.php:57
Stack trace:
#0 /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/RainLoop/Actions.php(538): MailSo\Cache\Drivers\Redis->__construct()
#1 /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/RainLoop/Actions/Messages.php(901): RainLoop\Actions->Cacher()
#2 /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/RainLoop/Actions/Messages.php(69): RainLoop\Actions->cacherForUids()
#3 /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/RainLoop/ServiceActions.php(137): RainLoop\Actions->DoMessageList()
#4 /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/RainLoop/Service.php(112): RainLoop\ServiceActions->ServiceJson()
#5 /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#6 /usr/share/webapps/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php(141): RainLoop\Service::Handle()
#7 /usr/share/webapps/nextcloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp()
#8 /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->indexPost()
#9 /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#10 /usr/share/webapps/nextcloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#11 /usr/share/webapps/nextcloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#12 /usr/share/webapps/nextcloud/lib/base.php(1047): OC\Route\Router->match()
#13 /usr/share/webapps/nextcloud/index.php(36): OC::handleRequest()
#14 {main}

Next RainLoop\Exceptions\ClientException: **CantGetMessageList**[201] in /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/RainLoop/Actions/Messages.php:81
Stack trace:
#0 /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/RainLoop/ServiceActions.php(137): RainLoop\Actions->DoMessageList()
#1 /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/RainLoop/Service.php(112): RainLoop\ServiceActions->ServiceJson()
#2 /usr/share/webapps/nextcloud/apps/snappymail/app/snappymail/v/2.24.0/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /usr/share/webapps/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php(141): RainLoop\Service::Handle()
#4 /usr/share/webapps/nextcloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp()
#5 /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->indexPost()
#6 /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#7 /usr/share/webapps/nextcloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#8 /usr/share/webapps/nextcloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#9 /usr/share/webapps/nextcloud/lib/base.php(1047): OC\Route\Router->match()
#10 /usr/share/webapps/nextcloud/index.php(36): OC::handleRequest()
#11 {main}
