### ISSUE TITLE
Message list is always empty

### ISSUE THREAD

**Issue by awrede** [the-djmaze/snappymail#799]
**Describe the bug**
Going to any folder results in an "Empty List" message.  Folder list and the unread msg count is displayed properly. 

**To Reproduce**
1. Open "nextcloud" main page.
2. Start SnappyMail app
3. See error

**Expected behavior**
The msgs in the folder should be displayed.

**Screenshots**
Symptoms and therefore screen shot just like in issue #792 

**Please complete the following information:**
- Browser: Firefox  108.0.1, Chrome 108
- IMAP daemon:  fastmail.com
- PHP version: 8.1.12
- SnappyMail Version: 2.24.1

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
```
[2022-12-26 20:49:54.314][8081915b] SERVICE[WARNING]: CantGetMessageList[201]
#0 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/RainLoop/ServiceActions.php(137): RainLoop\Actions->DoMessageList()
#1 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/RainLoop/Service.php(112): RainLoop\ServiceActions->ServiceJson('')
#2 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /nextcloud/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php(141): RainLoop\Service::Handle()
#4 /nextcloud/nextcloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#5 /nextcloud/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->indexPost()
#6 /nextcloud/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#7 /nextcloud/nextcloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#8 /nextcloud/nextcloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#9 /nextcloud/nextcloud/lib/base.php(1047): OC\Route\Router->match('/apps/snappymai...')
#10 /nextcloud/nextcloud/index.php(36): OC::handleRequest()
#11 {main}
[2022-12-26 20:49:54.314][8081915b] SERVICE[WARNING]: - Cannot assign array to property MailSo\Mail\Message::$sEmailId of type ?string @ /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/MailSo/Mail/Message.php#134
[2022-12-26 20:49:54.314][8081915b] [ERROR]: TypeError: Cannot assign array to property MailSo\Mail\Message::$sEmailId of type ?string in /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/MailSo/Mail/Message.php:134
Stack trace:
#0 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/MailSo/Mail/MailClient.php(494): MailSo\Mail\Message::fromFetchResponse('INBOX', Object(MailSo\Imap\FetchResponse))
#1 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/MailSo/Mail/MailClient.php(746): MailSo\Mail\MailClient->MessageListByRequestIndexOrUids(Object(MailSo\Mail\MessageCollection), Object(MailSo\Imap\SequenceSet))
#2 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/RainLoop/Actions/Messages.php(77): MailSo\Mail\MailClient->MessageList(Object(MailSo\Mail\MessageListParams))
#3 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/RainLoop/ServiceActions.php(137): RainLoop\Actions->DoMessageList()
#4 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/RainLoop/Service.php(112): RainLoop\ServiceActions->ServiceJson('')
#5 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#6 /nextcloud/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php(141): RainLoop\Service::Handle()
#7 /nextcloud/nextcloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#8 /nextcloud/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->indexPost()
#9 /nextcloud/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#10 /nextcloud/nextcloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#11 /nextcloud/nextcloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#12 /nextcloud/nextcloud/lib/base.php(1047): OC\Route\Router->match('/apps/snappymai...')
#13 /nextcloud/nextcloud/index.php(36): OC::handleRequest()
#14 {main}

Next RainLoop\Exceptions\ClientException: CantGetMessageList[201] in /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/RainLoop/Actions/Messages.php:81
Stack trace:
#0 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/RainLoop/ServiceActions.php(137): RainLoop\Actions->DoMessageList()
#1 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/RainLoop/Service.php(112): RainLoop\ServiceActions->ServiceJson('')
#2 /nextcloud/nextcloud/apps/snappymail/app/snappymail/v/2.24.1/app/libraries/RainLoop/Service.php(14): RainLoop\Service::RunResult()
#3 /nextcloud/nextcloud/apps/snappymail/lib/Util/SnappyMailHelper.php(141): RainLoop\Service::Handle()
#4 /nextcloud/nextcloud/apps/snappymail/lib/Controller/PageController.php(115): OCA\SnappyMail\Util\SnappyMailHelper::startApp(true)
#5 /nextcloud/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\SnappyMail\Controller\PageController->indexPost()
#6 /nextcloud/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#7 /nextcloud/nextcloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SnappyMail\Controller\PageController), 'indexPost')
#8 /nextcloud/nextcloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main('PageController', 'indexPost', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#9 /nextcloud/nextcloud/lib/base.php(1047): OC\Route\Router->match('/apps/snappymai...')
#10 /nextcloud/nextcloud/index.php(36): OC::handleRequest()
#11 {main}
```

**Additional context**
This is a first-time install of SnappyMail as a Nextcloud app.

**Comment by the-djmaze** [comment]
Could you enable debug mode and post the snappymail log so we can find out what is going on?

**Comment by awrede** [comment]
[log-2022-12-27.txt](https://github.com/the-djmaze/snappymail/files/10305164/log-2022-12-27.txt)
Debug enabled, listing Drafts folder with single test msg
