### ISSUE TITLE
ChangePassword failed in \data\_data_\_default_\plugins\change-password\index.php on line 195

### ISSUE THREAD

**Issue by setoy** [the-djmaze/snappymail#839]
**Describe the bug**
Changing the password via the hMailServer plugin fails with the message mentioned in the title.

```
[2023-01-09 12:51:44.025][eb0360f0] PHP-USER[DEBUG]: ChangePassword failed \snappymail\data\_data_\_default_\plugins\change-password\index.php [line:195, code:1024]
[2023-01-09 12:51:44.026][eb0360f0] SERVICE[WARNING]: UnknownNotification[130]
#0 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\Plugins\Manager.php(377): ChangePasswordPlugin->ChangePassword()
#1 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\ServiceActions.php(140): RainLoop\Plugins\Manager->RunAdditionalJson()
#2 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\Service.php(112): RainLoop\ServiceActions->ServiceJson()
#3 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\Service.php(14): RainLoop\Service::RunResult()
#4 \snappymail\snappymail\v\2.24.4\include.php(172): RainLoop\Service::Handle()
#5 \snappymail\index.php(11): include('...')
#6 {main}
[2023-01-09 12:51:44.026][eb0360f0] [DEBUG]: RainLoop\Exceptions\ClientException: UnknownNotification[130] in \snappymail\data\_data_\_default_\plugins\change-password\index.php:196
Stack trace:
#0 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\Plugins\Manager.php(377): ChangePasswordPlugin->ChangePassword()
#1 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\ServiceActions.php(140): RainLoop\Plugins\Manager->RunAdditionalJson()
#2 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\Service.php(112): RainLoop\ServiceActions->ServiceJson()
#3 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\Service.php(14): RainLoop\Service::RunResult()
#4 \snappymail\snappymail\v\2.24.4\include.php(172): RainLoop\Service::Handle()
#5 \snappymail\index.php(11): include('...')
#6 {main}
[2023-01-09 12:51:44.026][eb0360f0] JSON[DEBUG]: {"Action":"PluginChangePassword","Result":false,"ErrorCode":130,"ErrorMessage":"","ErrorMessageAdditional":"","Time":23}
```

The plugin "Change Password hMailServer" v2.0 is disabled - when trying to enable it I get "Unknown error":
```
[2023-01-09 12:54:48.871][21ff8d10] JSON[DEBUG]: Action: DoAdminPluginDisable
[2023-01-09 12:54:48.871][21ff8d10] POST[DEBUG]: {"Id":"change-password-hmailserver","Disabled":0,"Action":"AdminPluginDisable","XToken":"97118cc40700b9cc6d0356912e9bac456b1e9b08"}
[2023-01-09 12:54:48.871][21ff8d10] Crypt[DEBUG]: openssl_decrypt() with cipher aes-256-cbc-hmac-sha1
[2023-01-09 12:54:48.872][21ff8d10] SERVICE[WARNING]: Class "RainLoop\Actions\Notifications" not found
#0 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\ServiceActions.php(137): RainLoop\ActionsAdmin->DoAdminPluginDisable()
#1 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\Service.php(112): RainLoop\ServiceActions->ServiceJson()
#2 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\Service.php(14): RainLoop\Service::RunResult()
#3 \snappymail\snappymail\v\2.24.4\include.php(172): RainLoop\Service::Handle()
#4 \snappymail\index.php(11): include('...')
#5 {main}
[2023-01-09 12:54:48.872][21ff8d10] [DEBUG]: Error: Class "RainLoop\Actions\Notifications" not found in \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\Actions\AdminExtensions.php:48
Stack trace:
#0 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\ServiceActions.php(137): RainLoop\ActionsAdmin->DoAdminPluginDisable()
#1 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\Service.php(112): RainLoop\ServiceActions->ServiceJson()
#2 \snappymail\snappymail\v\2.24.4\app\libraries\RainLoop\Service.php(14): RainLoop\Service::RunResult()
#3 \snappymail\snappymail\v\2.24.4\include.php(172): RainLoop\Service::Handle()
#4 \snappymail\index.php(11): include('...')
#5 {main}
[2023-01-09 12:54:48.873][21ff8d10] JSON[DEBUG]: {"Action":"AdminPluginDisable","Result":false,"ErrorCode":999,"ErrorMessage":"0 - Class \"RainLoop\\Actions\\Notifications\" not found","ErrorMessageAdditional":"","Time":33}
```

Configuring the "change-password" plugin only offers "ispconfig" and "pdo", but not "hMailServer" anymore.

**Comment by setoy** [comment]
After the notification bugfix, the error notification shows:
`The PHP extension COM must be installed to use this plugin` - so this seems like a configuration issue which wasn't visible at first due to the notification issue.

Now I just have to look on how to enable COM in PHP 8.1. I'll report back.

**Comment by the-djmaze** [comment]
You are welcome
