### ISSUE TITLE
Cannot create folder on hMailServer

### ISSUE THREAD

**Issue by setoy** [the-djmaze/snappymail#885]
**Describe the bug**
When creating a new folder I receive an error message that the folder couldn't be created.

```
[2023-01-29 14:52:05.974][548fd4f1] [ERROR]: InvalidArgumentException in \snappymail\v\2.25.0\app\libraries\MailSo\Mail\MailClient.php:845
Stack trace:
#0 \snappymail\v\2.25.0\app\libraries\RainLoop\Actions\Folders.php(94): MailSo\Mail\MailClient->FolderCreate()
#1 \snappymail\v\2.25.0\app\libraries\RainLoop\ServiceActions.php(137): RainLoop\Actions->DoFolderCreate()
#2 \snappymail\v\2.25.0\app\libraries\RainLoop\Service.php(112): RainLoop\ServiceActions->ServiceJson()
#3 \snappymail\v\2.25.0\app\libraries\RainLoop\Service.php(14): RainLoop\Service::RunResult()
#4 \snappymail\v\2.25.0\include.php(172): RainLoop\Service::Handle()
#5 D:\inetpub\wwwroot\snappymail\index.php(11): include('...')
#6 {main}

Next RainLoop\Exceptions\ClientException: CantCreateFolder[400] in \snappymail\v\2.25.0\app\libraries\RainLoop\Actions\Folders.php:102
Stack trace:
#0 \snappymail\v\2.25.0\app\libraries\RainLoop\ServiceActions.php(137): RainLoop\Actions->DoFolderCreate()
#1 \snappymail\v\2.25.0\app\libraries\RainLoop\Service.php(112): RainLoop\ServiceActions->ServiceJson()
#2 \snappymail\v\2.25.0\app\libraries\RainLoop\Service.php(14): RainLoop\Service::RunResult()
#3 \snappymail\v\2.25.0\include.php(172): RainLoop\Service::Handle()
#4 D:\inetpub\wwwroot\snappymail\index.php(11): include('...')
#5 {main}
```

**Comment by Bolli84** [comment]
I suppose, this also applies on imap? I got the same issue here.

**Comment by phsc84** [comment]
Can confirm, that this is a problem in 2.25.0 also for other IMAP servers than hMail.

**Comment by the-djmaze** [comment]
> Therefore a 2.25.1 release would be much appreciated.

Done :wink:
