### ISSUE TITLE
Error with 25.0.3 upgrade

### ISSUE THREAD

**Issue by mmallejac** [the-djmaze/snappymail#910]
**Describe the bug**
Unable to install Snappymail to 25.0.3, on Nextcloud 25.0.3

**Please complete the following information:**
- PHP version: 8.1.14
- SnappyMail Version: 25.0.3

**[Debug/logging information]**

`docker exec --user www-data client-nextcloud-1 php occ app:enable snappymail`

```php
An unhandled exception has been thrown:

TypeError: MailSo\Base\Http::GetHost(): Return value must be of type string, null returned in /var/www/html/apps/snappymail/app/snappymail/v/2.25.3/app/libraries/MailSo/Base/Http.php:131
Stack trace:
#0 /var/www/html/apps/snappymail/app/snappymail/v/2.25.3/app/libraries/RainLoop/Actions.php(150): MailSo\Base\Http->GetHost(false, false)
#1 /var/www/html/apps/snappymail/app/snappymail/v/2.25.3/app/libraries/RainLoop/Api.php(12): RainLoop\Actions->__construct()
#2 /var/www/html/apps/snappymail/lib/Migration/InstallStep.php(69): RainLoop\Api::Actions()
#3 /var/www/html/lib/private/Repair.php(127): OCA\SnappyMail\Migration\InstallStep->run(Object(OC\Repair))
#4 /var/www/html/lib/private/legacy/OC_App.php(1064): OC\Repair->run()
#5 /var/www/html/lib/private/Installer.php(156): OC_App::executeRepairSteps('snappymail', Array)
#6 /var/www/html/core/Command/App/Enable.php(111): OC\Installer->installApp('snappymail', false)
#7 /var/www/html/core/Command/App/Enable.php(81): OC\Core\Command\App\Enable->enableApp('snappymail', Array, false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/console.php(100): OC\Console\Application->run()
#14 /var/www/html/occ(11): require_once('/var/www/html/c...')
```
 
**Additional context**

So I had to revert manually to 25.0.2.
Our Nextcloud instances are Dockerized. My purpose was to update from Nextcloud 24 to 25 and by the way replace Rainloop with Snappymail.

I have also noticed something else, not sure if related to snappymail : on some instances, I had to move the snappymail folder from `apps/` to `custom_apps/`.
The error message I got before : 
`An error occurred.
Please refresh the page and try again.Failed loading /custom_apps/snappymail/app/snappymail/v/2.25.2/static/js/min/libs.min.js

**Comment by the-djmaze** [comment]
Why are `$_SERVER['SERVER_NAME']` and `$_SERVER['HTTP_HOST']` undefined on your system?

**Comment by the-djmaze** [comment]
Ah i see, SnappyMail can't be installedusing cli yet.

Will look if that will become possible.

**Comment by mmallejac** [comment]
Thanks ! Does this mean that using `occ` is now ok ? Also any idea about `apps` vs `custom_apps` Nextcloud folders ?
