### ISSUE TITLE
Sending mails is broken

### ISSUE THREAD

**Issue by phsc84** [the-djmaze/snappymail#92]
**Describe the bug**
When I try to send a mail, the "Send" button gets red and shows "Unknown error". The exactly same error occurs when I try to store the mail.

**To Reproduce**
1. Compose a new mail.
2. Enter whatever receiver and content.
3. Click "Send".
4. See error.

**Expected behavior**
Mail is sent.

**Desktop (please complete the following information):**
 - Google Chrome Version 90.0.4430.212
 - SnappyMail Version 2.5.1

**Additional context**
```
[2021-05-21 11:28:55.636][dbb1f96d] INFO[NOTICE]: TypeError: Argument 1 passed to MailSo\Mime\Message::SetSender() must be an instance of MailSo\Mime\EmailCollection, instance of MailSo\Mime\Email given, called in /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions/Messages.php on line 1010 and defined in /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.5.1/app/libraries/MailSo/Mime/Message.php:304
Stack trace:
#0 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions/Messages.php(1010): MailSo\Mime\Message->SetSender(Object(MailSo\Mime\Email))
#1 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions/Messages.php(187): RainLoop\Actions->buildMessage(Object(RainLoop\Model\Account), false)
#2 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.5.1/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoSendMessage()
#3 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.5.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#4 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.5.1/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#5 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.5.1/app/handle.php(47): RainLoop\Service::Handle()
#6 /home/httpd/vhosts/url.com/httpdocs/apps/mail/snappymail/v/2.5.1/include.php(242): include('/home/httpd/vho...')
#7 /home/httpd/vhosts/url.com/httpdocs/apps/mail/index.php(12): include('/home/httpd/vho...')
#8 {main}
```

**Comment by ervee** [comment]
I also can't send email after update to 2.5.1. Not sure if this is related but I thought to just post here instead of creating a new bug. If I need to, just say so.

```
--- FlushLogCache: WriteOnErrorOnly
[2021-05-21 12:51:13.800][75dc1efd] INFO[DATA]: [DATE:2021-05-21 UTC][RL:2.5.1][PHP:7.3.28-1+0~20210503.84+debian9~1.gbp6819da][IP:212.61.12.100][PID:21272][nginx/1.18.0][fpm-fcgi]
[2021-05-21 12:51:13.800][75dc1efd] INFO[DATA]: [APC:on][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[2021-05-21 12:51:13.800][75dc1efd] REQUEST[NOTE]: [POST] https://mydomain.tld/webmail/snappymail/?/Json/&q[]=/_2HwQxCMOTLkDyxJv4L0GRrxGF6OFz9zxO9QiPKvGQ6dRPZKqR7kFq3TpPipvfZgruTjr0tFuAjXdWSx6for_38KUpuNu6MF9hfl8LRks65CQh7GuXTDp7-3uqQtRNw9JIjLSD_k3_BcVlXh_J7xEDKvZTKKmIfjt8fwnkX64f92FKTSMaCU0tID-C_JtVK4vSTmS66_TlKnxt1qJiTbw8bNVD-qbwdX_WKqnwvtrlRVIJ2vXXNLCD69mWk3lTh9tuQ59817sSxs7R4nRygtpX4Tnrpy7a0_2N8DsfcGtvyW1aOTjomIOZMlnGllAUWvFRuKhDw/
[2021-05-21 12:51:13.800][75dc1efd] JSON[NOTE]: Action: DoSendMessage
[2021-05-21 12:51:13.800][75dc1efd] POST[DATA]: {"IdentityID":"00061001611000000230","MessageFolder":"","MessageUid":"","SaveFolder":"sent-mail","To":"\"John Doe\" <j.doe@example.com>","Cc":"","Bcc":"","ReplyTo":"","Subject":"Test SnappyMail 2.5.1","TextIsHtml":"1","Text":"<div data-html-editor-font-wrapper=\"true\" style=\"font-family: arial, sans-serif; font-size: 13px;\"><div>###the entire message body..###<\/div><div>John Doe<\/div><\/div>","DraftInfo":"","InReplyTo":"","References":"","MarkAsImportant":"0","Dsn":"0","ReadReceiptRequest":"0","Action":"SendMessage","XToken":"a65c973e3df89e17aa6d52a17f7b6641"}
--- FlushLogCache: Trigger
[2021-05-21 12:51:13.802][75dc1efd] INFO[NOTICE]: RainLoop\Exceptions\ClientException: AuthError[102] in /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions.php:929
Stack trace:
#0 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions.php(969): RainLoop\Actions->GetAccountFromCustomToken('', true, true, true)
#1 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions.php(2036): RainLoop\Actions->getAccountFromToken()
#2 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions/Messages.php(172): RainLoop\Actions->initMailClientConnection()
#3 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoSendMessage()
#4 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#5 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#6 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/handle.php(47): RainLoop\Service::Handle()
#7 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/include.php(242): include('/installpath/.')
#8 /installpath/mydomain.tld/htdocs/webmail/snappymail/index.php(12): include('/installpath/.')
#9 {main}
[2021-05-21 12:51:13.802][75dc1efd] JSON[DATA]: {"Action":"SendMessage","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":31}
[2021-05-21 12:51:13.803][75dc1efd] INFO[MEMORY]: Memory peak usage: 2MB
[2021-05-21 12:51:13.803][75dc1efd] INFO[TIME]: Time delta: 0.022535085678101

--- FlushLogCache: WriteOnErrorOnly
[2021-05-21 12:51:13.869][5a8f26a6] INFO[DATA]: [DATE:2021-05-21 UTC][RL:2.5.1][PHP:7.3.28-1+0~20210503.84+debian9~1.gbp6819da][IP:212.61.12.100][PID:19463][nginx/1.18.0][fpm-fcgi]
[2021-05-21 12:51:13.869][5a8f26a6] INFO[DATA]: [APC:on][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[2021-05-21 12:51:13.869][5a8f26a6] REQUEST[NOTE]: [POST] https://mydomain.tld/webmail/snappymail/?/Json/&q[]=/_2HwQxCMOTLkDyxJv4L0GRrxGF6OFz9zxO9QiPKvGQ6dRPZKqR7kFq3TpPipvfZgruTjr0tFuAjXdWSx6for_38KUpuNu6MF9hfl8LRks65CQh7GuXTDp7-3uqQtRNw9JIjLSD_k3_BcVlXh_J7xEDKvZTKKmIfjt8fwnkX64f92FKTSMaCU0tID-C_JtVK4vSTmS66_TlKnxt1qJiTbw8bNVD-qbwdX_WKqnwvtrlRVIJ2vXXNLCD69mWk3lTh9tuQ59817sSxs7R4nRygtpX4Tnrpy7a0_2N8DsfcGtvyW1aOTjomIOZMlnGllAUWvFRuKhDw/
[2021-05-21 12:51:13.869][5a8f26a6] JSON[NOTE]: Action: DoFolderInformation
[2021-05-21 12:51:13.869][5a8f26a6] POST[DATA]: {"Folder":"saved-drafts","FlagsUids":"","UidNext":"","Action":"FolderInformation","XToken":"a65c973e3df89e17aa6d52a17f7b6641"}
--- FlushLogCache: Trigger
[2021-05-21 12:51:13.870][5a8f26a6] INFO[NOTICE]: RainLoop\Exceptions\ClientException: AuthError[102] in /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions.php:929
Stack trace:
#0 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions.php(969): RainLoop\Actions->GetAccountFromCustomToken('', true, true, true)
#1 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions.php(2036): RainLoop\Actions->getAccountFromToken()
#2 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions/Folders.php(358): RainLoop\Actions->initMailClientConnection()
#3 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoFolderInformation()
#4 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#5 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#6 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/handle.php(47): RainLoop\Service::Handle()
#7 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/include.php(242): include('/installpath/.')
#8 /installpath/mydomain.tld/htdocs/webmail/snappymail/index.php(12): include('/installpath/.')
#9 {main}
[2021-05-21 12:51:13.872][5a8f26a6] JSON[DATA]: {"Action":"FolderInformation","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":8}
[2021-05-21 12:51:13.873][5a8f26a6] INFO[MEMORY]: Memory peak usage: 2MB
[2021-05-21 12:51:13.873][5a8f26a6] INFO[TIME]: Time delta: 0.0089221000671387

--- FlushLogCache: WriteOnErrorOnly
[2021-05-21 12:51:24.587][29db2ba6] INFO[DATA]: [DATE:2021-05-21 UTC][RL:2.5.1][PHP:7.3.28-1+0~20210503.84+debian9~1.gbp6819da][IP:212.61.12.100][PID:21272][nginx/1.18.0][fpm-fcgi]
[2021-05-21 12:51:24.587][29db2ba6] INFO[DATA]: [APC:on][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[2021-05-21 12:51:24.588][29db2ba6] REQUEST[NOTE]: [GET] https://mydomain.tld/webmail/snappymail/?/Json/&q[]=/_2Hw[...snip...]hDw/Message/&q[]=/SU5CT1gANTg4NzMANDViMTYyZTQxZDc5MzM0ZTc5MDc1ZjRhMjU0NWExZTMAMQ=
[2021-05-21 12:51:24.588][29db2ba6] JSON[NOTE]: Action: DoMessage
--- FlushLogCache: Trigger
[2021-05-21 12:51:24.591][29db2ba6] INFO[NOTICE]: RainLoop\Exceptions\ClientException: AuthError[102] in /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions.php:929
Stack trace:
#0 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions.php(969): RainLoop\Actions->GetAccountFromCustomToken('', true, true, true)
#1 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions.php(2036): RainLoop\Actions->getAccountFromToken()
#2 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Actions/Messages.php(479): RainLoop\Actions->initMailClientConnection()
#3 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/ServiceActions.php(143): RainLoop\Actions->DoMessage()
#4 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Service.php(132): RainLoop\ServiceActions->ServiceJson('')
#5 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/libraries/RainLoop/Service.php(38): RainLoop\Service->RunResult()
#6 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/app/handle.php(47): RainLoop\Service::Handle()
#7 /installpath/mydomain.tld/htdocs/webmail/snappymail/snappymail/v/2.5.1/include.php(242): include('/installpath/.')
#8 /installpath/mydomain.tld/htdocs/webmail/snappymail/index.php(12): include('/installpath/.')
#9 {main}
[2021-05-21 12:51:24.593][29db2ba6] JSON[DATA]: {"Action":"Message","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":12}
[2021-05-21 12:51:24.655][29db2ba6] INFO[MEMORY]: Memory peak usage: 2MB
[2021-05-21 12:51:24.656][29db2ba6] INFO[TIME]: Time delta: 0.073095083236694
```

**Comment by the-djmaze** [comment]
This issue is resolved with the above mentioned commit
